### PR TITLE
fix the fatal bug of the convolution calculation part of the Minkowski sum

### LINKED ISSUE #8551: minkowski_sum has fatal bug for some special linestring and polygon
## Issue Details

./main
CGAL version: 6.0.0
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: sl_iter != m_statusLine.end()
File: /usr/local/include/CGAL/Surface_sweep_2/No_intersection_surface_sweep_2_impl.h
Line: 547
adopted

## Source Code

// main.cpp
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/minkowski_sum_2.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/Polygon_with_holes_2.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Polygon_2<K> Polygon_2;
typedef CGAL::Polygon_with_holes_2<K> Polygon_with_holes_2;

int main() {
        std::cout << "CGAL version: "
              << CGAL_VERSION_MAJOR << "."
              << CGAL_VERSION_MINOR << "."
              << CGAL_VERSION_PATCH << std::endl;
    // Define a simple polygon (first geometry)
    Polygon_2 P;
    P.push_back(K::Point_2(824, 627));
    P.push_back(K::Point_2(689, 555));

    // Define another simple polygon (second geometry)
    Polygon_2 Q;
    Q.push_back(K::Point_2(130, 150));
    Q.push_back(K::Point_2(20, 40));
    Q.push_back(K::Point_2(50, 60));
    Q.push_back(K::Point_2(125, 100));

    // Compute Minkowski sum (correct type)
    Polygon_with_holes_2 sum = CGAL::minkowski_sum_by_full_convolution_2(P, Q);

    // Output result (just an example)
    std::cout << "Minkowski sum computed successfully." << std::endl;

    return 0;
}

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64bits
* Compiler: g++ or MSVC
* Release or debug mode: debug mode raise error, release mode crush
* Specific flags used (if any):
* CGAL version: 6.0, or 5.6, or 5.0 all have problem
* Boost version: 1.71 or 1.73
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by Garbage123King**
## Summary of Changes
Modify the convolution calculation part of the Minkowski sum. In the 'elimination of antennas' phase, before I fix it, only the antennas of the first segment were eliminated, skipping the possible subsequent antennas. For more details, please refer to the explanation in the issue. I modified it so that if a new antenna is merged, the newly merged antenna is used as `curr` for the next iteration; otherwise, `after_next` is used as `curr`.

## Release Management
* Affected package(s): Minkowski_sum_2
* Issue(s) solved: fix #8551

### CODE REVIEW

File: Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h
Comment (efifogel) [inline Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h:1]: First, good job on spotting and fixing.
A more simple (and I guess efficient) fix is simply replacing Line 614:
      -          cycle.insert(curr,
      +          after_next = cycle.insert(curr,

File: Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h [hunk 1]
```diff
@@ -533,7 +533,7 @@ class Minkowski_sum_by_convolution_2 {
     // list for subsequences sharing a common move_on indicator. When we
     // encounter such a subsequence that equals the size of the corresponding
     // polygon, we can safely remove it from the convolution cycle.
-    typename std::list<Labeled_segment_2>::iterator  first, curr;
+    typename std::list<Labeled_segment_2>::iterator  first, curr, newins;
```
Comment (sloriot) [inline Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h:536]:
```suggestion
    typename std::list<Labeled_segment_2>::iterator  first, curr;
```

File: Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h [hunk 2]
```diff
@@ -611,7 +611,7 @@ class Minkowski_sum_by_convolution_2 {
         res = f_compare_xy(curr_pt, next_pt);
 
         if (res != EQUAL) {
-          cycle.insert(curr,
+          newins = cycle.insert(curr,
```
Comment (sloriot) [inline Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h:614]:
```suggestion
          after_next = cycle.insert(curr,
```

File: Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h [hunk 3]
```diff
@@ -621,7 +621,13 @@ class Minkowski_sum_by_convolution_2 {
...
         cycle.erase(curr);
         cycle.erase(next);
-        curr = after_next;
+        if (res != EQUAL) {
+          //continue comparing the new combined line with the next line
+          curr = newins;
+        }
+        else {
+          curr = after_next;
+        }
```
Comment (sloriot) [inline Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h:630]:
```suggestion
        curr = after_next;
```

File: Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h
Comment (sloriot) [reply Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h:1]: I updated the code. We agree on the fix now?

**Review by efifogel — APPROVED** [review]

**Comment by efifogel** [comment]
BW, consider the Minkowski sum of two 2 segments, that is, two degenerate polygons.
I've noticed that now, while the full-convolution method works, the reduced convolution (which is the default) fails.
The decomposition method also works on this case.
I guess more rigorous tests are needed, but the manual does not say that such degenerate cases are expected to work though. As Garbase123King said, mathematically, they should all work...

**Comment by sloriot** [comment]
Successfully tested in CGAL 6.1-Ic-15
