### PR TITLE
AABB_tree : fix doc vs code inconsistency

### LINKED ISSUE #260: Wrong functor required/used
The AABBGeomTraits require the functor [Compute_closest_point_3](http://doc.cgal.org/latest/AABB_tree/classAABBGeomTraits.html#a97e587bad84dcd1e90d00fb18a134762), but this signature is never used in `AABB_tree` code.

The class `AABB_traits`  provides a functor `Closest_point` which calls the free function `internal::nearest_point_3` which seems to be used instead. Note that even if this functor is renamed it is still in the wrong class (should be in the geomtraits).

### PR DESCRIPTION
**Pull request by janetournois**
partially fixes #260 

The doc mentions `Compute_closest_point_3`, and code implements `Closest_point`

<< edit
First, `Compute_closest_point_3` should be `Construct_closest_point_3`.
<< end edit

since ~~`Compute_closest_point_3`~~ `Construct_closest_point_3` should move to the Kernel at some point, I prefer to keep this option
However, for backward compatibility with possibly existing user code, I keep Closest_point
in the non-documented code.

### CODE REVIEW

**Comment by janetournois** [comment]
will be tested in [CGAL-4.9-Ic-125](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-125.shtml)

**Comment by janetournois** [comment]
the testsuite looks good

File: AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h [hunk 1]
```diff
@@ -145,10 +145,10 @@ A functor object to compute distance comparisons between the query and the nodes
 typedef unspecified_type Compare_distance; 
 
 /*!
-A functor object to compute closest point from the query on a primitive. Provides the operator: 
+A functor object to construct closest point from the query on a primitive. Provides the operator: 
 `Point_3 operator()(const Query& query, const Primitive& primitive, const Point_3 & closest);` which returns the closest point to `query`, among `closest` and all points of the primitive. 
 */ 
-typedef unspecified_type Closest_point; 
+typedef unspecified_type Construct_closest_point;
```
Comment (sloriot) [inline AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h]: I guess your missing _3 here

**Comment by sloriot** [comment]
I guess you're missing some changes in the code using the traits class, otherwise the changes done in the concept are not taken into account. (Or I'm missing something)

**Comment by janetournois** [comment]
this should be taken into account in #1341 and #1350

**Comment by sloriot** [comment]
Changes were imported in #1350
