### PR TITLE
Fix a perturber bug

### LINKED ISSUE #1944: Mesh_3: bug in perturber
*While debugging something else, a ctest run showed strange failures in another test...*

In `master` (currently 2249dfde063b2d359a93f4e46c9e5ca06789c5f3), if I add the following patch:
```patch
diff --git a/Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h b/Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
index 6b3f73f..2ef57f8 100644
--- a/Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
+++ b/Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
@@ -3374,6 +3374,8 @@ get_least_square_surface_plane(const Vertex_handle& v,
 
   reference_point = surface_point_vector.front();
 
+  CGAL_assertion(is_valid(plane.d()));
+
   return plane;
 }
 
diff --git a/Mesh_3/test/Mesh_3/debug.h b/Mesh_3/test/Mesh_3/debug.h
index 886fa14..30172eb 100644
--- a/Mesh_3/test/Mesh_3/debug.h
+++ b/Mesh_3/test/Mesh_3/debug.h
@@ -17,7 +17,7 @@
 // #define CGAL_MESHES_DEBUG_REFINEMENT_POINTS
 // #define CGAL_DEBUG_OCTREE_CONSTRUCTION
 
-//#define CGAL_MESH_3_VERBOSE
+#define CGAL_MESH_3_VERBOSE
 //#define CGAL_MESH_3_IO_VERBOSE
 
 // #define OPTIMIZE_INTERSECTION

```

then the test `test/Mesh_3/test_mesh_implicit_domains.cpp` fails. That shows that, for some reason, there are `NaN` numbers computed in the `get_least_square_surface_plane` function. I found out that there are "surface centers" with NaN numbers too. Probably some duals are degenerate in floating points, and should be computed robustly.

I failed to reproduce the bug with CGAL-4.9. I do not know why.

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

The `facet_surface_center` of facet was not always restored correctly,
after an aborted move, and that eventually led to use of uninitialized
memory... and a crash.

## Release Management

* Affected package(s): Mesh_3
* Issue(s) solved (if any): fix #1944

### CODE REVIEW

File: Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h [hunk 1]
```diff
@@ -1514,7 +1514,8 @@ class C3T3_helpers
           c3t3.remove_from_complex(Facet(c,i));
 
         c->set_facet_surface_center(i, facet_surface_center_[old_i]);
-        c->set_facet_surface_center_index(i, surface_center_index_table_[old_i]);
+        const Facet mirror = c3t3.triangulation().mirror_facet(Facet(c, i));
+        mirror.first->set_facet_surface_center(mirror.second, facet_surface_center_[old_i]);
```
Comment (janetournois) [inline Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h]: I totally agree with the 2 added lines (and hardly believe they have never been there!)

File: Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h [hunk 2]
```diff
@@ -1514,7 +1514,8 @@ class C3T3_helpers
           c3t3.remove_from_complex(Facet(c,i));
 
         c->set_facet_surface_center(i, facet_surface_center_[old_i]);
-        c->set_facet_surface_center_index(i, surface_center_index_table_[old_i]);
```
Comment (janetournois) [inline Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h]: why do you remove this?

Comment (lrineau) [reply Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h]: Because the code `c3t3.add_to_complex(Facet(c, i), index);` or `c3t3.remove_from_complex(Facet(c,i));`, a few line above, has already restored the index, using the API of the C3t3.

Comment (janetournois) [reply Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h]: ok!

**Comment by lrineau** [comment]
You are right Mael. It is fixed in https://github.com/CGAL/cgal/pull/2541/commits/6178c04cf1ea1d04edabb45bfbdac378297944d0.

**Comment by janetournois** [comment]
@lrineau does it fix the bug you met?

**Comment by lrineau** [comment]
No! :-(
