### PR TITLE
Fixes for the Demo

### LINKED ISSUE #4378: CGAL 3D demo: duplicate crash
Load a mesh, color its CCs, ctrl+D --> segfault

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

Some more fixes for the demo.

Fixes #4378

### CODE REVIEW

**Comment by afabri** [comment]
@maxGimeno Can you target the 5 bugfix release please.

File: Polyhedron/demo/Polyhedron/MainWindow.cpp [hunk 1]
```diff
@@ -1804,7 +1808,9 @@ void MainWindow::readSettings()
     viewer->setFastDrawing(settings.value("quick_camera_mode", true).toBool());
     scene->enableVisibilityRecentering(settings.value("offset_update", false).toBool());
     viewer->textRenderer()->setMax(settings.value("max_text_items", 10000).toInt());
-    viewer->setTotalPass(settings.value("transparency_pass_number", 4).toInt());
+    int val  = settings.value("transparency_pass_number", 4).toInt();
+    if (val < 4 ) val = 4;
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/MainWindow.cpp]:
```suggestion
    if (val < 4 ) {
      val = 4;
      settings.setValue("transparency_pass_number", 4);
    }
```

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-53.shtml
