### PR TITLE
Polyhedron_demo : Fix deformation

### LINKED ISSUE #1193: Loading an off while deforming another...
.. ends up creating another deformation object. This is inconsistent with some changes done by @maxGimeno to avoid deforming more than one item at once.

### LINKED ISSUE #1194: Show ROI checkbox is broken
in deformation plugin.

I had "show as sphere checked" when I tried to hide the ROI. When unchecking "show as spheres" ROI and control vertices are not shown and they won't show up even if I check "show ROI"

@maxGimeno

### LINKED ISSUE #1197: Extending ROI/Control vertices partially working
screenshot from 2016-06-23 13-26-00

I selected the ROI and then only one control point. I used the mouse wheel to extend the region.

In the package, note that the ROI is the region that is allowed to move, and they contains the control vertices.

cc @maxGimeno

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR fixes some bugs in the Edit_polyhedron_plugin (fixes #1193, fixes #1194 and fixes #1197 ).

### CODE REVIEW

File: Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp [hunk 1]
```diff
@@ -421,7 +421,17 @@ void Polyhedron_demo_edit_polyhedron_plugin::on_BrushSpinBoxRoi_changed(int valu
...
 void Polyhedron_demo_edit_polyhedron_plugin::new_item_created(int item_id)
 {
-  if(dock_widget->isVisible()) {
+  Scene_polyhedron_selection_item* selection_item = NULL;
+  for(int i = 0; i<scene->numberOfEntries(); i++)
+  {
+    selection_item = qobject_cast<Scene_polyhedron_selection_item*>(scene->item(i));
+    if (selection_item)
+      break;
+    else
```
Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp]: I guess setting it to NULL is useless since it is already

File: Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp [hunk 2]
```diff
@@ -421,7 +421,17 @@ void Polyhedron_demo_edit_polyhedron_plugin::on_BrushSpinBoxRoi_changed(int valu
...
+      selection_item = NULL;
```
Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp]: BTW, I don't see why we need this function at all now.

File: Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp [hunk 3]
```diff
@@ -751,53 +765,74 @@ struct Is_selected_property_map{
...
+    if(ctrl_active)
+      expand_vertex_selection(active_group->ctrl_vertices_group, *poly_item->polyhedron(), steps, Is_selected_property_map(mark),
+                            CGAL::Emptyset_iterator());
+    else
+      expand_vertex_selection(deform_mesh->roi_vertices(), *poly_item->polyhedron(), steps, Is_selected_property_map(mark),
                             CGAL::Emptyset_iterator());
+  }
   else
-    reduce_vertex_selection(deform_mesh->roi_vertices(), *poly_item->polyhedron(), -steps, Is_selected_property_map(mark),
+  { if(ctrl_active)
```
Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp]: identation issue

File: Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp [hunk 4]
```diff
@@ -751,53 +765,74 @@ struct Is_selected_property_map{
...
+    }
+    else
+    {
+      if(!deform_mesh->is_control_vertex(v))
+        mark[v->id()]=true;
+    }
   }
-
+  std::vector<bool> patron = mark;
   if(steps > 0)
```
Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp]: `patron` should be translated to `mask`

**Comment by sloriot** [comment]
I tested the branch and I confirm it fixes the 3 aforementioned issues

**Comment by sloriot** [comment]
In 4.7, the control vertices not in the current group were displayed in blue. Red was for the currently selected group

File: Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp [hunk 5]
```diff
@@ -1220,6 +1309,10 @@ void Scene_edit_polyhedron_item::reset_spheres()
 {
   d->spheres = NULL;
 }
+void Scene_edit_polyhedron_item::reset_spheres_ctrl()
+{
+  d->spheres_ctrl = NULL;
+}
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp]: (A general note for everybody modifying the Polyhedron demo. cc @sloriot)
The new API of [`QObject::connect`][c] allows to connect a signal to a functor. There is no longer the needs to add slots, and this modify the the `.h`.

If C++11 was allowed, the connection would be really simple, with a lambda expression:
```C++
connect(d->spheres_ctrl, &QObject::destroyed, this, [this] () { this->d->spheres_ctrl = NULL} );
```
The expression `[this] () { this->d->spheres_ctrl = NULL}` is a lambda-expression, that captures the value of `this`.

Without C++11, it can be done almost as easily:
```C++
struct Reset_spheres_ctrl {
  Scene_edit_polyhedron_item_priv* d;
  Reset_spheres_ctrl(Scene_edit_polyhedron_item_priv* d) : d(d) {}
  void operator()() const { d->spheres_ctrl = NULL; }
};
// [...]
connect(d->spheres_ctrl, &QObject::destroyed, this, Reset_spheres_ctrl(d) );
```
[c]: http://doc.qt.io/qt-5/qobject.html#connect-5

See also [New Signal Slot Syntax in Qt 5, in the wiki of Qt][*]. @maxGimeno: please read that document. You will see that it is really interesting.
[*]: https://wiki.qt.io/New_Signal_Slot_Syntax

I really would like that we allow to use C++11 in our demos. With CMake>=3.1, that is as simple as:
```CMake
target_compile_features(my_plugin PRIVATE cxx_lambdas)
```

**Comment by maxGimeno** [comment]
Color fixed.
