### PR TITLE
fix #572

### LINKED ISSUE #572: CDT Seg Faults
I noticed a seg fault deep down inside CGAL CDT.  Here is a minimal example to reproduce the issue:

https://gist.github.com/qnzhou/e997f6a04be5dfd169f9

Testing environment:
OS: OS X 10.10.5 and Linux
CGAL version: 4.7 (installed through mac port) and 4.5
Compiler: Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn) and gcc4.9.2

~~Update: I made a mistake in the minimal example which causes the crash.  I am working on an updated one.  Sorry.~~
Update2: The minimal example should now reproduce the seg fault.

Here is the visualization of the constraints for the CDT:
image

### PR DESCRIPTION
**Pull request by afabri**
The strategy of finding border edges not inside the conflict zone had a bug.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-92

File: Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h [hunk 1]
```diff
@@ -798,23 +798,16 @@ insert_subconstraint(Vertex_handle vaa,
...
-    it2 = it;
-    ++it2;
-    for(; it2 != edges.end();){
-      Edge e1 = *it, e2 = *it2;
-      if(this->mirror_edge(e1) == e2){
-        typename List_edges::iterator del = it;
-        --it;
-        edges.erase(del);
+
+  std::set<Face_handle> faces(intersected_faces.begin(), intersected_faces.end());
```
Comment (lrineau) [inline Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h]: `boost::flat_set`, from Boost.Container, would probably be more efficient, memory-wise. It was introduced in Boost-1.48, that is required by CGAL as the minimal version of Boost. That is safe to use it.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-94
