### PR TITLE
Demo: Fix grid axes scaling + use basic shader

### LINKED ISSUE #6815: Polyhedron demo axis bug
**Reopening #6775**

When pressing `G` key, the following axis is prompted:  
image

But now if I generate a sphere with d=10, the arrows are deformed :  
image

And with d=100 :  
image

This is not due to the generation of 3D objects, it is the same problem if I import a 3D file.  

There must surely be an error in the width of the arrow relative to the size of the scene.  

___

Platform: Windows 10
Demo: Pre-compiled demo/DLLs found on the website

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

While fixing the grid axes scaling, I have also changed the shader to simply use the basic one rather than the specific one that used lighting because:
- It's less code
- It's lighter shader
- It looks objectively better on some parts (for example, the base of the cone is not drawn, and that's visible with the light-based shader)
- It looks better overall (subjective).

Here is a comparison:

grid_axes

## Release Management

* Affected package(s): `Polyhedron`
* Issue(s) solved (if any): fix #6815
* Feature/Small Feature (if any): -
* License and copyright ownership: no change

### CODE REVIEW

File: GraphicsView/include/CGAL/Qt/qglviewer_impl.h [hunk 1]
```diff
@@ -3261,55 +3142,36 @@ void CGAL::QGLViewer::drawArrow(double r,double R, int prec, CGAL::qglviewer::Ve
...
   for(int d = 0; d<360; d+= 360/prec)
   {
-      float D = (float) (d * CGAL_PI / 180.);
-      float a = (float) std::atan(Rf / 0.33);
-      QVector4D p(0., 1., 0, 1.);
-      QVector4D n(Rf*sin(D), sin(a), Rf*cos(D), 1.);
-      QVector4D pR = mat*p;
-      QVector4D nR = mat*n;
+      float D = float(d * CGAL_PI / 180.);
+      float a = float(std::atan(Rf / 0.33));
```
Comment (sloriot) [inline GraphicsView/include/CGAL/Qt/qglviewer_impl.h:3146]: warning: unused variables

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-79
