### PR TITLE
Fix some UB / sanitizer errors

### LINKED ISSUE #5855: test_triangulation_2 failure under -fsanitize=null
## Issue Details

While building the master branch and running test_triangulation_2 with -fsanitize=null I get a runtime error.

`
/repos/cgal/STL_Extension/include/CGAL/Compact_container.h:1047:42: runtime error: reference binding to null pointer of type 'CGAL::Triangulation_face_base_2<CGAL::Simple_cartesian<CGAL::Quotient<CGAL::MP_Float>>, CGAL::Triangulation_ds_face_base_2<CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<CGAL::Simple_cartesian<CGAL::Quotient<CGAL::MP_Float>>, CGAL::Triangulation_ds_vertex_base_2<void>>, CGAL::Triangulation_face_base_2<CGAL::Simple_cartesian<CGAL::Quotient<CGAL::MP_Float>>, CGAL::Triangulation_ds_face_base_2<void>>>>>'
`

```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /repos/cgal/STL_Extension/include/CGAL/Compact_container.h:1047:42 in 
```

Repro steps:
1. clone the repo
2. cd /path/to/cgal/Triangulation_2/test/Triangulation_2
3. mkdir -p build/debug
4. cd build/debug
5.  cmake -DCMAKE_BUILD_TYPE=Debug -DCGAL_DIR=/path/to/cgal/ -DCMAKE_CXX_FLAGS="-fsanitize=null" ../../
6. make test_triangulation_2
7. ./test_triangulation_2 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64 bit
* Compiler: c++ (Debian 10.2.1-6+build2) 10.2.1 20210110
* Release or debug mode: Debug
* Specific flags used (if any): -fsanitize=null
* CGAL version: master (but i was specifically at 529add28d337301ae96365c0b929bbb628c864fd)
* Boost version: I believe boost 1.74
* Other libraries versions if used (Eigen, TBB, etc.): N/A

## Partial solution
It appears that a long time ago the handling for dim <0 changed inside copy_tds and it might be the cause of this bug.
I found this relevant [diff](https://github.com/CGAL/cgal/commit/f19e9553dfae71109e9b9c8258c260fbfdfaadcc#diff-b59d2b479118e06a4da39d478d33c8b692b604b92a5318d826ec821800e43915L1371) while looking for an answer.

Similarly it should use faces_begin() instead of faces().begin() which solved one of the issues with the test as faces_begin handles the dim < 0 case better.
https://github.com/CGAL/cgal/blob/529add28d337301ae96365c0b929bbb628c864fd/TDS_2/include/CGAL/Triangulation_data_structure_2.h#L2021
https://github.com/CGAL/cgal/blob/529add28d337301ae96365c0b929bbb628c864fd/TDS_2/include/CGAL/Triangulation_data_structure_2.h#L2035

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

Fix a number of small abuses resulting in UB / sanitizer errors.

Minor optimization in `TDS_3::copy_tds()`.

## Release Management

* Affected package(s): `TDS_23`, `Triangulation_23`
* Issue(s) solved (if any): fix #5855
* Feature/Small Feature (if any): NA
* License and copyright ownership: No change

In dim -1, there is only one vertex and one face, no neighbor
in position '0' to set.

### CODE REVIEW

File: TDS_2/include/CGAL/Triangulation_data_structure_2.h [hunk 1]
```diff
@@ -2021,10 +2024,10 @@ copy_tds(const TDS_src& tds_src,
   //update vertices and neighbor pointers
   fit1 = tds_src.faces().begin();
   for ( ; fit1 != tds_src.faces_end(); ++fit1) {
-      for (int j = 0; j < dim ; ++j) {
+      for (int j = 0; j < dim ; ++j)
         fmap[fit1]->set_vertex(j, vmap[fit1->vertex(j)] );
+      for (int j = 0; j < nn ; ++j)
         fmap[fit1]->set_neighbor(j, fmap[fit1->neighbor(j)]);
```
Comment (lrineau) [inline TDS_2/include/CGAL/Triangulation_data_structure_2.h:2030]: Andreas will certainly tell you that all for-loop should be followed by a compound statement (a *block*, with braces).

File: TDS_3/include/CGAL/Triangulation_data_structure_3.h [hunk 2]
```diff
@@ -4039,32 +4039,27 @@ copy_tds(const TDS_src& tds,
...
+  // Initializes maps
   Unique_hash_map< typename TDS_src::Vertex_handle,Vertex_handle > V;
   Unique_hash_map< typename TDS_src::Cell_handle,Cell_handle > F;
 
-  for (i=0; i <= n-1; ++i){
-    Vertex_handle vh=create_vertex( convert_vertex(*TV[i]) );
-    V[ TV[i] ] = vh;
-    convert_vertex(*TV[i],*vh);
+  // Create the vertices.
+  for (typename TDS_src::Vertex_iterator vit = tds.vertices_begin();
```
Comment (lrineau) [inline TDS_3/include/CGAL/Triangulation_data_structure_3.h:4058]:
```suggestion
  for (auto vit = tds.vertices_begin();
```

**Comment by maxGimeno** [comment]
tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-26.shtml
