### PR TITLE
Compute and fix packages dependencies

### LINKED ISSUE #1483: Triangulation_2 includes a file from Triangulation_3
The three following files:
```
Triangulation_2/include/CGAL/Delaunay_triangulation_2.h
Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h
Triangulation_2/include/CGAL/Regular_triangulation_2.h
```
include `Triangulation_3/include/CGAL/internal/info_check.h`.

### LINKED ISSUE #1484: A file from Generator (LGPL) includes a file from PCA (GPL)
`Generator/include/CGAL/random_convex_set_2.h` includes `<CGAL/centroid.h>` from PCA!

### LINKED ISSUE #1485: A file from BGL includes a file from T_2
`BGL/include/CGAL/Triangulation_vertex_base_with_id_2.h` should be move to the `Triangulation_2` package.

### LINKED ISSUE #1492: LCC (LGPLv3+) includes headers from Triangulation_3 (GPLv3+)
The file `<CGAL/Linear_cell_complex_constructors.h>` from LCC (under LGPLv3+) includes:
```C++
#include <CGAL/Triangulation_2.h>
#include <CGAL/Triangulation_3.h>
```
from GPLv3+ packages. That breaks the license, making the file GPLv3. That also breaks a license checking feature we are trying to integrate into CGAL.

That header is documented in [Constructions for Linear Cell Complex](http://doc.cgal.org/latest/Linear_cell_complex/group__PkgLinearCellComplexConstructions.html).

### LINKED ISSUE #1494: PMP includes one headers from Mesh_3
`Mesh_3/include/CGAL/Mesh_3/dihedral_angle_3.h` is included by `<CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h>`.

The computation of the dihedral angle should be moved to a LGPL package, to avoid that dependency.

### PR DESCRIPTION
**Pull request by lrineau**
Fix #1483.
Fix #1484.
Fix #1485.
Fix #1492.
Fix #1494.

### CODE REVIEW

File: STL_Extension/test/STL_Extension/test_Object.cpp [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 #include <CGAL/Object.h>
 #include <CGAL/assertions.h>
+#include <CGAL/use.h>
```
Comment (lrineau) [inline STL_Extension/test/STL_Extension/test_Object.cpp]: > How did that get included before??? 

It is included by `<CGAL/Algebraic_structure_traits.h>`, that is one of the dependencies of `<CGAL/basic.h>`.
