### PR TITLE
Spatial searching: Make weighted Minkowski Distance working with Epeck

### LINKED ISSUE #7194: Weighted_Minkowski_Distance in Spatial searching not working with exact kernels
## Issue Details

When trying to compile a spatial search with an exact kernel using weighted Minkowski distance we get a compiler error due to FT being passed in directly to `std::pow()` in the source code for Weighted_Minkowksi_Distance:

https://github.com/CGAL/cgal/blob/5f205d35068b5fb951f8e5d95654c99827f65a7e/Spatial_searching/include/CGAL/Weighted_Minkowski_distance.h#L360

## Source Code

Modified from the Minkowski example in the spatial searching docs

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Orthogonal_k_neighbor_search.h>
#include <CGAL/Weighted_Minkowski_distance.h>
#include <CGAL/Search_traits_2.h>
#include <CGAL/point_generators_2.h>
typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef K::Point_2 Point_d;
typedef CGAL::Random_points_in_square_2<Point_d> Random_points_iterator;
typedef CGAL::Counting_iterator<Random_points_iterator> N_Random_points_iterator;
typedef CGAL::Search_traits_2<K> TreeTraits;
typedef CGAL::Weighted_Minkowski_distance<TreeTraits> Distance;
typedef CGAL::Orthogonal_k_neighbor_search<TreeTraits, Distance> K_neighbor_search;
typedef K_neighbor_search::Tree Tree;

[[cpp11::register]]
int main()
{
  const int D = 2;
  const int N = 1000;
  const unsigned int K = 5;
  Random_points_iterator rpit( 1.0);
  Tree tree(N_Random_points_iterator(rpit,0),
            N_Random_points_iterator(N));
  Point_d query(0,0);
  double w[2] = { 1.0, 2.0};
  Distance tr_dist(3.14,D,w, w+D);
  K_neighbor_search search(tree, query, K, 0.0, true, tr_dist);
  for (K_neighbor_search::iterator it = search.begin(); it!=search.end(); ++it)
    std::cout << "Point " << (*it).first << " at distance = " << (*it).second << std::endl;
  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac M1
* Compiler: clang
* Release or debug mode: release
* Specific flags used (if any): =-DCGAL_DO_NOT_USE_BOOST_MP -DCGAL_USE_GMPXX -DBOOST_NO_AUTO_PTR
* CGAL version: 5.5.1
* Boost version: 1.81.0
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

As the power computation with an arbitrary number does not work for all number types we pass via  double arithmetic.
This might in the future be optimized, for example for integral powers.

## Release Management

* Affected package(s): Spatial_searching
* Issue(s) solved (if any): fix #7194
* License and copyright ownership: unchanged

### CODE REVIEW

File: Spatial_searching/doc/Spatial_searching/CGAL/Weighted_Minkowski_distance.h [hunk 1]
```diff
@@ -10,6 +10,9 @@ defined by \f$ l_{\infty}(w)(r,q)=max \{w_i |r_i-q_i| \mid 1 \leq i \leq d\}\f$.
 For the purpose of the distance computations it is more efficient to compute
 the transformed distance \f$ {\sigma_{i=1}^{i=d} \, w_i(r_i-q_i)^p}\f$ instead of the actual distance.
 
+\note As this distance involves the computation of a power it is not
+done exact but with floaring point arithmetic.
+
```
Comment (albert-github) [inline Spatial_searching/doc/Spatial_searching/CGAL/Weighted_Minkowski_distance.h:15]: floaring -> floating ?

**Comment by afabri** [comment]
@MaelRL what has to be approved, that is, what is the question?

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-174

**Comment by lrineau** [comment]
ping @MaelRL (see https://github.com/CGAL/cgal/pull/7219#issuecomment-1418946533).

**Comment by MaelRL** [comment]
My point was that `to_double()` is used in all cases, but maybe the FT could implement its own `pow`.

**Comment by MaelRL** [comment]
> My point was that `to_double()` is used in all cases, but maybe the FT could implement its own `pow`.

Conclusion of an offline discussion is that this isn't worth the time.
