### PR TITLE
Fix bug with self intersecting bezier curves + with CORE::Polynomial

### LINKED ISSUE #4817: Issue with self intersecting Bezier curves
Adding Bezier curves with self intersections often crash when inserted one at a time, raising the error
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: nt_traits.degree(rem) < 0
File: /usr/local/include/CGAL/Arr_geometry_traits/Bezier_cache.h
Line: 873
```

## Source Code
Google Drive link: [bug.zip](https://drive.google.com/file/d/1xVzZx8Y0HRyh1TYZXmN5nMVhNMpZpj_o/view?usp=sharing)
Visualization of the curve:
https://www.desmos.com/calculator/byfqnjwaok

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu Linux 20.04
* Compiler: gcc 9.3.0
* Release or debug mode: Both
* CGAL version: 5.0.2
* Boost version: 1.71

### LINKED ISSUE #4918: Bug with point location operations with Bezier curves
## Issue Details

Running point location operations sometimes crash with the exception:
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: _inc_to_right != cv._inc_to_right
File: ../../../include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h
Line: 1337
```

## Source Code

This example is with a self intersecting Bezier curve that can be correctly constructed without facing the issue in  #4817. I'm not sure yet if this only happens with self intersecting curves.
Drive Link: [bug3.zip](https://drive.google.com/file/d/17dwmaTfo78WLY4tgkA1IbKcUR4rLpso0/view?usp=sharing)
Visualization: [Bezier_pointlocation_bug.png](https://drive.google.com/file/d/10Y0Ie0BioF8Zkr5YsMLXW_F5zi_1sy-5/view?usp=sharing)
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu Linux 20.04
* Compiler: gcc 9.3.0
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version: 1.71

### LINKED ISSUE #4920: Bug with matching parameters of exact self intersection points in Bezier curves
## Issue Details
Making self intersection points exact often crash with the error:
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
File: /usr/local/include/CGAL/Arr_geometry_traits/Bezier_point_2.h
Line: 1675
```
This bug is unrelated to both #4918 and #4817. I believe [this commit](https://github.com/theartful/cgal/commit/07836712659d71916b8910bdb81f8fd1a5e3afe1) to be a proper fix for it, but it depends on #4916 getting merged first, so I will wait for that.

## Source Code
In this example an arrangement is created and a "ray_shoot_down" query is performed, causing the error.
Drive Link: [bug4.zip](https://drive.google.com/file/d/14LzO-4KFzVySf-fSYlUK_lT1vXdcImd0/view?usp=sharing)
Visualization: [Bezier_selfintersection_exact_bug.png](https://drive.google.com/file/d/1JLtqeAuYP7k03Y0TvsP7XXYMUJueo-GZ/view?usp=sharing)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu Linux 20.04
* Compiler: gcc 9.3.0
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version: 1.71

### PR DESCRIPTION
**Pull request by theartful**
## Summary of Changes

For #4817 it was 2 bugs at play:
1. A bug in "pseudoRemainder" in CORE::Polynomial. Can be reproduced using this example
```C++
// This will segfault

#include <CGAL/CORE_BigInt.h>
#include <CGAL/CORE_BigRat.h>
#include <CGAL/CORE_Expr.h>
#include <CGAL/CORE/poly/Poly.h>

int main()
{
  using Polynomial = CORE::Polynomial<CORE::BigInt>;

  Polynomial poly(
      "6292610697842286811635955139693732935009542961033344667036418048-"
      "103819018355033897838248246203466232014668376703031553190065602560*x+"
      "389958343406394061055782957406169075627518035964428754926430060544*x^2-"
      "944918087329222432316982976498054054571260048471617675425124188160*x^3+"
      "1211824183851140903767601657701759440881940385941369372497424678912*x^4-"
      "699316777172893143445259888350571697548316324857460168144464117760*x^5+"
      "144953133353533471687425668682375878986597384576189365099121606656*x^6+"
      "0*x^7+0*x^8+0*x^9+0*x^10+0*x^11+0*x^12");

  // uncommenting this fixes the problem
  // poly.contract();

  auto derivative = Polynomial{poly}.differentiate();
  auto x = CORE::gcd(poly, derivative);
}
```
2. A bug in how polynomials were laid out to be passed to the resultant function in the Bezier traits.

I checked the correctness of this change using the demo by making self intersecting curves and by checking the vertices of the arrangement in #4817 against a visualization of the curve.

For #4918, the assertion was placed incorrectly
https://github.com/CGAL/cgal/blob/3f8916e0cb42466770b727511eae25730ad79b0c/Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h#L1142-L1146
This asserts that vertices originating from the same curve divide the curve into 2 x_monotone curves having different directions. This is only true for vertical tangencies. In case of self intersections, they would have the same direction.
This is "compare_to_left" function. Its twin "compare_to_right" has it right
https://github.com/CGAL/cgal/blob/3f8916e0cb42466770b727511eae25730ad79b0c/Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h#L1010-L1015

For #4920 when finding exact intersections between 2 curves, you solve the polynomials and get a number of "(t, s)" pairs. "t" is the param for the first, while "s" is for the second. You then find the one that lies in the approximated interval bound. However when the two curves are the same (self intersections) you need to try swapping "(s, t)" as well. This is because the function that finds self intersections doesn't report both of the duplicate pair: (t, s) and (s, t).

## Release Management

* Affected package(s): Arrangement_2, CORE
* Issue(s) solved (if any): fix #4817 fix #4918 fix #4920
* License and copyright ownership: The license used by CGAL.

### CODE REVIEW

File: CGAL_Core/include/CGAL/CORE/poly/Poly.tcc [hunk 1]
```diff
@@ -670,19 +670,20 @@ Polynomial<NT> Polynomial<NT>::pseudoRemainder (
...
   tmpB.contract();    // local copy of B
+  int bTrueDegree = tmpB.degree;
   C = NT(1);  // Initialized to C=1.
-  if (B.degree == -1)  {
+  if (bTrueDegree == -1)  {
     core_error("ERROR in Polynomial<NT>::pseudoRemainder :\n    -- divide by zero polynomial", __FILE__, __LINE__, false);
     return Polynomial(0);  // Unit Polynomial (arbitrary!)
   }
-  if (B.degree > degree) {
+  if (bTrueDegree > degree) {
```
Comment (theartful) [inline CGAL_Core/include/CGAL/CORE/poly/Poly.tcc:679]: This was the specific bug. Although the apparent degree of B can be larger than the degree of A (this), its true degree might not be.
I didn't change `degree` since a call to "contract" removes the trailing zero coefficients and makes degree = true degree.

**Comment by efifogel** [comment]
All changes are necessary

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-222.shtml
