### PR TITLE
Fix unknown behavior that changed in Visual 2019

### LINKED ISSUE #4796: Mesh_3 parallel - regression
##  Issue Details

I am meshing an implicit domain with Mesh_3 parallel, and facing this assertion :
```CGAL error: assertion violation!
Expression : this->is_facet_on_surface(facet)
File       : C:\Users\Jane\Documents\CGAL\cgal-dev\Mesh_3\include\CGAL/Mesh_3/Refine_facets_3.h
```

Since this crash happens with CGAL-5.0.2 but not with CGAL-5.0.1, I bisected and found that commit 
85712ba28c63b708f106517a78229665d9a3ef23 seems to be responsible for that crash. (Indeed there is no assertion with the previous commit).

## Source Code

@maxGimeno @lrineau I am sending it to you directly (it's simple).

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: vs2019
* Release or debug mode: both
* Specific flags used (if any): `CGAL_LINKED_WITH_TBB` `CGAL_CONCURRENT_MESH_3`
* CGAL version: 5.0.2
* Boost version: 1.67.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.7.0, TBB 2019 Update 3

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
The Concurrent_compact_container uses some undefined behavior to  maintain time_stamps and some other things, including a counter that is not initialized during construction. 
In Vicual Studio 2019, the behavior of the std::atomic constructor changed, breaking this counter, leading to bugs at least in Mesh_3. This PR fixes it.
## Release Management

* Affected package(s):STL_Extension
* Issue(s) solved (if any): fix #4796

### CODE REVIEW

File: STL_Extension/include/CGAL/Concurrent_compact_container.h [hunk 1]
```diff
@@ -341,17 +341,25 @@ class Concurrent_compact_container
   iterator
   emplace(const Args&... args)
   {
+    typedef CCC_internal::Erase_counter_strategy<
+      CCC_internal::has_increment_erase_counter<T>::value> EraseCounterStrategy;
     FreeList * fl = get_free_list();
     pointer ret = init_insert(fl);
+    auto erase_counter = EraseCounterStrategy::erase_counter(*ret);;
```
Comment (lrineau) [inline STL_Extension/include/CGAL/Concurrent_compact_container.h:348]: Note that we still use an undefined behavior, because:
  - here the code reads the erase counter from `*ret`, that is not yet created,
  - in `allocator_new_block`, the erase counter of uninitialized objects is assigned.

Comment (maxGimeno) [reply STL_Extension/include/CGAL/Concurrent_compact_container.h:348]: Should we try to change that now, instead of waiting until it breaks and spend another 2 days trying to understand why ?

Comment (lrineau) [reply STL_Extension/include/CGAL/Concurrent_compact_container.h:348]: As we use bit-squatting for the type `USED`/`FREE` of a cell of the container, we have to use undefined-behavior, no matter what we do. That is a property of that container: it uses undefined-behavior for efficiency. That is worth a few days of hard work from time to time.

Comment (maxGimeno) [reply STL_Extension/include/CGAL/Concurrent_compact_container.h:348]: Ok, I was right to ask then :)

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-182.shtml
