### PR TITLE
Fix issues with new containers for arrangement cells

### LINKED ISSUE #6092: Performance degradation of boolean set operation when upgrade CGAL from 5.2.3 to 5.3.
## Issue Details

Performance degradation of boolean set operation when upgrade CGAL from 5.2.3 to 5.3.
Here is a simple test:
CGAL 5.2.3
image

CGAL 5.3
image

## Source Code
```
#include <iostream>
#include <vector>

#include "CGAL/Exact_predicates_exact_constructions_kernel.h"
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_2 Point_2;

#include "CGAL/Polygon_2.h"
typedef CGAL::Polygon_2<Kernel> Polygon_2;

#include "CGAL/Polygon_set_2.h"
typedef CGAL::Polygon_set_2<Kernel> Polygon_set_2;

int main(int argc, char* argv[])
{
    auto startTime = std::chrono::high_resolution_clock::now();
    const size_t polygonSize = 2000;
    std::vector<Polygon_2> vecPolygons(polygonSize);
    for (size_t i = 0; i < polygonSize; ++i)
    {
        vecPolygons[i].push_back(Point_2(i - 0.5, i - 0.5));
        vecPolygons[i].push_back(Point_2(i + 0.5, i - 0.5));
        vecPolygons[i].push_back(Point_2(i + 0.5, i + 0.5));
        vecPolygons[i].push_back(Point_2(i - 0.5, i + 0.5));
    }
    Polygon_set_2 polygonSet;
    polygonSet.join(vecPolygons.begin(), vecPolygons.end());

    for (size_t i = 0; i < polygonSize; ++i)
    {
        polygonSet.do_intersect(vecPolygons[i]);
    }
    
    auto endTime = std::chrono::high_resolution_clock::now();
    auto diffTime = endTime - startTime;
    std::cout << "Total cost: " << diffTime.count() * 1e-9 << std::endl;
    return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11 home basic 64 bits
* Compiler: MSVC-2019-Community
* Release or debug mode: Release 
* Specific flags used (if any):
* CGAL version: CGAL5.2.3 CGAL5.3
* Boost version: boost_1_76_0
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #6092

### CODE REVIEW

File: STL_Extension/include/CGAL/Compact_container.h [hunk 1]
```diff
@@ -343,10 +343,10 @@ class Compact_container
     a.swap(b);
   }
 
-  iterator begin() { return iterator(first_item, 0, 0); }
+  iterator begin() { return empty()?iterator(last_item, 0):iterator(first_item, 0, 0); }
   iterator end()   { return iterator(last_item, 0); }
 
-  const_iterator begin() const { return const_iterator(first_item, 0, 0); }
+  const_iterator begin() const { return empty()?const_iterator(last_item, 0):const_iterator(first_item, 0, 0); }
```
Comment (lrineau) [inline STL_Extension/include/CGAL/Compact_container.h:349]: Should be applied to the `Concurrent_compact_container` as well.

**Comment by sloriot** [comment]
We basically undo changes of #5408

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-95
