### PR TITLE
Polyhedron_demo: Fix Isotropic_remeshing_plugin

### LINKED ISSUE #2033: Polyhedron_demo : Fix Isotropic_remeshing_plugin
## Issue Details

There is a bug in the isotropic remeshing plugin with protected edges that are too long. 
@janetournois  Can you please give me precisions about what is wrong and how to reproduce ?

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Add a warning box if the protected edegs are too long for the target length.
## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): fix #2033

### CODE REVIEW

**Comment by janetournois** [comment]
it works, thank you

File: Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp [hunk 1]
```diff
@@ -368,18 +369,36 @@ public Q_SLOTS:
...
+                  , target_length
+                  , *selection_item->polyhedron()
+                  , CGAL::Polygon_mesh_processing::parameters::number_of_iterations(nb_iter)
+                  .protect_constraints(protect)
+                  .edge_is_constrained_map(selection_item->constrained_edges_pmap())
+                  .relax_constraints(smooth_features)
+                  .number_of_relaxation_steps(nb_smooth)
+                  .vertex_is_constrained_map(selection_item->constrained_vertices_pmap())
+                  .face_patch_map(Patch_id_pmap<face_descriptor>()));
+          }
```
Comment (janetournois) [inline Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp]: please try to avoid to re-indent code like this. It makes a diff for nothing.
@maxGimeno can you please amend and "push force" this commit to cancel this re-indentation in the commit?
Thanks

**Comment by lrineau** [comment]
@janetournois Can you verify if you approve the changes proposed by Maxime, after you request for changes https://github.com/CGAL/cgal/pull/2056#pullrequestreview-33174085?

**Comment by janetournois** [comment]
I do! Sorry, with the push force I did not get a notification.

**Comment by lrineau** [comment]
Also merged in `releases/CGAL-4.10-branch`.
