### PR TITLE
Polyhedron_demo: Discard degenerated faces in elements computation

### LINKED ISSUE #1897: Polyhedron demo - `off_plugin` crashes on some input
## Issue Details

For some input `off` files, the `off_plugin` crashes. I attach one example. It may be that the data inside is corrupted, but the demo should not crash. It should for example send an error pop-up message.

## Environment

* Operating system : Windows, 64 bits
* Compiler: msvc 2016
* Release
* CGAL version: `master`
[x29_plane.zip](https://github.com/CGAL/cgal/files/766560/x29_plane.zip)

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

This PR fixes the display of degenerated polygon soups and avoids a crash when a face uses several times the same vertices.

## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): fix #1897

### CODE REVIEW

File: Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp [hunk 1]
```diff
@@ -264,60 +264,27 @@ Scene_polygon_soup_item_priv::triangulate_polygon(Polygons_iterator pit, int pol
...
-            }
-        }
+     FT::PointAndId pid = pid_stack.back();
+     pid_stack.pop_back();
+     bool should_pass = false;
+     BOOST_FOREACH(FT::PointAndId poai, pid_stack)
+     {
+      if (pid.point== poai.point)
+      {
+        should_pass = true;
```
Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp]: simply `return` here.
