### PR TITLE
Triangulation_2:  Fix Polyline_constraint_hierarchy_2

### LINKED ISSUE #3447: Segfault when inserting twice the same polyline constraint
Reported on cgal-discuss.
Code: https://gist.github.com/sloriot/ea321a1020a838290ed99c98c7d8b697

The issue is in CDT+, with CDT there is no issue.

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

We need two versions of the insert_constraint() function of the class `Polyline_constraint_hierarchy_2`, namely
- one for the old API where constraints were just 2d segments (it is deprecated), and where one cannot insert the same constraint twice
- and one for polylines where it is possible to insert the same polyline twice.

### Todo
- [x] Rebase on an earlier release

## Release Management

* Affected package(s): Triangulation_2
* Issue(s) solved (if any): fix #3447

### CODE REVIEW

File: Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h [hunk 1]
```diff
@@ -247,7 +247,8 @@ class Polyline_constraint_hierarchy_2
 
   // insert/remove
   void add_Steiner(T va, T vb, T vx);
-  Vertex_list* insert_constraint(T va, T vb);
+  Vertex_list* insert_constraint_old_API(T va, T vb);
+    Vertex_list* insert_constraint(T va, T vb);
```
Comment (sloriot) [inline Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h]:
```suggestion
  Vertex_list* insert_constraint(T va, T vb);
```

**Comment by afabri** [comment]
@lrineau Succesfully tested in [5.0-Ic-17](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-17.shtml)
