### PR TITLE
Polyhedron_demo: Fix the Cut_plugin

### LINKED ISSUE #1278: AABB tree plugin crashes
probably because my model has zero length edges, that is zero area faces.  We should only put non-zero faces in the AABB tree.  @sloriot  Do you agree?

### PR DESCRIPTION
**Pull request by maxGimeno**
fixes #1278 
This PR filters facets of polyhedrons to ignore the ones that are degenerated. It also makes the plugin print a warning and ignore the not pure triangle polyhedrons.

### CODE REVIEW

File: Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp [hunk 1]
```diff
@@ -1204,14 +1204,33 @@ void Polyhedron_demo_cut_plugin::createCutPlane() {
...
+          facet_trees[poly_item]->insert(Facet_primitive(fit, *poly_item->polyhedron(), pmap));
+      }
+
+
+    /*  insert(faces(*(poly_item->polyhedron())).first,
                                      faces(*(poly_item->polyhedron())).second,
                                      *poly_item->polyhedron(),
-                                     pmap );
+                                     pmap );*/
+
```
Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp]: No need to keep commented code

File: Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp [hunk 2]
```diff
@@ -1204,14 +1204,33 @@ void Polyhedron_demo_cut_plugin::createCutPlane() {
...
+      //filter facets to ignore degenerated ones
+      for(Polyhedron::Facet_iterator fit = poly_item->polyhedron()->facets_begin(), end = poly_item->polyhedron()->facets_end(); fit!=end; ++fit)
+      {
+        Polyhedron::Point a(fit->halfedge()->vertex()->point()),
+            b(fit->halfedge()->next()->vertex()->point()),
+            c(fit->halfedge()->prev()->vertex()->point());
+
+        Polyhedron::Traits::Collinear_3  collinear = poly_item->polyhedron()->traits().collinear_3_object();
+        bool test = collinear(a,b,c);
+        if(!test)
```
Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp]: note that there is a global function `CGAL::collinear()`

File: Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp [hunk 3]
```diff
@@ -1204,14 +1204,33 @@ void Polyhedron_demo_cut_plugin::createCutPlane() {
...
+    {
+      messages->warning(QString("%1 ignored (not pure triangle)").arg(poly_item->name()));
+      continue;
+    }
     if(facet_trees.find(poly_item) == facet_trees.end()) {
       facet_trees[poly_item] = new Facet_tree();
       PPMAP pmap;
-      facet_trees[poly_item]->insert(faces(*(poly_item->polyhedron())).first,
+      //filter facets to ignore degenerated ones
+      for(Polyhedron::Facet_iterator fit = poly_item->polyhedron()->facets_begin(), end = poly_item->polyhedron()->facets_end(); fit!=end; ++fit)
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp]: This line of code is far too long. According to our coding guidelines, the line width should be limited to 80 columns. There is a tolerance, but you should try to reduce the width of your lines. For this, `for` loop, it can be reduced easily:
```C++
for(Polyhedron::Facet_iterator fit = poly_item->polyhedron()->facets_begin(),
                               end = poly_item->polyhedron()->facets_end();
      fit!=end; ++fit)
```

File: Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp [hunk 4]
```diff
@@ -1204,14 +1204,33 @@ void Polyhedron_demo_cut_plugin::createCutPlane() {
     CGAL::Three::Scene_item* item = scene->item(i);
     Scene_polyhedron_item* poly_item = qobject_cast<Scene_polyhedron_item*>(item);
     if(!poly_item) continue;
-
+    if(!poly_item->polyhedron()->is_pure_triangle())
+    {
+      messages->warning(QString("%1 ignored (not pure triangle)").arg(poly_item->name()));
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp]: I am pretty sure most of CGAL users will be surprised by that wording. I think the working "not a triangulated mesh" would be better.

File: Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp (hunk 2 above)
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp]: Well, Maxime has learned so far to write CGAL generic code, and in a generic code, all access to the geometry should be through geomtraits functors.

Here the code is wrote only for a given type, a `CGAL::Polyhedron_3` with a standard CGAL kernel, and that is the reason why one can use the global function `CGAL::collinear`.

File: Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp (hunk 3 above)
Comment (afabri) [inline Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp]: Or even

BOOST_FOREACH(boost::graph_traits<Polyhedron>::face_descriptor fd, faces(*poly_item))
