### PR TITLE
Fixing warnings (mostly unused variables)

### LINKED ISSUE #9033: New warnings
- [x] `/mnt/testsuite/include/CGAL/IO/write_las_points.h:106:26: warning: ‘void LASpoint::set_scan_angle_rank(I8)’ is deprecated: use set_scan_angle() for LAS 1.4 compatibility [-Wdeprecated-declarations]`
- [x] `/mnt/testsuite/include/CGAL/Polyline_simplification_2/simplify.h:235:9: warning: variable ‘n’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/include/CGAL/KSP_3/Data_structure.h:554:17: warning: variable ‘faces’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/include/CGAL/KSP_3/Data_structure.h:367:17: warning: variable ‘numfaces’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/test/Lab_Demo/triangulate_primitive.h:148:25: warning: variable ‘x’ set but not used - [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/test/Lab_Demo/triangulate_primitive.h:148:31: warning: variable ‘y’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/test/Lab_Demo/triangulate_primitive.h:148:37: warning: variable ‘z’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/include/CGAL/IO/File_maya.h:153:9: warning: variable ‘c’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/include/CGAL/Mesh_3/Sliver_perturber.h:1288:7: warning: variable ‘num_new_vertices_to_treat’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/include/CGAL/partition_is_valid_2.h:157:8: warning: variable ‘poly_num’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/include/CGAL/Periodic_4_hyperbolic_triangulation_2/internal/Dehn_hyperbolic_octagon_translation_word.h:92:19: warning: variable ‘end’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/include/CGAL/Voronoi_diagram_2/Segment_Delaunay_graph_degeneracy_testers.h:191:15: warning: variable ‘n_inf’ set but not used [-Wunused-but-set-variable=]`
- [x] `/mnt/testsuite/include/CGAL/Surface_mesh_simplification/internal/Edge_collapse.h:593:33: warning: variable ‘non_collapsable_count’ set but not used [-Wunused-but-set-variable=]`
- [ ] `-- WARNING: MPFR found but could not compile print_MPFR_version.cpp:
C:\dev\mpfr-4.2.2-vcpkg\include\mpfr.h(52,10): error C1083: Cannot open include file: 'gmp.h': No such file or directory [C:\CGAL_ROOT\CGAL-6.1-Ic-218\cmake\platforms\MSVC-2022-Community-Release\CMakeFiles\CMakeTmp\cmTC_857ff.vcxproj]` (MSVC 2022)

### PR DESCRIPTION
**Pull request by soesau**
## Summary of Changes

Removed unused variables or added CGAL_USE in some cases.
Adapted to deprecated method in LASTools.

## Release Management

* Issue(s) solved (if any): fix #9033

### CODE REVIEW

File: Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/internal/Edge_collapse.h [hunk 1]
```diff
@@ -668,6 +668,8 @@ loop()
       CGAL_SMS_TRACE(1, edge_to_string(*opt_h) << " uncomputable cost." );
     }
   }
+
+  CGAL_assertion_code(CGAL_USE(non_collapsable_count));
```
Comment (sloriot) [inline Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/internal/Edge_collapse.h]: the variable is not used at all. It can be removed

File: Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2/Segment_Delaunay_graph_degeneracy_testers.h [hunk 2]
```diff
@@ -209,6 +209,8 @@ class Segment_Delaunay_graph_face_tester_2
       ++ec;
     } while ( ec != ec_start );
 
+    CGAL_USE(n_inf);
```
Comment (sloriot) [inline Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2/Segment_Delaunay_graph_degeneracy_testers.h]: this one is not used either and can be removed

**Comment by sloriot** [comment]
Not sure it's related to this PR but we have:
```
C:\CGAL_ROOT\CGAL-6.1-Ic-230\include\CGAL\IO\write_las_points.h(108,27): warning C4244: 'argument': conversion from 'const float' to 'I8', possible loss of data [C:\CGAL_ROOT\CGAL-6.1-Ic-230\cmake\platforms\MSVC-2022-Preview-Release\test\Point_set_3\test_deprecated_io_ps.vcxproj]
```

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.1-Ic-232

**Comment by sloriot** [comment]
@soesau  Shall I wait for the TODO to be implemented to merge the branch?

**Comment by soesau** [comment]
> @soesau Shall I wait for the TODO to be implemented to merge the branch?

Just added the last ToDo. Still needs testing.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.1-Ic-240
