### PR TITLE
Polyhedron_demo: Fix the Normal Drawing

### LINKED ISSUE #1232: drawing the normals
They should have length  min(average_spacing, the_now_fixed_length)   @maxGimeno

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR fixes #1232 .
It sets a maximum value for the normal lengths that is the average spacing of the points set.

### CODE REVIEW

File: Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp [hunk 1]
```diff
@@ -246,7 +247,18 @@ void Scene_points_with_normal_item_priv::compute_normals_and_vertices() const
...
+       typedef CGAL::Parallel_tag Concurrency_tag;
+#else
+        typedef CGAL::Sequential_tag Concurrency_tag;
+#endif
+
+        double average_spacing = CGAL::compute_average_spacing<Concurrency_tag>(
+              points.begin(), points.end(),
+              6);
+
+        float normal_length = (float)std::min(average_spacing, std::sqrt(region_of_interest.squared_radius() / 1000.));
```
Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp]: this will not compile on windows. Use:
`(float)(std::min)(average_spacing, std::sqrt(region_of_interest.squared_radius() / 1000.));`

Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp]: is there any reason to use `float` and not `double` for `normal_length`?
