### PR TITLE
SMSP: Fix cone initialization of edge sources

### LINKED ISSUE #6681: Surface Mesh Shortest Paths / Geodesics with Source Points on Mesh Border
## Issue Details
Surface_mesh_shortest_path calculates the wrong distance if an inserted source point lies on the mesh border. From the documentation it's not clear if the algortihm is supposed to work for source points that lie on the border or if it's supposed to work with triangulation that have a borders at all.

The error is happening in CGAL\Surface_mesh_shortest_path\Surface_mesh_shortest_path.h line 845. A triangle is constructed from the border / from the null_face. Would be nice to have an Assertion at this point. 
The example below shows that it seems to work for target points on edges, but not for source points.
The example constructs a surface mesh with 2 triangles and calculated a shortest distance of 2.118 between source and target if the source lies on a border, distance is calculated as 0.5 if source and target are switched.

## Source Code
```c++
#include <iostream>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh/Surface_mesh.h>
#include <CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h>
#include <CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path_traits.h>


typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Surface_mesh<K::Point_3> SM;
typedef CGAL::Surface_mesh_shortest_path_traits<K, SM> SP_Traits;
typedef CGAL::Surface_mesh_shortest_path<SP_Traits> ShortestPath;

int main()
{
    SM mesh;
    SM::vertex_index v00 = mesh.add_vertex(SM::Point(0, 0, 0));
    SM::vertex_index v01 = mesh.add_vertex(SM::Point(0, 1, 0));
    SM::vertex_index v10 = mesh.add_vertex(SM::Point(1, 0, 0));
    SM::vertex_index v11 = mesh.add_vertex(SM::Point(1, 1, 1));

    SM::face_index f0 = mesh.add_face(v00, v10, v01);
    SM::face_index f1 = mesh.add_face(v10, v11, v01);

    //traget lies on border
    {
        ShortestPath sp(mesh);
        ShortestPath::Barycentric_coordinate coordsOnBorder{ 0.5, 0.5, 0.0 };

        sp.add_source_point(v00);
        double d = sp.shortest_distance_to_source_points(f0, coordsOnBorder).first;
        std::cout << "distance 1: " << d << "\n";
    }

    //source lies on border
    {
        ShortestPath sp(mesh);
        ShortestPath::Barycentric_coordinate coordsOnBorder{ 0.5, 0.5, 0.0 };

        sp.add_source_point(f0, coordsOnBorder);
        double d = sp.shortest_distance_to_source_points(v00).first;
        std::cout << "distance 2: " << d << "\n";
    }
}
```
## Environment

 Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10, 64 bit
 Compiler: MSVC2019
 Release or debug mode: both
 CGAL version: 5.4.1

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

For sources located on edges, a cone was created targeting the opposite vertex (on either side if non-border), but nothing targeted the vertices at the extremities of the edge.

This PR fixes that by reworking cone creations for edge sources, closer to what is done for face sources.

Tests improvements along the way.

## Release Management

* Affected package(s): `Surface_mesh_shortest_path`
* Issue(s) solved (if any): fix #6681
* Feature/Small Feature (if any): -
* License and copyright ownership: no change

### CODE REVIEW

File: Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h [hunk 1]
```diff
@@ -2739,11 +2810,21 @@ class Surface_mesh_shortest_path
 
   \param vertex A vertex of the input face graph
   */
-  Point_3 point(const vertex_descriptor vertex) const
+  decltype(auto) point(const vertex_descriptor v) const
```
Comment (albert-github) [inline Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h:2813]: When changing the name of the argument, don't forget to change it in the documentation as well.
From documentation build (CGAL-5.6-Ic-22:
```
/home/cgal-testsuite/cgal_doc_build/CGAL-5.6-Ic-22/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h:2811: warning: argument 'vertex' of command @param is not found in the argument list of CGAL::Surface_mesh_shortest_path< Traits, VIM, HIM, FIM, VPM >::point(const vertex_descriptor v) const
/home/cgal-testsuite/cgal_doc_build/CGAL-5.6-Ic-22/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h:2811: warning: The following parameter of CGAL::Surface_mesh_shortest_path::point(const vertex_descriptor v) const is not documented:
  parameter 'v'`

**Review by albert-github — CHANGES_REQUESTED** [review]

File: Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h (hunk 1 above)
Comment (albert-github) [reply Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h]: resolved by [0e5c2c4](https://github.com/CGAL/cgal/pull/6739/commits/0e5c2c42b9192dd1350641bd6d1c545487ff2ab9)
