### PR TITLE
Mesh_3: fix use of initial_points_generator (fix #9159)

### LINKED ISSUE #9159: Meshing 3D image but see only one object
Hello,
I am using CGAL 6.1.0 (Mesh_3) to mesh a labeled 3D image.
My input image contains multiple labeled objects, and I expect each connected component (label > 0) to be meshed.

CGAL reports during initialization:

```
Searching for connected components...
  28 components were found.
Construct initial points...
```
So CGAL detects 28 components in the labelled image. I have already reduce the meshsize to an extremely small value (sizing_scale=0.0001).

However, in the resulting mesh output (.mesh), only one object appears. 
I have attached the input image (download [here](https://unibox.uni-rostock.de/getlink/fi8pdKv9C2hFX7ZKPF9Nk2/0720_GAG_Syn_2D_10ngml_IL-1B_J2_nucleus_clean.inr.gz)) and the dumped C3t3 (`CGAL::dump_c3t3(c3t3, "out")`) for inspection. 
My code: 

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>
#include <CGAL/Mesh_3/generate_label_weights.h>
#include <CGAL/Mesh_3/Detect_features_in_image.h>
#include <CGAL/Labeled_mesh_domain_3.h>
#include <CGAL/make_mesh_3.h>
#include <CGAL/Image_3.h>
#include <CGAL/IO/output_to_vtu.h>
#include <CGAL/Mesh_3/Construct_initial_points_labeled_image.h>
#include <CGAL/facets_in_complex_3_to_triangle_mesh.h>
#include <oneapi/tbb/global_control.h>
#include <filesystem>
#include <iostream>
#include <fstream>
#include <stdexcept>
#include <CGAL/Random.h>

using K = CGAL::Exact_predicates_inexact_constructions_kernel;
using Image_domain = CGAL::Labeled_mesh_domain_3<K>;
using Mesh_domain = CGAL::Mesh_domain_with_polyline_features_3<Image_domain>;

#ifdef CGAL_CONCURRENT_MESH_3
using Concurrency_tag = CGAL::Parallel_tag;
#else
using Concurrency_tag = CGAL::Sequential_tag;
#endif

using Tr = CGAL::Mesh_triangulation_3<Mesh_domain, CGAL::Default, Concurrency_tag>::type;
using C3t3 = CGAL::Mesh_complex_3_in_triangulation_3<Tr>;
using Mesh_criteria = CGAL::Mesh_criteria_3<Tr>;

namespace fs = std::filesystem;
using namespace CGAL::parameters;

int main(int argc, char* argv[])
{
  if (argc < 3) {
    throw std::invalid_argument("Usage: <program> <input_file.inr.gz> <output_folder> [sizing_scale] [edge_size]");
  }

  const std::string fname = argv[1];
  const std::string output_folder = argv[2];
  double sizing_scale = (argc > 3) ? std::atof(argv[3]) : 0.1;
  double edge_size = (argc > 4) ? std::atof(argv[4]) : 1000.0;

  CGAL::Image_3 image;
  if(!image.read(fname)){
    std::cerr << "Error: Cannot read file " << fname << std::endl;
    return EXIT_FAILURE;
  }

  const float sigma = (std::max)(image.vx(), (std::max)(image.vy(), image.vz()));
  CGAL::Image_3 img_weights = CGAL::Mesh_3::generate_label_weights(image, sigma);

  Mesh_domain domain = Mesh_domain::create_labeled_image_mesh_domain(
    image,
    weights = std::ref(img_weights),
    relative_error_bound = 1e-6,
    features_detector = CGAL::Mesh_3::Detect_features_in_image()
  );

  CGAL::Bbox_3 bbox = domain.bbox();
  double diag = CGAL::sqrt(
      CGAL::square(bbox.xmax() - bbox.xmin()) +
      CGAL::square(bbox.ymax() - bbox.ymin()) +
      CGAL::square(bbox.zmax() - bbox.zmin()));
  double sizing_default = diag * sizing_scale;

  Mesh_criteria criteria(
    edge_size = sizing_default,
    edge_distance = sizing_default / 10,
    facet_angle = 25,
    facet_size = sizing_default,
    facet_distance = sizing_default / 10,
    cell_radius_edge_ratio = 0,
    cell_size = 0
  );

  CGAL::Construct_initial_points_labeled_image<C3t3, Mesh_domain>
      img_pts_generator(image, domain);

  C3t3 c3t3 = CGAL::make_mesh_3<C3t3>(
    domain,
    criteria,
    initial_points_generator(img_pts_generator)
  );

  c3t3.remove_isolated_vertices();

  // Write MEDIT
  std::string output_file = output_folder + "/" + fs::path(fname).stem().string() + ".mesh";
  std::ofstream medit_file(output_file);
  CGAL::IO::write_MEDIT(medit_file, c3t3,
      all_cells(false).all_vertices(false).show_patches(false));
  medit_file.close();

  // Debug dump
  CGAL::dump_c3t3(c3t3, "out");

  return 0;
}
```
Any clarification about how Mesh_3 handles multiple connected labelled components would be very appreciated.
If I am using the wrong export parameters or mesh criteria, please let me know.

## Environment

* Operating system: Ubuntu 
* CGAL version: 6.1.0

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

The bug was in #7798. The generator was called with its parameter `n = 0` instead of its default value.

## Todo

- [x] Add test

## Release Management

* Affected package(s): Mesh_3 
* Issue(s) solved (if any): fix #9159

### CODE REVIEW

File: Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h [hunk 1]
```diff
@@ -320,9 +321,11 @@ struct Construct_initial_points_labeled_image
           c3t3.set_index(v, intersect_index);
 
           *pts++ = std::make_pair(pi, intersect_index); // dimension 2 by construction, points are on surface
+          ++nb_of_points;
         }
       }
     }
+    std::cout << "  " << nb_of_points << " initial points were constructed." << std::endl;
```
Comment (sloriot) [inline Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h]: leftover

Comment (lrineau) [reply Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h]: Actually, I added it. There was already messages, like:

```
Searching for connected components...
  28 components were found.
Construct initial points...
```

I have added a final sentence so that the display is now:

```
Searching for connected components...
  28 components were found.
Construct initial points...
  560 initial points were constructed.
```

Comment (afabri) [reply Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h]: What about wrapping it in something with `VERBOSE` ?

**Comment by afabri** [comment]
Is the problem the same for initialisation for a grey level image?

**Comment by lrineau** [comment]
> Is the problem the same for initialisation for a grey level image?

Yes, and this PR fixes it as well.

File: Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h (hunk 1 above)
Comment (lrineau) [reply Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h]: > What about wrapping it in something with `VERBOSE` ?

Right, doing it now.

**Comment by afabri** [comment]
It is not related to the bug that was reported, but can you clarify in the documentation of this [`operator()` ](https://doc.cgal.org/latest/Mesh_3/structCGAL_1_1Construct__initial__points__labeled__image.html)  what `n=20` means..  Does it generate 20 points per connected component, or for the entire image?

File: Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h [hunk 2]
```diff
@@ -99,16 +99,32 @@ struct Construct_initial_points_labeled_image
 {
   const CGAL::Image_3& image_;
   const MeshDomain& domain_;
+  const bool verbose_;
 
   /*!
   * Constructs a functor for generating initial points in labeled images.
   * @param image the labeled image that defines the mesh domain
   * @param domain the mesh domain
+  *  @param np an optional sequence of \ref bgl_namedparameters "Named Parameters" among the ones listed below:
```
Comment (afabri) [inline Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h]:
```suggestion
  * @param np an optional sequence of \ref bgl_namedparameters "Named Parameters" among the ones listed below:
```

**Comment by sloriot** [comment]
Mesh_3 fully red in CGAL-6.2-Ic-60

**Comment by lrineau** [comment]
> Mesh_3 fully red in CGAL-6.2-Ic-60

Sorry, I forgot to check other .cpp with ctest. That passes, now, after commit fffffcde4a57775cf4c976da758234c6206ae4dc.

**Comment by sloriot** [comment]
Seems to be responsible for those runtime errors:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.2-Ic-65/Mesh_3/TestReport_lrineau_Ubuntu-Latest-CXX11.gz
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.2-Ic-65/Mesh_3/TestReport_gimeno_Debian-testing-clang-main.gz
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.2-Ic-65/Mesh_3/TestReport_gimeno_ArchLinux-clang.gz

**Comment by sloriot** [comment]
@lrineau investigated and the branch is not responsible for the bug that is already here (worked around with a6b3139). It is triggered by this branch cause more init points are added.

Let's merge the branch and look at Sunday test results

**Comment by sloriot** [comment]
Tests results are looking good. There is one failing case that might not be related but I'm putting a link here in case you want to have a look:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.1.1-I-253/Mesh_3/TestReport_gimeno_Ubuntu-Latest-NO_DEPRECATED_CODE.gz

File: Cartesian_kernel/include/CGAL/constructions/kernel_ftC3.h [hunk 3]
```diff
@@ -948,7 +948,10 @@ power_distance_to_power_sphereC3(const FT &px, const FT &py, const FT &pz, const
                                         sx, sy, sz, sw,
                                         tx, ty, tz, FT(1));
 
-  return -ff0/(ff1 - ff0);
+  if(is_zero(ff0))
+    return FT(0);
+  else
+    return -ff0/(ff1 - ff0);
```
Comment (lrineau) [inline Cartesian_kernel/include/CGAL/constructions/kernel_ftC3.h:954]: Anyway, that code `power_distance_to_power_sphereC3` was added, and is only used, by `Sliver_exuder`. I have verified, and the patch is right.
