### PR TITLE
Polyhedron_demo: Fix draw two sides for Polyhedron

### LINKED ISSUE #2103: Add a "draw two side" option in the context menu of Polyhedron item
When ticked, it will fill the vector of normals and use the same shader as for polygon soups. When unticked, the vector of normals is cleared. Special care need to be taken when multicolors are ON.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
The PROGRAM_FLAT allows to save memory by not keeping the flat normals and computing them in real time in the fragment shader, but it loses the orientation of the faces. To fix it, we decided to drop this enhancement in the case the draw_two_sides option is set, and keep computing the flat normals.

## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): fix #2103 
* Feature/Small Feature (if any):

### CODE REVIEW

**Comment by maxGimeno** [comment]
Travis failing is not due to this code.

**Comment by lrineau** [comment]
> Unable to connect to ppa.launchpad.net:http:

I have restarted the failed job.

**Comment by lrineau** [comment]
... and the restarted job worked. The Travis status of this PR is now green.

File: Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp [hunk 1]
```diff
@@ -117,15 +117,15 @@ struct Scene_polyhedron_item_priv{
   }
 
 
-  void compute_normals_and_vertices(const bool colors_only = false) const;
+  void compute_normals_and_vertices(const bool colors_only = false, const bool is_two_side = false) const;
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp]: I do not really understand why the parameter here is named `is_two_side`. At the very least, there should be an 's': `is_two_sides`.

Anyway, there is already a good name: `draw_two_sides`.

File: Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp [hunk 2]
```diff
@@ -491,7 +500,14 @@ Scene_polyhedron_item_priv::initialize_buffers(CGAL::Three::Viewer_interface* vi
 {
     //vao containing the data for the facets
     {
-    program = item->getShaderProgram(Scene_polyhedron_item::PROGRAM_FLAT, viewer);
+    if(viewer->property("is_two_sides").toBool())
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp]: Same: `draw_two_sides`
