### PR TITLE
Polyhedron_demo: Restore snapshots 

### LINKED ISSUE #1208: Polyhedron demo : save snapshot broken
- open anything you like in polyhedron demo
- do File -> save snapshot
- open the image in your favorite viewer : it's all gray

@maxGimeno can you please have a look at this? we really need it to prepare slides

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR fixes #1208 .
It restores the non-vectorial snapshots of the demo the way they were in 4.6.

### CODE REVIEW

**Comment by sloriot** [comment]
There should be an option to preserve the aspect ratio.

File: Polyhedron/demo/Polyhedron/Viewer.h [hunk 1]
```diff
@@ -174,6 +175,7 @@ public Q_SLOTS:
   QString message;
   bool _displayMessage;
   QTimer messageTimer;
+  QMatrix4x4 projectionMatrix;
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Viewer.h]: I think the `Viewer` class should use a d-pointer, like the other ones in our framework, to avoid that modifications for internal reasons, like this one, have an impact on the `Viewer.h`.

Comment (sloriot) [inline Polyhedron/demo/Polyhedron/Viewer.h]: @lrineau I suggest that this is done in another PR. Shall you open an issue for that?

Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Viewer.h]: I agree. Issue #1248.

**Comment by sloriot** [comment]
Use <i>Camel Case</i> for the text in the dialog

**Comment by sloriot** [comment]
I don't know what the difference when "use white background is  checked". I don't know what the option on the frustum is useful for.

File: Polyhedron/demo/Polyhedron/Viewer.h (hunk 1 above)
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Viewer.h]: See commit https://github.com/CGAL/cgal/pull/1244/commits/5d1da468bf758415d7b6f6124c605a040683dd48. There was already a d-pointer for `Viewer`.

**Comment by maxGimeno** [comment]
@sloriot  The background option makes the snapshot's background  white  even if it is not in the scene (View->Set Background Color) and the option for the Frustum is used to avoid deforming the scene when the ratio of the snapshot is not the same as the one of the viewer.

**Comment by lrineau** [comment]
A side note: do not mix "[CamelCase][cc]", which is a naming convention for identifiers, with [rules for capitalization of words in English titles][e].

[cc]: https://en.wikipedia.org/wiki/CamelCase
[e]: https://www.google.com/search?q=capitalize+titles+in+english

**Comment by afabri** [comment]
settings -> Settings in the dialog. I've sent a mail to Maxime.

The snapshop printing works with VC++.

**Comment by janetournois** [comment]
Than you!
