### PR TITLE
Handle "right" folds

### LINKED ISSUE #1445: Random polygon generation issue
The following examples shows an infinite loop while trying to generate a random polygon

```
/*  
There must be a bug to fix in the sweepline code if this package.
The following data set hangs with the vertices in this particular order.
As the first thing the random_polygon_2 functions does
is a random_shuffle, we have put it in an #ifndef  for this testcase
 */

#define CGAL_DONT_SHUFFLE_IN_RANDOM_POLYGON_2 1

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/random_polygon_2.h>
#include <CGAL/algorithm.h>



#include <fstream>
#include <list>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::Point_2                                          Point_2;
typedef std::list<Point_2>                                  Container;
typedef CGAL::Polygon_2<K, Container>                       Polygon_2;


int main( )
{
   Polygon_2            polygon;
   std::list<Point_2>   point_set;

   std::string input = "-5 -7 46 59 55 -50 27 -93 46 -62 55 17 -71 0 -27 -41 -86 -73 7 -85 -71 93 41 -47 78 0 -13 52 -73 -25 -17 -11 56 -61 71 -69 -44 59 -9 5 -64 -96 -66 -45 39 54 -93 -22 5 -21 -32 32 -26 77 -99 -2 62 -73 -35 7 -88 60 39 56 2 3 -5 -50 3 68 82 16 -64 -38 -2 -16";


   std::stringstream input_stream(input);

   std::istream_iterator< Point_2 > in(input_stream);
   CGAL::copy_n_unique(in, 38,
                       std::back_inserter(point_set));

   std::ostream_iterator< Point_2 >  out( std::cout, "\n " );

   CGAL::random_polygon_2(point_set.size(), std::back_inserter(polygon),
                          point_set.begin());

   std::cout << "done" << std::endl;
   return 0;
}
```

### LINKED ISSUE #2585: random_polygon_2 goes into infinite loop for some point input sequences
## Issue Details

CGAL::random_polygon_2  goes into an infinite loop for some point input sequences.
It occurs both with an exact kernel (Exact_predicates_exact_constructions_kernel), and with Simple_cartesian.

The infinite loop occurs in random_polygon_2.h in the call to:
```
make_simple_polygon(vertices.begin(), vertices.end(), traits);
```

### Sample input sequences triggering the bug:

Point_2D X Y:
```
0 1
2 2
2 1
3 1
```

```
0 1 
2 0
1 1
2 1
```

```
1 3 
1 0
1 1 
1 2
```

I believe it happens because there are coplanar points in the input sequence.

random_polygon_2 throwing an exception or failing with an empty output sequence would be acceptable, or at least preferable to the infinite loop.
It's desirable to be able to generate polygons with coplanar points though..

## Source Code

Gist with minimal sample code (-std=c++11):
https://gist.github.com/bobergj/7d13865080e923b7017f4761358828ce

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): macOS Sierra 10.12.6, 64 bits
* Compiler: Apple LLVM version 9.0.0 (clang-900.0.38)
* Release or debug mode: Both
* Specific flags used (if any):
* CGAL version: 4.11 built from source. 
* Boost version: 1.59.0_3 (macports)
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

The following "right fold" configurations of collinear points: `x-2 x x-1` and `x+2 x x+1` cannot be handled with the typical left swap because the interval has range `n-1` (so, it swaps a single vertex onto itself). 

Code is changed to manually swap like it is done when the fold is on the left (which can and is immediately detected at the beginning of the insertion event).

## Release Management

* Affected package(s): `Generator`, `Polygon`
* Issue(s) solved (if any): fix #2585, fix #1445
* Feature/Small Feature (if any): NA
* License and copyright ownership: no changes

### CODE REVIEW

**Comment by MaelRL** [comment]
Does _not_ fix https://github.com/CGAL/cgal/issues/5160, which is a completely different issue where the algorithm alternates between two polygons.

File: Polygon/include/CGAL/Polygon_2/Polygon_2_simplicity.h [hunk 1]
```diff
@@ -74,6 +74,8 @@ struct Vertex_index {
     explicit Vertex_index(Index_t i): m_i(i) {}
     Index_t as_int() const {return m_i;}
     Vertex_index operator++() {++m_i; return *this; }
+    bool operator==(const Vertex_index& other) const = default;
```
Comment (lrineau) [inline Polygon/include/CGAL/Polygon_2/Polygon_2_simplicity.h:77]: `operator==` cannot be `= default`. That is only allowed since C++20. Before C++20, only special member functions (cstor, dstor, copy, assign, and move-*) can be defaulted.
https://en.cppreference.com/w/cpp/language/member_functions#Special_member_functions

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-106.shtml
