### PR TITLE
Mesh_2: fix degenerate cases

### LINKED ISSUE #781: CGAL::Assertion_exception when refining mesh
I am using the default CDT mesh refiner.  I sometimes hit an assertion when refining.

I am running tip of tree CGAL as of Feb 12 - SHA c624d3d835afe666885e32e234f9209b88f208f5

terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: n == zone.fh
File: /usr/local/include/CGAL/Mesh_2/Refine_edges.h
Line: 434
Aborted (core dumped)

I've created a gist (https://gist.github.com/petersadro/55470eccde4ce8df3684) with the backtrace, example code, and data to reproduce the issue.

Sorry for the large amount of data.  I actually pared down the free points to the minimum to still reproduce the problem.  Removing the constraints is problematic.

Thanks,
Pete

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

This PR fixes the error reported in issue #781. The main two changes are:

- in `Refine_edges.h`:  allow the refinement point of a constrained edge to be an existing close encroaching vertex,
- in `Refine_faces.h`: skip tiny bad faces when their bbox are smaller than a few ulp.

## Release Management

* Affected package(s): Triangulation_2, Mesh_2
* Issue(s) solved (if any): fix #781
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership: maintenance by GeometryFactory, now copyright change

### CODE REVIEW

File: Mesh_2/include/CGAL/Mesh_2/Clusters.h [hunk 1]
```diff
@@ -17,11 +17,16 @@
 #include <CGAL/license/Mesh_2.h>
 
 
+#include <CGAL/boost/iterator/transform_iterator.hpp>
 #include <CGAL/Filter_circulator.h>
+#include <CGAL/tags.h>
 #include <CGAL/Unique_hash_map.h>
 
+#include <boost/iterator/transform_iterator.hpp>
```
Comment (sloriot) [inline Mesh_2/include/CGAL/Mesh_2/Clusters.h:25]: not included by the CGAL version?

File: Mesh_2/include/CGAL/Mesh_2/Refine_edges.h [hunk 2]
```diff
@@ -16,16 +16,27 @@
...
+#include <CGAL/number_utils.h>
 #include <CGAL/tags.h>
-#include <CGAL/assertions.h>
 
-#include <utility>
-#include <iterator>
 #include <boost/iterator/filter_iterator.hpp>
-#include <CGAL/boost/iterator/transform_iterator.hpp>
+
+#include <boost/iterator/transform_iterator.hpp>
```
Comment (sloriot) [inline Mesh_2/include/CGAL/Mesh_2/Refine_edges.h:32]: same question here

File: Mesh_2/include/CGAL/Mesh_2/Refine_faces.h [hunk 3]
```diff
@@ -15,13 +15,27 @@
...
-#include <CGAL/Meshes/Triangulation_mesher_level_traits_2.h>
-#include <CGAL/Mesh_2/Face_badness.h>
-#include <CGAL/Double_map.h>
+#include <CGAL/boost/graph/graph_traits_Constrained_Delaunay_triangulation_2.h>
+#include <CGAL/boost/graph/IO/OFF.h>
 #include <CGAL/boost/iterator/transform_iterator.hpp>
+#include <CGAL/Double_map.h>
+#include <CGAL/enum.h>
+#include <CGAL/functional.h>
+#include <CGAL/IO/io.h>
```
Comment (sloriot) [inline Mesh_2/include/CGAL/Mesh_2/Refine_faces.h]: hide IO behind CGAL_MESH_2_DEBUG_INSERTIONS?

File: Mesh_2/package_info/Mesh_2/dependencies [hunk 4]
```diff
@@ -1,15 +1,25 @@
 Algebraic_foundations
+BGL
+Cartesian_kernel
 Circulator
 Distance_2
+Distance_3
```
Comment (sloriot) [inline Mesh_2/package_info/Mesh_2/dependencies]: strange you are bringing 3D packages

File: Mesher_level/include/CGAL/Mesher_level.h [hunk 5]
```diff
@@ -327,6 +347,8 @@ class Mesher_level
     case CONFLICT_AND_ELEMENT_SHOULD_BE_DROPPED:
       std::cerr << "rejected (permanent)\n";
       break;
+    default:
+      std::cerr << "rejected (other reason)\n";
```
Comment (sloriot) [inline Mesher_level/include/CGAL/Mesher_level.h:334]: won't this pollute the terminal of users?

File: Mesh_2/include/CGAL/Mesh_2/Clusters.h (hunk 1 above)
Comment (lrineau) [reply Mesh_2/include/CGAL/Mesh_2/Clusters.h:25]: I just wanted to calm down the warnings from clangd.

File: Mesh_2/package_info/Mesh_2/dependencies (hunk 4 above)
Comment (lrineau) [reply Mesh_2/package_info/Mesh_2/dependencies]: That comes from `Kernel_23/include/CGAL/Kernel/function_objects.h`.

File: Mesher_level/include/CGAL/Mesher_level.h (hunk 5 above)
Comment (lrineau) [reply Mesher_level/include/CGAL/Mesher_level.h:334]: That is protected by `#ifdef CGAL_MESHES_DEBUG_REFINEMENT_POINTS`. If that macro is defined, the
user wants to have verbose outputs.

File: Mesh_2/package_info/Mesh_2/dependencies (hunk 4 above)
Comment (sloriot) [reply Mesh_2/package_info/Mesh_2/dependencies]: Still find it fishy, you shall not include kernel functors since all is coming from the geom traits. Might be the IO functions.

**Comment by lrineau** [comment]
Even if this PR is a bug-fix, I would prefer it to be in CGAL-6.2 only, because there is a breaking change on the requirements of the traits class: https://github.com/CGAL/cgal/pull/9290/changes/a48e7ee74d4934f8ea66ab537032f8576b535ecb#diff-13fc09a664b393d1a17f16b50657be2bc99df52a992c50a2880ad88525d823bc

File: Mesh_2/include/CGAL/Mesh_2/Clusters.h [hunk 6]
```diff
@@ -84,7 +89,7 @@ class Clusters
      */
     std::pair<Vertex_handle, Vertex_handle> smallest_angle;
 
-    FT rmin; // @fixme: rmin has no meaning if reduced=false!!!
+    FT next_sq_insertion_radius; // @fixme: next_sq_insertion_radius has no meaning if reduced=false!!!
```
Comment (afabri) [inline Mesh_2/include/CGAL/Mesh_2/Clusters.h]: Would it make sense to deal with this old todo   in this bug fix PR ?

File: Mesh_2/include/CGAL/Mesh_2/Refine_edges.h [hunk 7]
```diff
@@ -352,27 +363,13 @@ class Refine_edges_base :
...
-
-  void after_insertion_split_constraint(Vertex_handle v1, Vertex_handle v2,
-                                        Vertex_handle va,
-                                        Tag_true)
-  {
-    tr.split_constraint(v1, v2, va);
-  }
-
-public:
+  public:
```
Comment (afabri) [inline Mesh_2/include/CGAL/Mesh_2/Refine_edges.h:387]: on purpose, or only for debugging ?

Comment (lrineau) [reply Mesh_2/include/CGAL/Mesh_2/Refine_edges.h:387]: That is just a reformating from `clang-format`. The `public:` was just shifted 2 spaces right.

File: STL_Extension/include/CGAL/Compact_container.h [hunk 8]
```diff
@@ -1235,7 +1235,7 @@ class Output_rep<CGAL::internal::CC_iterator<DSC, Const> > {
 };
 
 struct With_offset_tag {
-  int offset = 0;
+  int offset = -1;
```
Comment (afabri) [inline STL_Extension/include/CGAL/Compact_container.h]: For bisect or really for this PR ? Motivation?

File: Mesh_2/package_info/Mesh_2/dependencies (hunk 4 above)
Comment (lrineau) [reply Mesh_2/package_info/Mesh_2/dependencies]: It was indeed included by `CGAL/IO/OFF.h` (for `Cartesian_converter`).

Once the includes of IO headers are guarded by `#if defined(CGAL_MESH_2_DEBUG...`, those dependencies are gone.

File: STL_Extension/include/CGAL/Compact_container.h (hunk 8 above)
Comment (lrineau) [reply STL_Extension/include/CGAL/Compact_container.h]: > For bisect or really for this PR ? Motivation?

The only reason we might want to use that tag is to offset timestamps by -1, to take the infinite vertex into account. That default value is better.

Comment (afabri) [reply STL_Extension/include/CGAL/Compact_container.h]: Maybe add a comment in the code why it is -1
With a later blame we will have a hard time to understand why it was changed during a Mesh_2 fix.

**Comment by afabri** [comment]
Bug reported in the CI, also in the testsuite.   
And additionally:  `test/Mesh_2/issue_781.cpp:55:10: fatal error: 'CGAL/Base_with_time_stamp.h' file not found`
and `include/CGAL/Mesher_level.h:301:33: error: no member named 'geometry' in 'CGAL::Reconstruction_triangulation_3<CGAL::Robust_circumcenter_filtered_traits_3<CGAL::Epick>>'
    auto geom = triangulation().geometry(e);`

File: Mesh_2/include/CGAL/Mesh_2/Refine_edges.h [hunk 9]
```diff
@@ -492,26 +597,74 @@ class Refine_edges_base :
...
+
+#ifdef CGAL_MESH_2_DEBUG_REFINEMENT_POINTS
+    std::cerr << "refinement_point_impl(Edge: " << IO::oformat(va, With_point_tag{}) << ", "
+              << IO::oformat(vb, With_point_tag{}) << ") = ";
     std::cerr << p << '\n';
+#endif // CGAL_MESH_2_DEBUG_REFINEMENT_POINTS
+    if constexpr(std::is_floating_point_v<FT>) {
+      Is_locally_conforming_Gabriel<Tr> is_locally_conforming_Gabriel{};
+      constexpr FT max_FT = (std::numeric_limits<FT>::max)();
+      auto ulp = [&max_FT](const FT& x) { return std::nextafter(x, max_FT) - x; };
```
Comment (sloriot) [inline Mesh_2/include/CGAL/Mesh_2/Refine_edges.h]:
```suggestion
      auto ulp = [](const FT& x) { return std::nextafter(x, max_FT) - x; };
```

Comment (sloriot) [reply Mesh_2/include/CGAL/Mesh_2/Refine_edges.h]: warning [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.2-Ic-101/Barycentric_coordinates_2/TestReport_magritte_arm64-apple_bigsur_clang1200-release-64bits.gz)

Comment (afabri) [reply Mesh_2/include/CGAL/Mesh_2/Refine_edges.h]: Added, because Visual C++ issues this error without this.
```
error C3493: 'max_FT' cannot be implicitly captured because no default capture mode has been specified  
````

Comment (lrineau) [reply Mesh_2/include/CGAL/Mesh_2/Refine_edges.h]: I will commit the `[&]` capture. That will probably satisfy both compilers.

File: Installation/CHANGES.md [hunk 10]
```diff
@@ -10,6 +10,11 @@ Release date: July 2026
 - Made the `Arr_linear_traits_2` a model of the new concept.
 - Added overloads of `draw(Arrangement_on_surface_2& arr, Bbox& bbox, ...)` that enable the drawing of arrangements induced by unbounded curves.
 
+### [2D Conforming Triangulations and Meshes](https://doc.cgal.org/6.2/Manual/packages.html#PkgMesh2)
+
+- The implementation is more robust to degenerate inputs, such as polygons with microscopic edges, or nearly colinear points.
```
Comment (afabri) [inline Installation/CHANGES.md]:
```suggestion
- The implementation is more robust to degenerate inputs, such as polygons with microscopic edges, or nearly collinear points.
```

File: Mesh_2/include/CGAL/Mesh_2/Do_not_refine_edges.h [hunk 11]
```diff
@@ -48,9 +48,9 @@ class Do_not_refine_edges :
 
   typedef typename Triangulation_mesher_level_traits_2<Tr>::Zone Zone;
 
+public:
```
Comment (afabri) [inline Mesh_2/include/CGAL/Mesh_2/Do_not_refine_edges.h:51]: on purpose or for debugging?

**Review by lrineau — COMMENTED** [review]
I have been working on this PR for three weeks, now, at least part-time.

We have other priorities, and decided to postpone the work on this PR for now. I just commit two new minimized versions of `10070.obj` (from triwild), that trigger assertions in Mesh_2. They can be reproduced by:

```shell
/path/to/build/test/Mesh_2/test_mesh_obj Mesh_2/test/Mesh_2/triwild-10070-min3.obj 
/path/to/build/test/Mesh_2/test_mesh_obj Mesh_2/test/Mesh_2/triwild-10070-min4.obj 
```

File: Mesh_2/include/CGAL/Mesh_2/Do_not_refine_edges.h (hunk 11 above)
Comment (lrineau) [reply Mesh_2/include/CGAL/Mesh_2/Do_not_refine_edges.h:51]: On purpose: `using Super::triangulation_ref_impl;` must be visible by classes derived from this one.

**Comment by afabri** [comment]
I  commented the insertion of putting constraints on the convex hull edges and was running it on ~60 data sets @MaelRL  gave me:
```
10942.obj   159865.obj  168697.obj  175333.obj  184912.obj  190022.obj  192392.obj  202724.obj  212286.obj  216727.obj  219125.obj  222387.obj  246717.obj  261034.obj  289713.obj  38839.obj  87109.obj
118915.obj  16114.obj   170101.obj  177208.obj  18581.obj   190448.obj  194871.obj  206321.obj  214343.obj  217503.obj  219591.obj  226714.obj  247285.obj  262318.obj  293061.obj  39109.obj  92779.obj
122605.obj  163651.obj  171425.obj  177972.obj  188680.obj  190472.obj  201659.obj  209621.obj  215200.obj  217613.obj  21970.obj   234409.obj  249724.obj  26539.obj   293104.obj  46477.obj  93025.obj
122959.obj  163771.obj  171488.obj  178034.obj  188684.obj  191077.obj  201957.obj
```
where  1/3  show a problem:
```
175333.obj  assertion
212286.obj    Ctrl-C  4GB
219125.obj    Ctrl-C  4GB
246717.obj  assertion
289713.obj  assertion
170101.obj  assertion
217503.obj  assertion
293061.obj  assertion
39109.obj  assertion
163651.obj assertion
209621.obj  Ctrl C 10 GB
234409.obj  assertion
293104.obj assertion
46477.obj assertion  immediately
93025.obj assertion
178034.obj assertion
188684.obj assertion
201957.obj Ctrl C 10 GB
```

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.2-Ic-108
