### PR TITLE
Kernel_23: Fix some doc issue with weighted points

### LINKED ISSUE #3167: operator+= not implemented for Weighted_Point_3
## Issue Details
If I understand [the documentation](https://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Weighted__point__3.html#aff371a7ec70357bca92293889184c290) correctly, than the class Weighted_point_3 should have the operator += implemented, however, that doesn't seem to be the case. Am I doing something wrong?

> weighted_point.cpp:13:5: error: no match for ‘operator+=’ (operand types are ‘CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>::Weighted_point_3 {aka CGAL::Weighted_point_3<CGAL::Epick>}’ and ‘CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick>::Vector_3 {aka CGAL::Vector_3<CGAL::Epick>}’)
  wp += v;

## Source Code

``` c++

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;

int main()
{
	K::Point_3 p(0,0,0);
	K::FT w(1);
	K::Weighted_point_3 wp(p,w);
	K::Vector_3 v(1,1,1);
	
	p += v;
	wp += v;
}
```

## Environment

* Operating system: Ubuntu 18.04
* Compiler: g++
* CGAL version: 4.12

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

The documentation says we can translate weighted points using `operator+(Vector_3)`. In practice, we can't. I'm not too sure about adding overloads for weighted points of predicates/constructions meant to act on (bare) points (see [this comment](https://github.com/CGAL/cgal/issues/3167#issuecomment-396617477)), so the doc is changed instead.

## Release Management

* Affected package(s): `Kernel_23`
* Issue(s) solved (if any): fix #3167
* Feature/Small Feature (if any):

### CODE REVIEW

File: Kernel_23/include/CGAL/Weighted_point_3.h [hunk 1]
```diff
@@ -91,62 +91,62 @@ class Weighted_point_3 : public R_::Kernel_base::Weighted_point_3
...
-  typename cpp11::result_of<typename R::Compute_weight_3( Weighted_point_3)>::type
+  typename cpp11::result_of<typename R::Compute_weight_3(Weighted_point_3)>::type
   weight() const
   {
     return typename R::Compute_weight_3()(*this);
   }
 
 
-  typename cpp11::result_of<typename R::Compute_x_3( Weighted_point_3)>::type
+  typename cpp11::result_of<typename R::Compute_x_3(Point_3)>::type
```
Comment (lrineau) [inline Kernel_23/include/CGAL/Weighted_point_3.h]: Andreas, after this change, then maybe the `std::result_of` can be used instead of TR1.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.13-Ic-42][*], and then merged.

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.13-Ic-42.shtml
