### PR TITLE
Early exit if the mesh is empty

### LINKED ISSUE #7263: `PMP::orient_to_bound_a_volume(emptyMesh)` crashes the session
Hello,

When a mesh is empty, `CGAL::is_closed(themesh)` and `CGAL::is_triangle_mesh(themesh)` both return `true`, but `PMP::orient_to_bound_a_volume(themesh)` crashes the session.

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #7263

### CODE REVIEW

File: Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h [hunk 1]
```diff
@@ -1364,6 +1364,9 @@ void orient_to_bound_a_volume(TriangleMesh& tm,
   typedef typename GetGeomTraits<TriangleMesh, NamedParameters>::type              GT;
   typedef typename GetInitializedFaceIndexMap<TriangleMesh, NamedParameters>::type FaceIndexMap;
 
+  std::size_t nbf = num_faces(tm);
+  if (nbf == 0) return;
```
Comment (MaelRL) [inline Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h:1368]: [`is_empty(g)`](https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/helpers.h#L994)?

Comment (afabri) [reply Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h:1368]: `num_faces()` may even be larger than zero if there is garbage.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-184
