### PR TITLE
Fix non-documented IO functions

### LINKED ISSUE #3189: write_off on non-garbage collected Surface_mesh objects
`write_off()` is using `num_vertices()` and `num_faces()` which leads to errors if the surface mesh contains garbage.

### PR DESCRIPTION
**Pull request by sloriot**
## Summary of Changes

Call documented functions in convenience functions.

## Release Management

* Affected package(s):
* Issue(s) solved (if any): fix #3189

### CODE REVIEW

File: Surface_mesh/include/CGAL/Surface_mesh/IO.h [hunk 1]
```diff
@@ -267,51 +267,12 @@ bool read_off_ascii(Surface_mesh<Point_3>& mesh,
...
-    }
-
-    // read as ASCII or binary
-    bool ok = (is_binary ?
-               internal::read_off_binary(mesh, in, has_normals, has_texcoords) :
-               internal::read_off_ascii(mesh, in, has_normals, has_texcoords));
+  std::ifstream in(filename.c_str());
+  if (in.fail())
+    return false;
+  in >> mesh;
```
Comment (lrineau) [inline Surface_mesh/include/CGAL/Surface_mesh/IO.h]: The new code certainly cannot read binary file (because of the `ifstream` open mode. That seems to be a regression.

Comment (sloriot) [reply Surface_mesh/include/CGAL/Surface_mesh/IO.h]: Indeed. What should be done here? The real bug was only in the write function but I though that maybe we could get rid of duplicated code. I can simply undo the change for the read function.

Comment (lrineau) [reply Surface_mesh/include/CGAL/Surface_mesh/IO.h]: I think you should indeed undo the change for the read function, otherwise the demo will no longer read the colors of colored OFF.

Comment (sloriot) [reply Surface_mesh/include/CGAL/Surface_mesh/IO.h]: Amended

**Comment by sloriot** [comment]
Successfully tested in CGAL-4.13-Ic-57
