### PR TITLE
Stream support: Fix for Epeck

### LINKED ISSUE #9071: write_polygon_soup() fails to compile with EPEC Kernel
## Issue Details

The title says it all.

## Source Code

```
#include <array>
#include <vector>

#if 1
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;
#else
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
using Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
#endif
#include <CGAL/IO/polygon_soup_io.h>
int main() {
  std::vector<Kernel::Point_3> points;
  std::vector<std::array<std::size_t, 3>> polygons;
  CGAL::IO::write_polygon_soup("xxx.off", points, polygons, CGAL::parameters::stream_precision(17));
  return 0;
}

```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: latest
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

For file formats that expect floating point coordinates we convert on the fly so that  `CGAL::io::write_polygon_soup()`    also works for  polygon soups with ` FT` which are non-float/double, e.g.  `Exact_predicates_exact_constructions_kernel`.
Additionally, we document the named parameter `point_map` as it was missing.

## Release Management

* Affected package(s): Stream_support
* Issue(s) solved (if any): fix #9071
* License and copyright ownership: unchanged 
* upon integration update and test #9109

### CODE REVIEW

File: Kernel_23/include/CGAL/Kernel/function_objects.h [hunk 1]
```diff
@@ -2650,7 +2650,7 @@ namespace CommonKernelFunctors {
     {
       CGAL_kernel_precondition(! K().collinear_3_object()(p,q,r) );
       Vector_3 res = CGAL::cross_product(q-p, r-p);
-      res = res / CGAL::sqrt(res.squared_length());
+      res = res / CGAL::approximate_sqrt(res.squared_length());
```
Comment (afabri) [inline Kernel_23/include/CGAL/Kernel/function_objects.h]: @MaelRL is that ok ?

**Comment by MaelRL** [comment]
This is related to https://github.com/CGAL/cgal/pull/7874.

There we said: 
> After a discussion with @MaelRL we decided that the user is in charge to pass a vertex_point_map as named parameter that does the conversion. This is straightforward as we offer the [Cartesian_converter_property_map](https://doc.cgal.org/latest/Property_map/structCGAL_1_1Cartesian__converter__property__map.html).

Here that would mean adding the point map parameter to the named parameters of `write_polygon_soup()` rather than `CGAL::to_double()` + `approximate_sqrt` calls.

File: Kernel_23/include/CGAL/Kernel/function_objects.h (hunk 1 above)
Comment (MaelRL) [reply Kernel_23/include/CGAL/Kernel/function_objects.h]: I don't like these `approximate_sqrt`s in the kernel functors because they "fail" silently in the sense that if you are not very used to this, you will not notice a kernel called "[...] exact constructions" is doing inexact constructions.

**Comment by afabri** [comment]
And with vertex you mean the index in the range of points.

File: Kernel_23/include/CGAL/Kernel/function_objects.h (hunk 1 above)
Comment (afabri) [reply Kernel_23/include/CGAL/Kernel/function_objects.h]: It's for computing the face normal for the STL output.   Do you suggest to construct it with the point type   `VertexPointMap::value_type`?

**Comment by MaelRL** [comment]
Yes, here it's the point range's point map (like in Point_set_3 / Point_set_processing_3, etc.) whereas for the other PR, it's a vertex point map

File: Kernel_23/include/CGAL/Kernel/function_objects.h (hunk 1 above)
Comment (MaelRL) [reply Kernel_23/include/CGAL/Kernel/function_objects.h]: If you pass a point map, the functor will work as it is because CGAL::sqrt will be defined for the point map's value type.

File: Stream_support/include/CGAL/IO/GOCAD.h [hunk 2]
```diff
@@ -331,6 +331,12 @@ bool write_GOCAD(std::ostream& os,
  * \param np optional sequence of \ref bgl_namedparameters "Named Parameters" among the ones listed below
  *
  * \cgalNamedParamsBegin
+ *   \cgalParamNBegin{point_map}
+ *     \cgalParamDescription{a property map associating points with %Cartesian coordinates to the elements of the point set `points`}
+ *     \cgalParamType{a model of `ReadablePropertyMap` whose key type is the value type
+ *                    of the iterator of `PointRange` and value type is a point type with %Cartesian coordinates}
```
Comment (MaelRL) [inline Stream_support/include/CGAL/IO/GOCAD.h]: This doesn't really fit the actual requirements.

The proper requirement if the code were clean would be that the geom traits provides Compute_x_3, Compute_y_3, Compute_z_3, etc.

But even currently, the requirement is that there exists .x(), .y() and .z() on the point, not that it's a Cartesian kernel or not.

Note also that Gocad does not have the Cartesian_converter like (some) other I/O functions.

File: Stream_support/include/CGAL/IO/STL.h [hunk 3]
```diff
@@ -328,7 +329,7 @@ bool write_STL(std::ostream& os,
       Point_3 qq = conv(q);
       Point_3 rr = conv(r);
 
-      const Vector_3 nn = collinear(pp,qq,rr) ? Vector_3(1,0,0) : unit_normal(pp,qq,rr);
+      const Vector_3 nn = collinear(pp,qq,rr) ? Vector_3(static_cast<FT>(1.0),static_cast<FT>(0),static_cast<FT>(0)) : unit_normal(pp,qq,rr);
```
Comment (lrineau) [inline Stream_support/include/CGAL/IO/STL.h]: That is strange to pass `1.0` (a double) for the first coordinate, but `0` (an int) for the two others.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.2-Ic-20

File: Stream_support/include/CGAL/IO/STL.h [hunk 4]
```diff
@@ -317,12 +325,16 @@ bool write_STL(std::ostream& os,
...
-      const Vector_3 n = collinear(p,q,r) ? Vector_3(1,0,0) : unit_normal(p,q,r);
+      Point_3 pp = conv(p);
+      Point_3 qq = conv(q);
+      Point_3 rr = conv(r);
 
-      const float coords[12] = { static_cast<float>(n.x()), static_cast<float>(n.y()), static_cast<float>(n.z()),
-                                 static_cast<float>(p.x()), static_cast<float>(p.y()), static_cast<float>(p.z()),
-                                 static_cast<float>(q.x()), static_cast<float>(q.y()), static_cast<float>(q.z()),
-                                 static_cast<float>(r.x()), static_cast<float>(r.y()), static_cast<float>(r.z()) };
+      const Vector_3 nn = collinear(pp,qq,rr) ? Vector_3(static_cast<FT>(1.0),static_cast<FT>(0),static_cast<FT>(0)) : unit_normal(pp,qq,rr);
```
Comment (afabri) [inline Stream_support/include/CGAL/IO/STL.h]:
```suggestion
      const Vector_3 nn = collinear(pp,qq,rr) ? Vector_3(static_cast<FT>(1),static_cast<FT>(0),static_cast<FT>(0)) : unit_normal(pp,qq,rr);
```

File: Stream_support/include/CGAL/IO/STL.h (hunk 3 above)
Comment (afabri) [reply Stream_support/include/CGAL/IO/STL.h]: changed 1.0 to 1

File: Stream_support/include/CGAL/IO/GOCAD.h [hunk 5]
```diff
@@ -331,8 +336,14 @@ bool write_GOCAD(std::ostream& os,
  * \param np optional sequence of \ref bgl_namedparameters "Named Parameters" among the ones listed below
  *
  * \cgalNamedParamsBegin
+ *   \cgalParamNBegin{point_map}
+ *     \cgalParamDescription{a property map associating points to the elements of the range `points`}
+ *     \cgalParamType{a model of `ReadablePropertyMap` whose key type is the value type
+ *                    of the iterator of `PointRange` and value type is a model of the concept`Point_3`}
```
Comment (MaelRL) [inline Stream_support/include/CGAL/IO/GOCAD.h]: This will link to CGAL::Point_3, not Kernel::Point_3

File: Stream_support/include/CGAL/IO/Generic_writer.h [hunk 6]
```diff
@@ -51,11 +53,14 @@ class Generic_writer
...
 
+    typedef typename Kernel_traits<typename boost::property_traits<PointMap>::value_type>::type K;
+    typedef Simple_cartesian<double> SC;
+    Cartesian_converter<K,SC> conv;
     m_writer.write_header(m_os, points.size(), 0, polygons.size());
     for(std::size_t i=0, end=points.size(); i<end; ++i)
     {
-      const typename boost::property_traits<PointMap>::value_type& p = get(point_map, points[i]);
-      m_writer.write_vertex(to_double(p.x()), to_double(p.y()), to_double(p.z()));
+      typename SC::Point_3 p = conv(get(point_map, points[i]));
```
Comment (MaelRL) [inline Stream_support/include/CGAL/IO/Generic_writer.h]:
```suggestion
      decltype(auto) p = conv(get(point_map, points[i]));
```

File: Stream_support/include/CGAL/IO/STL.h [hunk 7]
```diff
@@ -305,6 +307,12 @@ bool write_STL(std::ostream& os,
 
   set_stream_precision_from_NP(os, np);
 
+  typedef Simple_cartesian<float> SC;
+  typedef SC::FT FT;
```
Comment (MaelRL) [inline Stream_support/include/CGAL/IO/STL.h]: Remove this and write Vector_3(1.f, 0.f, 0.f) directly?

File: Stream_support/include/CGAL/IO/STL.h [hunk 8]
```diff
@@ -317,12 +325,16 @@ bool write_STL(std::ostream& os,
...
-      const Vector_3 n = collinear(p,q,r) ? Vector_3(1,0,0) : unit_normal(p,q,r);
+      Point_3 pp = conv(p);
+      Point_3 qq = conv(q);
+      Point_3 rr = conv(r);
 
-      const float coords[12] = { static_cast<float>(n.x()), static_cast<float>(n.y()), static_cast<float>(n.z()),
-                                 static_cast<float>(p.x()), static_cast<float>(p.y()), static_cast<float>(p.z()),
-                                 static_cast<float>(q.x()), static_cast<float>(q.y()), static_cast<float>(q.z()),
-                                 static_cast<float>(r.x()), static_cast<float>(r.y()), static_cast<float>(r.z()) };
+      const Vector_3 nn = collinear(pp,qq,rr) ? Vector_3(static_cast<FT>(1),static_cast<FT>(0),static_cast<FT>(0)) : unit_normal(pp,qq,rr);
```
Comment (MaelRL) [inline Stream_support/include/CGAL/IO/STL.h]: In fact, it should probably be:
```cpp
const Vector_3 n = internal::construct_normal_of_STL_face(p, q, r, k);
```
like everywhere else, and we would not even have started this PR :)

Also looking at that function, the logic is not super sound: we do the collinear check and then deduce that if it's not collinear, then the approximate sqrt won't be zero. It should rather compute the squared length regardless of the predicate (who will now be non-exact with SC<float> anyway), and if that value is zero, then return (1,0,0).

File: Stream_support/include/CGAL/IO/STL.h [hunk 9]
```diff
@@ -317,12 +325,16 @@ bool write_STL(std::ostream& os,
       const Point& q = get(point_map, points[face[1]]);
       const Point& r = get(point_map, points[face[2]]);
 
-      const Vector_3 n = collinear(p,q,r) ? Vector_3(1,0,0) : unit_normal(p,q,r);
+      Point_3 pp = conv(p);
+      Point_3 qq = conv(q);
+      Point_3 rr = conv(r);
```
Comment (MaelRL) [inline Stream_support/include/CGAL/IO/STL.h]:
```suggestion
      decltype(auto) pp = conv(p);
      decltype(auto) qq = conv(q);
      decltype(auto) rr = conv(r);
```

File: Stream_support/include/CGAL/IO/GOCAD.h (hunk 5 above)
Comment (afabri) [inline Stream_support/include/CGAL/IO/GOCAD.h]:
```suggestion
 *                    of the iterator of `PointRange` and value type is a model of the concept `Kernel::Point_3`}
```

File: Stream_support/include/CGAL/IO/OBJ.h [hunk 10]
```diff
@@ -358,6 +364,12 @@ bool write_OBJ(std::ostream& os,
  * \param np optional sequence of \ref bgl_namedparameters "Named Parameters" among the ones listed below
  *
  * \cgalNamedParamsBegin
+ *   \cgalParamNBegin{point_map}
+ *     \cgalParamDescription{a property map associating points to the elements of the range `points`}
+ *     \cgalParamType{a model of `ReadablePropertyMap` whose key type is the value type
+ *                    of the iterator of `PointRange` and value type is a model of the concept `Point_3`}
```
Comment (afabri) [inline Stream_support/include/CGAL/IO/OBJ.h]:
```suggestion
 *                    of the iterator of `PointRange` and value type is a model of the concept `Kernel::Point_3`}
```

File: Stream_support/include/CGAL/IO/OFF.h [hunk 11]
```diff
@@ -308,6 +314,12 @@ bool write_OFF(std::ostream& os,
  * \param np optional sequence of \ref bgl_namedparameters "Named Parameters" among the ones listed below
  *
  * \cgalNamedParamsBegin
+ *   \cgalParamNBegin{point_map}
+ *     \cgalParamDescription{a property map associating points to the elements of the range `points`}
+ *     \cgalParamType{a model of `ReadablePropertyMap` whose key type is the value type
+ *                    of the iterator of `PointRange` and value type is a model of the concept `Point_3`}
```
Comment (afabri) [inline Stream_support/include/CGAL/IO/OFF.h]:
```suggestion
 *                    of the iterator of `PointRange` and value type is a model of the concept `Kernel::Point_3`}
```

**Review by afabri — COMMENTED** [review]
changes

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.2-Ic-43
