### PR TITLE
Remove remaining native GL code 

### LINKED ISSUE #2879: CGAL-4.12-beta1 does not build on Fedora armv7hl
The [build task for armv7hl](https://koji.fedoraproject.org/koji/taskinfo?taskID=25348734) failed with this log:

https://kojipkgs.fedoraproject.org//work/tasks/8734/25348734/build.log

```
[ 58%] Building CXX object src/CGAL_Qt5/CMakeFiles/CGAL_Qt5.dir/__/__/include/CGAL/Qt/moc_GraphicsViewNavigation.cpp.o
cd /builddir/build/BUILD/CGAL-4.12-beta1/build/src/CGAL_Qt5 && /usr/bin/c++  -DCGAL_Qt5_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -I/builddir/build/BUILD/CGAL-4.12-beta1/build/include -I/builddir/build/BUILD/CGAL-4.12-beta1/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib/qt5/./mkspecs/linux-g++ -isystem /usr/include/qt5/QtSvg  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -fPIC   -frounding-math -fPIC -std=gnu++11 -o CMakeFiles/CGAL_Qt5.dir/__/__/include/CGAL/Qt/moc_GraphicsViewNavigation.cpp.o -c /builddir/build/BUILD/CGAL-4.12-beta1/build/src/CGAL_Qt5/__/__/include/CGAL/Qt/moc_GraphicsViewNavigation.cpp
In file included from /builddir/build/BUILD/CGAL-4.12-beta1/include/CGAL/Qt/debug_impl.h:35,
                 from /builddir/build/BUILD/CGAL-4.12-beta1/src/CGAL_Qt5/debug.cpp:26,
                 from /builddir/build/BUILD/CGAL-4.12-beta1/build/src/CGAL_Qt5/all_files.cpp:4:
/builddir/build/BUILD/CGAL-4.12-beta1/include/CGAL/gl.h:35:14: fatal error: GLES3/gl3.h: No such file or directory
 #    include <GLES3/gl3.h>
              ^~~~~~~~~~~~~
compilation terminated.
```

Is there anything in CGAL that still need `<CGAL/gl.h>`?!

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Removes remaining GL native code in the CGAL packages, appart from Installation as I had no confirmation that I could remove that.

## Release Management

* Affected package(s):AABB_tree, Graphics_view, Mesh_3, Surface_mesher, Polyhedron
* Issue(s) solved (if any): fix #2879

### CODE REVIEW

File: AABB_tree/include/CGAL/internal/AABB_tree/AABB_drawing_traits.h [hunk 1]
```diff
@@ -1,103 +0,0 @@
...
-// Author(s)     :  Camille Wormser, Pierre Alliez
-
-#ifndef CGAL_AABB_DRAWING_TRAITS_H
-#define CGAL_AABB_DRAWING_TRAITS_H
-
-#include <CGAL/license/AABB_tree.h>
-
-
-#include <CGAL/Bbox_3.h>
-#include <CGAL/gl.h>
```
Comment (lrineau) [inline AABB_tree/include/CGAL/internal/AABB_tree/AABB_drawing_traits.h]: That class `AABB_drawing_traits` was modified by yourself, and no longer uses OpenGL functions.
1. You must not remove this file.
2. You must just remove the `#include <CGAL/gl.h>`.

And try to compile the `cut_plugin`!

File: Polyhedron/demo/Polyhedron/opengl_tools.h [hunk 2]
```diff
@@ -26,7 +26,6 @@
 #ifndef CGAL_OPENGL_TOOLS_H
 #define CGAL_OPENGL_TOOLS_H
 
-# include <CGAL/gl.h>
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/opengl_tools.h]: You should remove the `Color` class from this file, because it might no longer compile without the declaration of OpenGL functions.

File: AABB_tree/include/CGAL/internal/AABB_tree/AABB_drawing_traits.h (hunk 1 above)
Comment (maxGimeno) [reply AABB_tree/include/CGAL/internal/AABB_tree/AABB_drawing_traits.h]: oops, I only tried the AABB_demo. Didn't think of the cut plugin

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.12-Ic-191], and then merged.

  [CGAL-4.12-Ic-191]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-191.shtml
