### PR TITLE
fix the orientation of convex hull polyhedron of 4 points

### LINKED ISSUE #2320: Invalid Orientation of Convex hull
This is a follow up of #2171 : invalid orientation of a convex hull polyhedron.

The following program fails:

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/convex_hull_3.h>
#include <CGAL/Polygon_mesh_processing/orientation.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::Point_3 Point_3;
typedef CGAL::Polyhedron_3<K> Gm_polyhedron;

#include <fstream>


int main()
{
  Point_3 points[] = { Point_3(1.0, 0.0, 0.0), Point_3(0.0, 1.0, 0.0), Point_3(0.0, 0.0, 1.0), Point_3(0.0, 0.0, 0.0) };
  Gm_polyhedron P1;
  CGAL::convex_hull_3(points, &points[4], P1);
  std::ofstream output("poly.off");
  output << P1;
  output.close();
  CGAL_assertion( CGAL::Polygon_mesh_processing::is_outward_oriented(P1) );
}
```

### PR DESCRIPTION
**Pull request by sloriot**
## Summary of Changes

The tetrahedron was always incorrectly oriented by construction.

## Release Management

* Affected package(s): Convex_hull_3
* Issue(s) solved (if any): fix #2320

### CODE REVIEW

**Comment by lrineau** [comment]
I plan to release:
 - CGAL-4.11-beta1 tomorrow, from last night version of `integration`,
 - then CGAL-4.10.1 after my coming back from vacation, mid-August,
 - then CGAL-4.11 gold version, mid-September.

This PR will not be in CGAL-4.11-beta1, but only in CGAL-4.10.1 and CGAL-4.11.

File: Convex_hull_3/include/CGAL/convex_hull_3.h [hunk 1]
```diff
@@ -690,8 +690,12 @@ ch_quickhull_polyhedron_3(std::list<typename Traits::Point_3>& points,
       non_coplanar_quickhull_3(points, tds, traits);
       copy_face_graph(tds,P);
     }
-    else
-      make_tetrahedron(v0->point(),v1->point(),v2->point(),v3->point(),P);
+    else{
+      CGAL_assertion( traits.has_on_positive_side_3_object()(
```
Comment (afabri) [inline Convex_hull_3/include/CGAL/convex_hull_3.h]: Shouldn't that be an orientation test with 4 points instead of a constuct_plane?

Comment (sloriot) [inline Convex_hull_3/include/CGAL/convex_hull_3.h]: `Orientation_3` is not in the traits concept and it does not matter since in case we use a kernel with exact predicates, the plane is represented as a triple of points and `Orientation_3` is then used internally.

Comment (afabri) [inline Convex_hull_3/include/CGAL/convex_hull_3.h]: @lrineau  If you look at the code, do you really think that this can pose a problem if you merge it into master without going through a testsuite?  It is somehow  embarassing (mea culpa) that we don't even get the convex hull of  four points right.

**Comment by lrineau** [comment]
I have merged it without testing, closing my eyes.
