### PR TITLE
Polyhedron Demo: Big fix for windows

### LINKED ISSUE #3200: Display bugs with polylines item
## Issue Details

I have created the file [cross (selection)-edges.polylines.txt](https://github.com/CGAL/cgal/files/2159194/cross.selection.-edges.polylines.txt) by loading the `cross.off`, then selection, sharp edges, and then save the selection as a polylines item.

If one loads that file with the polyhedron demo, I have strange display issues:

1. The item is displayed, whatever is its status (view/hide) in the
   scene. See the screenshot.
   screenshot_20180703_141231

2. The display of corner balls (when activated) is wrong: they are white.
    screenshot_20180703_141500

I have cleaned by build directory. The only plugins are:
```
Plugins/IO/liboff_plugin.so 
Plugins/IO/libpolylines_io_plugin.so 
Plugins/IO/libstl_plugin.so 
Plugins/IO/libsurface_mesh_io_plugin.so 
Plugins/PMP/liborient_soup_plugin.so 
Plugins/PMP/libselection_plugin.so 
Plugins/PMP/libselection_sm_plugin.so
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux Fedora 27
* Compiler: gcc 7.3.1
* Release or debug mode: Release, with debug info
* Specific flags used (if any): flags `-Og -g`, with assertions
* CGAL version: `master` 2d9000efded57d8e41e2cde175310c4a2eaf81b1
* Boost version: 1.64.0

@maxGimeno You can add this to the top-priority bugs: we need that demo working for Siggraph.

### LINKED ISSUE #3205: Triangulation_3 Demo is broken
## Issue Details
Performing a picking operation in the T_3 demo breaks rendering.
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 64 bits
* Compiler: Clang
* Release or debug mode: debug

### LINKED ISSUE #3228: Polyhedron: Polylines can't be hidden anymore
## Issue Details

1. Create or load a polyline object
2. Uncheck "View" in the list of items, the polyline doesn't disappear.

## Environment

* CGAL version: master

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

This PR sets the default context to OpenGL ES 2, as recommended by Qt, because on some windows machines, the context 2.1 cannot be instantiated. It also fixes the widelines in OpenGL_4.3, using a geometry shader.

Fix #3200, fix #3205 and fix #3228.

### CODE REVIEW

**Comment by maxGimeno** [comment]
@jtournois or @afabri and @sgiraudot  I'll need you to test this. Relevant plugins are selection_plugin, parameterization_plugin (you need a hole in the mesh for this one), polylines, point_sets, and if it all works it should be OK I guess.

**Comment by janetournois** [comment]
how come I am the author of commit c8c12fd ?

**Comment by lrineau** [comment]
It seems that `glShadeModel`, from the OpenGL API, is still used in the basic viewer feature of Guillaume. See the [Travis link errors](https://travis-ci.org/CGAL/cgal/builds/399184244).

**Comment by sloriot** [comment]
I first tested the demo in master on macOS HighSierra 10.13.14 using Apple LLVM 9.1.0
I ran the demo through VNC. I got a warning when starting the demo about openGL context (can it be related to VNC?).
Parametrization, selection went fine but I got a strange error I never saw when I tried to orient the elephant after a shuffle.
screenshot from 2018-07-03 10-35-15

I'll now switch to that branch and test it.

**Comment by janetournois** [comment]
- facet selection does not display the selection, though the number of selected facets increases in "Infos" (but I don't know if it's related to this PR or your other PR)
- which parameterization should be tested?
- polylines and point sets : what should we test?
- opening skull.inr, I can see the bbox, planes and handles, but no image is displayed

**Comment by janetournois** [comment]
(and the ton of warnings we already met)

**Comment by maxGimeno** [comment]
@janetournois some commits come from Gauguin, I guess it makes you the author :/

**Comment by sloriot** [comment]
OK using the branch I have exactly the same results (including the warnings+the error message on soup orient). I also tested the image viewing.

**Comment by janetournois** [comment]
- selected faces are not hidden, I tried that. They are simply not displayed
- the ARAP parameterization on anchor + a hole displays the wait cursor but I don't get anything
- for skull.inr, cut planes are guessable (with the axes) but no (2D gray level) image is displayed on them. Is this normal?

**Comment by maxGimeno** [comment]
Ok it shoulb be ready for testing again. Globally it seems to work pretty well on gauguin, so I hope OpenGL spamming on windows is gone for @janetournois too !

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Jul 3, 2018, 10:29 AM GMT+2](https://github.com/CGAL/cgal/pull/3198#issuecomment-402056361 "2018-07-03T08:29:22Z - Replied by Github Reply Comments"):
> It seems that `glShadeModel`, from the OpenGL API, is still used in the basic viewer feature of Guillaume. See the [Travis link errors](https://travis-ci.org/CGAL/cgal/builds/399184244).

Those Travis errors are still there.

**Comment by janetournois** [comment]
Should I test now, or is the status "WIP"?

**Comment by maxGimeno** [comment]
@janetournois  No, you should wait until maybe tomorrow, I'm still working on important changes.

File: Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp [hunk 1]
```diff
@@ -232,7 +235,7 @@ struct Scene_edit_box_item_priv{
     //Fragment source code
     const char fragment_source[] =
     {
-      "#version 120 \n"
+      "//#version 100  \n"
```
[the remark this answers is not in the document]
Comment (maxGimeno) [reply Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp]: In the end it's only for OpenGL ES 2.0 that I will remove the #version, because the standard is #version 100 es and I had errors saying es was unexpected. Plus in my Android version, none of my shader had a #version, so I guess it will be ok.

**Comment by maxGimeno** [comment]
@janetournois Ok now It should be ready. Maybe you should start with a minimal build just to see if the inopportune warnings abour #version are gone, as I really hope .

**Comment by lrineau** [comment]
MacOS X seems [stuck with OpenGL 4.1](https://www.quora.com/Why-is-OpenGL-poorly-supported-on-Mac-OS-X). See also [this official documentation page](https://support.apple.com/en-us/HT202823) that gives details about all versions of Apple computers.

**Comment by maxGimeno** [comment]
@lrineau that's why I decided to downgrade the glsl version to the minimum needed forthe Geometry Shaders, naming 3.2 (glsl 150). Maybe requiring OpenGL 3.2 instead of 4.3 would be cleaner, but as I only test that the major version is 4 before passing to ES2 it works for @sloriot  (GL 4.1). What do you think ? 3.2 or keep with 4.3 ?

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Jul 5, 2018, 4:10 PM GMT+2](https://github.com/CGAL/cgal/pull/3198#issuecomment-402734990 "2018-07-05T14:10:36Z - Replied by Github Reply Comments"):
> @lrineau that's why I decided to downgrade the glsl version to the minimum needed forthe Geometry Shaders, naming 3.2 (glsl 150). Maybe requiring OpenGL 3.2 instead of 4.3 would be cleaner, but as I only test that the major version is 4 before passing to ES2 it works for @sloriot  (GL 4.1). What do you think ? 3.2 or keep with 4.3 ?

I think that is fine the way you did it. Let's hope Windows NVIDIA drivers do not complain about OpenGL 3.2 (GLSL 1.50) being too old.

**Comment by janetournois** [comment]
When I start the demo, I have lots of GL ERROR messages.
[log.txt](https://github.com/CGAL/cgal/files/2167004/log.txt)

**Comment by sloriot** [comment]
@janetournois with ec0f565?

**Comment by sloriot** [comment]
@maxGimeno On MacOs, I no longer have any error but there is nothing displayed for a polyhedron item. Only when _points_ display mode is set, I can see the points.

**Comment by janetournois** [comment]
About other issues,
- display of face selection is fixed
- ARAP parameterization on a sphere with a hole works nicely,
- image_io_plugin works on segmented images (I tried liver_kidney_gallbladder), and grey level (I tried skull)
- display and size slider of point set are ok
- display and line width slider of polyline are ok

**Comment by lrineau** [comment]
[**@janetournois**](https://github.com/janetournois) commented on [Jul 5, 2018, 4:39 PM GMT+2](https://github.com/CGAL/cgal/pull/3198#issuecomment-402744837 "2018-07-05T14:39:56Z - Replied by Github Reply Comments"):
> When I start the demo, I have lots of GL ERROR messages.
> [log.txt](https://github.com/CGAL/cgal/files/2167004/log.txt)

!! The shaders quoted by the error logs are from the code source of Qt5 itself... 

I think you should add `QT_LOGGING_RULES='qt.qpa.gl=true;qt.opengl.*=true' ` in the environment:
```shellsession
$ QT_LOGGING_RULES='qt.qpa.gl=true;qt.opengl.*=true' ./Polyhedron_3.exe
```
to see debug messages from Qt5 itself.

**Comment by janetournois** [comment]
@sloriot I think so. I will try again

**Comment by janetournois** [comment]
@lrineau here is the start log with the options you mention (and the same commit as above)
[log.txt](https://github.com/CGAL/cgal/files/2167203/log.txt)

**Comment by janetournois** [comment]
Permanently switching to my Nvidia graphic card (instead of automatically switching from Intel to Nvidia and back), I have no more GL ERROR's! :-)

File: Polyhedron/demo/Polyhedron/Polyhedron_demo.cpp [hunk 2]
```diff
@@ -59,12 +92,21 @@ Polyhedron_demo::Polyhedron_demo(int& argc, char **argv,
...
   d_ptr->mainWindow.reset(new MainWindow(parser.isSet(verbose)));
   MainWindow& mainWindow = *d_ptr->mainWindow;
   
   mainWindow.setWindowTitle(main_window_title);
+
+  //find a suitable context
+  if (OGLSupports(4, 3, false, QSurfaceFormat::CoreProfile))
+  {
+    
+  }
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Polyhedron_demo.cpp]: @maxGimeno Is that normal that the body of the `if` is empty? I thought you wanted to set the default format to 4.3 core profile.

File: GraphicsView/include/CGAL/Qt/qglviewer_impl.h [hunk 3]
```diff
@@ -205,33 +204,35 @@ This method is automatically called once, before the first call to paintGL().
...
+
+  {
+    format.setDepthBufferSize(24);
+    format.setStencilBufferSize(8);
+    format.setVersion(2,0);
+    format.setRenderableType(QSurfaceFormat::OpenGLES);
+    format.setSamples(0);
+    format.setOption(QSurfaceFormat::DebugContext);
+    QSurfaceFormat::setDefaultFormat(format);
+    needNewContext();
```
Comment (lrineau) [inline GraphicsView/include/CGAL/Qt/qglviewer_impl.h]: @maxGimeno I think you should `qDebug()` something, here, to be able to know which mode is used by the app.

**Comment by lrineau** [comment]
[**@janetournois**](https://github.com/janetournois) commented on [Jul 5, 2018, 5:25 PM GMT+2](https://github.com/CGAL/cgal/pull/3198#issuecomment-402760220 "2018-07-05T15:25:09Z - Replied by Github Reply Comments"):
> @lrineau here is the start log with the options you mention (and the same commit as above)
> [log.txt](https://github.com/CGAL/cgal/files/2167203/log.txt)

Two things strange here:
- the debug messages show that Qt5 uses the Intel integrated graphics card,
- the OpenGL errors are due to shaders that are internal to Qt5. I have a look at the code of Qt5, and it seems that Qt5 misunderstood the context for a non-core context, and uses legacy versions of shaders, whereas the context uses a core profile.

See the constructor of `QOpenGLEngineSharedShaders::QOpenGLEngineSharedShaders` in the file `qtbase/src/gui/opengl/qopenglengineshadermanager.cpp`.

File: Polyhedron/demo/Polyhedron/Polyhedron_demo.cpp (hunk 2 above)
Comment (maxGimeno) [reply Polyhedron/demo/Polyhedron/Polyhedron_demo.cpp]: Nope, I forgot to remove it.

**Comment by maxGimeno** [comment]
Bad news. It looks like a considerable part of the Triangulation_3 demo will need to be entirely re-coded. It massively uses legacy code for rendering and selection and other things., and none of these works within this PR.

**Comment by maxGimeno** [comment]
For the bugged Qt5 shaders, I get the same on magritte with Qt5.5.1. Apparently it's fixed in Qt 5.9. @janetournois I'm pretty sure your Qt is more recent than that though.

**Comment by sloriot** [comment]
Problems on MacOS are resolved for me.
However, Travis seems to complain about something missing libGL of mesa. @maxGimeno Is it related to this PR?
@sgiraudot  could you give it a try?

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Jul 9, 2018, 11:42 AM GMT+2](https://github.com/CGAL/cgal/pull/3198#issuecomment-403421924 "2018-07-09T09:42:50Z - Replied by Github Reply Comments"):
> For the bugged Qt5 shaders, I get the same on magritte with Qt5.5.1. Apparently it's fixed in Qt 5.9. 

Please copy-paste a reference link to that bug. That could be useful to justify why we recommend Qt 5.9.

**Comment by maxGimeno** [comment]
https://bugreports.qt.io/browse/QTBUG-47851

The last comment says it is fixed in 5.9

**Comment by lrineau** [comment]
The Periodic_Lloyd_3 demo, in file `Viewer.cpp`, still use the global function `glPointSize`. That is why there is that link error in Travis:
https://travis-ci.org/CGAL/cgal/jobs/402092660#L2427
```
[ 93%] Linking CXX executable Periodic_Lloyd_3
/usr/bin/ld: CMakeFiles/Periodic_Lloyd_3.dir/Viewer.cpp.o: undefined reference to symbol 'glPointSize'
//usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

File: Triangulation_3/demo/Triangulation_3/Viewer.cpp [hunk 4]
```diff
@@ -1667,59 +1659,131 @@ void Viewer::drawFacet(const Triangle_3& t, std::vector<float> *vertices)
...
+    buffers[33].release();
+    vao[3].release();
+    
+    QMatrix4x4 mvpMatrix;
+    double mat[16];
+    camera()->getModelViewProjectionMatrix(mat);
+    for(int i=0; i < 16; i++)
+    {
+      mvpMatrix.data()[i] = (float)mat[i];
+    }
```
Comment (lrineau) [inline Triangulation_3/demo/Triangulation_3/Viewer.cpp]: There is a [warning], about that loop:
```
...\test\Triangulation_3_Demo\Viewer.cpp(1701) : warning C4258: 'i' : definition from the for loop is ignored; the definition from the enclosing scope is used
        ...\test\Triangulation_3_Demo\Viewer.cpp(1684) : definition of 'i' ignored
        ...\test\Triangulation_3_Demo\Viewer.cpp(1662) : definition of 'i' used
```
[warning]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-Ic-62/Triangulation_3_Demo/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Release-64bits.gz

Just rename the `i` of the second loop to something else, like `i2`, to avoid the warning.

**Comment by lrineau** [comment]
The PCA_Demo and Circular_kernel_3_Demo fail to compile:
- for circular kernel, linker errors:
```
/usr/bin/ld: CMakeFiles/Circular_kernel_3.dir/Viewer.cpp.o: undefined reference to symbol 'glPointSize'
```
- for PCA, lots of compilation errors:
```
Principal_component_analysis_Demo/render_edges.h:12:11: error: 'class Viewer' has no member named 'glBegin'
Principal_component_analysis_Demo/render_edges.h:12:11: error: no member named 'glBegin' in 'Viewer'
Principal_component_analysis_Demo/render_edges.h:12: error: ‘class Viewer’ has no member named ‘glBegin’
Principal_component_analysis_Demo/render_edges.h:20:13: error: 'class Viewer' has no member named 'glVertex3d'
Principal_component_analysis_Demo/render_edges.h:20:13: error: no member named 'glVertex3d' in 'Viewer'
Principal_component_analysis_Demo/render_edges.h:20: error: ‘class Viewer’ has no member named ‘glVertex3d’
Principal_component_analysis_Demo/render_edges.h:21:13: error: 'class Viewer' has no member named 'glVertex3d'
Principal_component_analysis_Demo/render_edges.h:21:13: error: no member named 'glVertex3d' in 'Viewer'
Principal_component_analysis_Demo/render_edges.h:21: error: ‘class Viewer’ has no member named ‘glVertex3d’
Principal_component_analysis_Demo/render_edges.h:23:11: error: 'class Viewer' has no member named 'glEnd'
Principal_component_analysis_Demo/render_edges.h:23:11: error: no member named 'glEnd' in 'Viewer'
Principal_component_analysis_Demo/render_edges.h:23: error: ‘class Viewer’ has no member named ‘glEnd’
Principal_component_analysis_Demo/Scene.cpp:109:13: error: 'class Viewer' has no member named 'glPolygonMode'
Principal_component_analysis_Demo/Scene.cpp:109:13: error: 'class Viewer' has no member named 'glPolygonMode'; did you mean 'glPolygonOffset'?
Principal_component_analysis_Demo/Scene.cpp:109:13: error: no member named 'glPolygonMode' in 'Viewer'
```
and other similar error about undefined members.

File: Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp [hunk 5]
```diff
@@ -367,7 +376,8 @@ Scene_polylines_item::supportsRenderingMode(RenderingMode m) const {
 // Shaded OpenGL drawing: only draw spheres
 void
 Scene_polylines_item::draw(CGAL::Three::Viewer_interface* viewer) const {
-
+  if(!visible())
+    return;
     if(!are_buffers_filled)
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp]: There is a minor warning, because of the indentation:
```
.../platforms/ArchLinux-CXX14/test/Polyhedron_Demo/Scene_polylines_item.cpp: In member function 'virtual void Scene_polylines_item::draw(CGAL::Three::Viewer_interface*) const':
.../platforms/ArchLinux-CXX14/test/Polyhedron_Demo/Scene_polylines_item.cpp:379:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
...
...
.../platforms/ArchLinux-CXX14/test/Polyhedron_Demo/Scene_polylines_item.cpp:381:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if(!are_buffers_filled)
     ^~
```

**Comment by afabri** [comment]
Successfully tested manually on Windows VC2013 with Qt 5.10.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.13-Ic-66][*], and then merged.

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.13-Ic-66.shtml
