### PR TITLE
STL extension: Add a template argument to Prevent_deref  for the value type

### LINKED ISSUE #7400: bug: the value_type of the range returned by Triangulation_3.finite_vertex_handles() is not Vertex_handle
## Issue Details

The function `Triangulation_3.finite_vertex_handles()` returns a range of value type equal to `Triangulation_3::Vertex_handle`. At least it should. But that is wrong. The value type is actually `Triangulation_3::Finite_vertices_iterator`, that is implicitly convertible to `Vertex_handle`. That sounds right, but the following valid code does not compile:
```c++
Triangulation t;

int main()
{
  Vertex_handle v_inf = t.infinite_vertex();
  for(auto v: t.finite_vertex_handles()) {
    Vertex_handle v2 = v; // the conversion compiles
    if(v == v_inf)  // compilation error here
      return 1;
  }
  return 0;
}
```
The compilation error is:
```
[build] .../test_triangulation_ranges_value_types.cpp:51:10: error: no match for ‘operator==’ (operand types are ‘CGAL::Triangulation_3<CGAL::Epick>::Finite_vertices_iterator’ and ‘Vertex_handle’ {aka ‘CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> >, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> >, CGAL::Sequential_tag> > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>’})
[build]    51 |     if(v == v_inf) return 1;
[build]       |        ~ ^~ ~~~~~
[build]       |        |    |
[build]       |        |    Vertex_handle {aka CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_3<CGAL::Epick, CGAL::Triangulation_ds_vertex_base_3<void> >, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<void> >, CGAL::Sequential_tag> > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>}
[build]       |        CGAL::Triangulation_3<CGAL::Epick>::Finite_vertices_iterator
```

The solution is to write a special iterator type for that range, that filters out the infinite vettex, and has a special dereference function.

The other range `finite_cell_handles()` using `Prevent_deref` certainly has the same issue.

## Source Code

Here is my complete test code.

```c++
#include <type_traits>
#include <iterator>
// Add C++20 utilities to C++14
template< class T >
struct remove_cvref {
    typedef std::remove_cv_t<std::remove_reference_t<T>> type;
};

template< class T >
using remove_cvref_t = typename remove_cvref<T>::type;

template <class Iterator>
using iter_value_t = std::remove_reference_t<decltype(*std::declval<Iterator>())>;

template<class Range>
using range_value_t = iter_value_t<remove_cvref_t<decltype(std::begin(std::declval<Range>()))>>;

template< class T, class U >
constexpr bool is_same_v = std::is_same<T, U>::value;

template< class T, class U >
constexpr bool is_convertible_v = std::is_convertible<T, U>::value;


#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Triangulation_3.h>

using Triangulation = CGAL::Triangulation_3<CGAL::Exact_predicates_inexact_constructions_kernel>;

using Vertex_handle =  Triangulation::Vertex_handle;

Triangulation t;

// Tds::vertex_handles() -> Vertex_handle
static_assert(is_same_v<range_value_t<decltype(t.tds().vertex_handles())>, Vertex_handle>);

// Triangulation::all_vertex_handles() -> Vertex_handle
static_assert(is_same_v<range_value_t<decltype(t.all_vertex_handles())>, Vertex_handle>);

// Triangulation::finite_vertex_handles() -> convertible to Vertex_handle
static_assert(is_convertible_v<decltype(*std::begin(t.finite_vertex_handles())), Vertex_handle>);

// But not equal to Vertex_handle
// static_assert(is_same_v<range_value_t<decltype(t.finite_vertex_handles())>, Vertex_handle>);

int main()
{
  Vertex_handle v_inf = t.infinite_vertex();
  for(auto v: t.finite_vertex_handles()) {
    Vertex_handle v2 = v;
    if(v == v_inf) return 1;
  }
  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: gcc 13
* CGAL version: CGAL-5.6-dev (`master` version 35a1285a12b473c5a4fd0c20b2a46a1bb460362e)

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Fix issue #7400

## Release Management

* Affected package(s):  Triangulation_2, Triangulation_3, STL_extension
* Issue(s) solved (if any): fix #7400 

* License and copyright ownership: unchanged

### CODE REVIEW

**Review by lrineau — COMMENTED** [review]
I am made slight modifications about indentations, spaces, naming.

I am fine with the changes. That fixes the issue.

**Comment by sloriot** [comment]
This is most likely responsible for runtime errors in Shape_detection in CGAL-5.6-Ic-271.

might be related commits:
- https://github.com/CGAL/cgal/pull/6702/commits/427e147c7f7e8f681cc762efa14e6ab6ac0d0364 
- https://github.com/CGAL/cgal/pull/6702/commits/7c4123152b61c97613332973dc199644a4e625ab
- https://github.com/CGAL/cgal/pull/6702/commits/15b55bd32f11ff39e45c660c9fe07eab68856029

**Comment by sloriot** [comment]
Note that I also suspect that it is responsible for the many time out in PMP. From what I remember, I did try a similar change and it has a dramatic impact on the runtime of Polyhedron.

File: STL_Extension/include/CGAL/iterator.h [hunk 1]
```diff
@@ -37,28 +37,34 @@
...
+template<typename I, typename Value_type = I>
 class Prevent_deref
   : public boost::iterator_adaptor<
-  Prevent_deref<I>
+    Prevent_deref<I,Value_type>
   , I // base
-  , I // value
+  , Value_type // value
+  , boost::use_default
+  , Value_type // ref
```
Comment (sloriot) [inline STL_Extension/include/CGAL/iterator.h:47]:
```suggestion
  , std::conditional_t<std::is_same<I,Value_type>::value, boost::use_default, Value_type> // ref
```

**Comment by lrineau** [comment]
@sloriot I have removed the https://github.com/CGAL/cgal/labels/Tests%20failing label, because the corresponding tests were three months ago, and the pull-request has changed since then.

File: STL_Extension/include/CGAL/iterator.h (hunk 1 above)
Comment (sloriot) [reply STL_Extension/include/CGAL/iterator.h:47]: I don't remember precisely but it has to do with boost iterator being very much picky about a particular type of iterator. Now I remember. There is an issue with boost iterator adaptor that follows the standard saying that a bidirectional iterator must have a reference that is a reference type. If not, the adapted iterator will not be directional. We ended up with an infinite loop in `std::prev` because of that.

Comment (lrineau) [reply STL_Extension/include/CGAL/iterator.h:47]: That is actually [*LegacyForwardIterator*](https://en.cppreference.com/w/cpp/named_req/ForwardIterator) that requires that `reference` is a reference type:
> Let T be the value type of It. The type `std::iterator_traits<It>::reference` must be either 
> 
>  - `T&` or `T&&` (since C++11) if It satisfies [LegacyOutputIterator](https://en.cppreference.com/w/cpp/named_req/OutputIterator) (It is mutable), or
>  - `const T&` or `const T&&` (since C++11) otherwise (It is constant), 
> 
> (where T is the type denoted by `std::iterator_traits<It>::value_type`)

Comment (lrineau) [reply STL_Extension/include/CGAL/iterator.h:47]: Then maybe the second argument of `Prevent_deref` should be the reference type `Ref_type`, directly (with a `static_assert<std::is_reference_v<Ref_type>>`).

**Comment by lrineau** [comment]
> I suspect this PR to be responsible for [Shape detection runtime errors in CGAL-6.0-Ic-114](https://cgal.geometryfactory.com/CGAL/testsuite/results-6.0-Ic-114.shtml#Shape_detection).

The address sanitizer found stack-use-after-scope errors: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-114/Shape_detection/TestReport_lrineau_Fedora-Release.gz

**Comment by janetournois** [comment]
This PR has both labels "Tests failing" and "Ready to be tested"....(?)

**Comment by lrineau** [comment]
> This PR has both labels "Tests failing" and "Ready to be tested"....(?)

This PR #7410 is on my personal TODO-list. It is a blocker for #8170.

**Review by lrineau — APPROVED** [review]
After latests commits, I tested a lot locally, on Fedora Linux 40, with optimizers and assertions:

```shellsession
> ctest --test-dir build/RelWithDebInfo -j12 -L 'Arr|Triangulation_[23]|SMDS|STL|Mesh_[23]|TDS_[23]|Shape' -j12 
Internal ctest changing into directory: /home/lrineau/Git/cgal-master/build/RelWithDebInfo
Test project /home/lrineau/Git/cgal-master/build/RelWithDebInfo
          Start    2: check build system
[...]
100% tests passed, 0 tests failed out of 1105

Label Time Summary:
Arrangement_on_surface_2_Demo          = 418.14 sec*proc (1 test)
Arrangement_on_surface_2_Examples      = 2098.81 sec*proc (130 tests)
Arrangement_on_surface_2_Tests         = 1725.35 sec*proc (347 tests)
Arrangement_on_surface_2_earth_Demo    =  66.69 sec*proc (1 test)
CGAL_build_system                      =  20.59 sec*proc (2 tests)
Installation                           =  20.59 sec*proc (2 tests)
Mesh_2_Demo                            =  46.22 sec*proc (2 tests)
Mesh_2_Examples                        = 207.70 sec*proc (14 tests)
Mesh_2_Tests                           = 281.50 sec*proc (28 tests)
Mesh_3_Examples                        = 2732.15 sec*proc (70 tests)
Mesh_3_Tests                           = 2595.52 sec*proc (60 tests)
SMDS_3_Examples                        =  51.89 sec*proc (6 tests)
SMDS_3_Tests                           = 274.94 sec*proc (16 tests)
STL_Extension_Examples                 =  32.31 sec*proc (14 tests)
STL_Extension_Tests                    = 221.11 sec*proc (72 tests)
Shape_detection_Examples               = 410.24 sec*proc (28 tests)
Shape_detection_Tests                  = 856.47 sec*proc (46 tests)
Shape_regularization_Examples          =  83.29 sec*proc (12 tests)
Shape_regularization_Tests             = 502.73 sec*proc (46 tests)
TDS_2_Tests                            =  17.89 sec*proc (4 tests)
TDS_3_Examples                         =  15.77 sec*proc (6 tests)
TDS_3_Tests                            =  26.06 sec*proc (6 tests)
Triangulation_2_Demo                   = 131.43 sec*proc (3 tests)
Triangulation_2_Examples               = 621.42 sec*proc (54 tests)
Triangulation_2_Tests                  = 687.99 sec*proc (50 tests)
Triangulation_3_Demo                   = 100.61 sec*proc (1 test)
Triangulation_3_Examples               = 543.42 sec*proc (42 tests)
Triangulation_3_Tests                  = 746.26 sec*proc (44 tests)

Total Test time (real) = 1679.44 sec
```

Looks good, at least on my Linux machine.

**Comment by sloriot** [comment]
Successfully tested in 6.0-Ic-251
