### PR TITLE
PMP: Fix doxygen warnings

### LINKED ISSUE #4548: Documentation warnings in overnight build
In the overnight builds CGAL-5.0.3-I-207 and CGAL-5.1-Ic-86 I see for the Polygon_mesh_processing package:
> todo:8: warning: unexpected token TK_COMMAND_BS as the argument of _internalref
> todo:21: warning: unexpected token TK_COMMAND_BS as the argument of _internalref

Looking a bit into the problem I see that the come from:
- the file Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h line 1201
  > /// \todo use the area criteria? this means maybe continue exploration of larger cc
- the file Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/merge_border_vertices.h line 112:
  > /// \todo shall we try to be more conservative?

this is in the middle of the method and doxygen has no idea where to place it, changing `///` into `//` will solve the issue.

Note: there is some more "documentation" in repair.h that start with `///` (e.g. line 1371), this is a bit a strange block as it looks like it is intended as a comment block, but most lines just have `//`  or the `///` has not been changed into `//`. (Looks like incorrect merges after the "big" change of:

> Commit: 0417bb88d77c652fd301787eb0b110ea062dd6b8 [0417bb8]
> Parents: 5b22f7213e
> Author: Mael Rouxel-Labbé <mael.rouxel.labbe@geometryfactory.com>
> Date: Wednesday, July 25, 2018 10:51:53 AM
> Committer: Mael Rouxel-Labbé
> Commit Date: Wednesday, July 25, 2018 10:53:30 AM
> Hide "remove_degenerate_faces"

### PR DESCRIPTION
**Pull request by MaelRL**
## Release Management

* Affected package(s): `Polygon_mesh_processing`
* Issue(s) solved (if any): fix #4548

### CODE REVIEW

File: Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h [hunk 1]
```diff
@@ -1089,15 +1089,15 @@ bool remove_degenerate_edges(TriangleMesh& tmesh)
 //         - `Compare_distance_3` to compute the distance between 2 points
 //         - `Collinear_3` to check whether 3 points are collinear
 //         - `Less_xyz_3` to compare lexicographically two points
-///        - `Equal_3` to check whether 2 points are identical.
-///       For each functor Foo, a function `Foo foo_object()` must be provided.
+//        - `Equal_3` to check whether 2 points are identical.
```
Comment (albert-github) [inline Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h]: Indentation is here before the `-` different, in the current situation no problem but when all lines of the comment block would get `///` again it is a small problem (I don't think this is intended in the future so just a small warning).

Comment (MaelRL) [reply Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h]: It doesn't matter because the code for 5.1 is in another PR, where that particular function is properly documented, but thanks for the heads-up.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-88.shtml
