### PR TITLE
Triangulation_3: Fix insertion and removal of ranges of weighted points (for 4.12)

### LINKED ISSUE #3354: Segmentation fault in parallel (TBB) regular triangulation 3d
## Issue Details

Segmentation fault happens when inserting points in a parallel regular triangulation object with varying weights. Running with `gdb` gives the following:

```
[Switching to Thread 0x7ffff5833700 (LWP 20752)]
0x0000555555586084 in CGAL::Spatial_lock_grid_base_3<CGAL::Spatial_lock_grid_3<CGAL::Tag_priority_blocking> >::try_lock<false, CGAL::Weighted_point_3<CGAL::Epick> > (this=0x7fffffffda38, point=..., lock_radius=0) at /usr/include/CGAL/Spatial_lock_grid_3.h:221
221       bool try_lock(const P3 &point, int lock_radius = 0)
```

## Source Code

Using an adaptation of the TBB enabled example with varying weights.

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Regular_triangulation_3.h>
#include <CGAL/point_generators_3.h>
#include <iostream>
#include <fstream>
#include <vector>
#include <random>
#include <functional>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
// Regular T3
typedef CGAL::Triangulation_data_structure_3< 
  CGAL::Regular_triangulation_vertex_base_3<K>, 
  CGAL::Regular_triangulation_cell_base_3<K>, 
  CGAL::Parallel_tag>                                       Tds;
typedef CGAL::Regular_triangulation_3<K, Tds>               Rt;
typedef Rt::Bare_point                                      Bare_point;
typedef Rt::Weighted_point                                  Weighted_point;
typedef Rt::Vertex_handle                                   Vertex_handle;

constexpr int N = 1000000;

struct MyRT
{
  Rt::Lock_data_structure lock;
  std::vector<Weighted_point> points;
  Rt rt;

  MyRT(std::function<double ()> w)
    : lock(CGAL::Bbox_3(-1., -1., -1., 1., 1., 1.), 50)
    , rt(K(), &lock)
  {
    CGAL::Random_points_in_cube_3<Bare_point> rnd(1.);
    points.reserve(N);
    for (int i = 0; i < N; ++i)
      points.push_back(Weighted_point(*rnd++, w()));
    std::cout << "Inserting points.\n";
    rt.insert(points.begin(), points.end());
  }
};

int main()
{
  std::mt19937 random(0);
  std::normal_distribution<double> normal;

  MyRT myrt(std::bind(normal, random));
  assert(myrt.rt.is_valid());

  return 0;
}
```

compiled with

```shell
g++ -frounding-math -lm -lCGAL -lgmp -lboost_thread -lmpfr \
    -DCGAL_LINKED_WITH_TBB -pthread -ltbb -latomic -ltbbmalloc -pthread \
    cgal-parallel.cc
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): GNU/Linux Debian (testing) 64bit
* Compiler: confirmed with GCC 6.4.0 and GCC 8.2.0
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: 4.12.0 and 4.12.1
* Boost version: 1.62.0
* Other libraries versions if used (Eigen, TBB, etc.): TBB

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

- In a parallel insertion of a range of weighted points, the 'hint' is a vertex handle that is unsafe to use because the insertion of a weighted point by another thread might hide (delete) the hint.
  _Solution_: check the validity of the hint before and after trying to lock it.
- The removal of a range of weighted points while storing hidden points means that we re-insert hidden points after a successful removal. However, since we have only locked what was needed to remove the vertex and not to re-insert the hidden points, deadlocks can appear.
  _Solution_: unlock everything after successful removal and threads can then wrestle normally for control of zones to re-insert hidden points. Same check is needed on the hint.

## Release Management

* Affected package(s): `Triangulation_3`
* Issue(s) solved (if any): fix #3354
* Feature/Small Feature (if any): --

### CODE REVIEW

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h [hunk 1]
```diff
@@ -1324,14 +1324,48 @@ namespace CGAL {
...
+          if(!m_rt.tds().is_vertex(hint))
+#endif
+          {
+            hint = m_rt.finite_vertices_begin();
+            continue;
+          }
+
+          // We need to make sure that while are locking the position P1 := hint->point(), 'hint'
+          // does not get its position changed to P2 != P1.
+          const Weighted_point hint_point_mem = hint->point();
```
Comment (lrineau) [inline Triangulation_3/include/CGAL/Regular_triangulation_3.h]: The `point()` method is not thread-safe. You should store `hint_point_mem` the same way you store `hint`: only refresh it once the lock is obtained.

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h [hunk 2]
```diff
@@ -1324,14 +1324,48 @@ namespace CGAL {
...
+            // that its position hasn't changed to ensure that we will start the locate from where
+            // we have locked.
+#ifdef CGAL_RT3_IGNORE_TDS_CONCEPT
+            if(!m_rt.tds().vertices().is_used(hint) ||
+#else
+            if(!m_rt.tds().is_vertex(hint) ||
+#endif
+               hint->point() != hint_point_mem)
+            {
+              hint = m_rt.finite_vertices_begin();
```
Comment (lrineau) [inline Triangulation_3/include/CGAL/Regular_triangulation_3.h]: `m_rt.finite_vertices_begin()` is not locked, and may be under destruction as well. In my opinion, only the infinite vertex is safe.

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h [hunk 3]
```diff
@@ -2388,40 +2453,96 @@ namespace CGAL {
...
     else
     {
-      Vertex_handle hint = (v->cell()->vertex(0) == v ?
-        v->cell()->vertex(1) : v->cell()->vertex(0));
+      // Check that the vertex hasn't be deleted from the TDS while we were locking it
+#ifdef CGAL_RT3_IGNORE_TDS_CONCEPT
+      if(!tds().vertices().is_used(v))
+#else
+      if(!tds().is_vertex(v))
+#endif
```
Comment (lrineau) [inline Triangulation_3/include/CGAL/Regular_triangulation_3.h]: I am surprised that a vertex that we managed to lock can be destroyed by another thread. That would defeat all the purpose of the lock.

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h (hunk 1 above)
Comment (MaelRL) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: I think this whole `hide_point_mem` shenanigan is actually just useless. In other contexts, we need to ensure that the position of the lock is valid by checking the erase counter. Here, I just need to ensure that I locked _some_ valid place, and it doesn't matter if it's not where I thought it was.

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h (hunk 2 above)
Comment (MaelRL) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: First thing it'll do when it enters the loop again is to check the validity of the `hint` so it should be safe.

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h (hunk 3 above)
Comment (MaelRL) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: I'm checking here that `v` is a valid vertex in case it was destroyed _before_ it was locked. I could also check the validity before the `try_lock_vertex`, but there's no real point since it might be destroyed in between that check and the lock.

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h (hunk 1 above)
Comment (lrineau) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: I agree, but the value of `hint_point_mem` cannot be trusted, unless you assign it once in the `try_lock` block.

Comment (MaelRL) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: Sure, but I don't care about its value: of course it would ideally be where I think it is, but if it is not and it locked somewhere else, then the `locate` will just start from another position and that's alright as the hint might be wrong anyway in the first place. 

All I care about is that the `vh->cell()` is safe to use, not whether it is at an interesting position.

**Comment by lrineau** [comment]
@MaelRL: why the flag `not yet approved`?

**Comment by MaelRL** [comment]
Just to emphasis the code review. If you're okay with the diff and my last replies, it can be removed.

**Comment by MaelRL** [comment]
Nevermind, I forgot also the fact that currently it has this ugly macro: see [this comment](https://github.com/CGAL/cgal/pull/3367#discussion_r222331973). Do I just go through with ignoring the TDS concept?

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h [hunk 4]
```diff
@@ -1324,14 +1324,48 @@ namespace CGAL {
...
-          if (m_rt.try_lock_vertex(hint) && m_rt.try_lock_point(p))
+          // The 'hint' is unsafe to use immediately because we are in a regular triangulation,
+          // and the insertion of a (weighted) point in another thread might have hidden (deleted)
+          // the hint.
+#define CGAL_RT3_IGNORE_TDS_CONCEPT
+#ifdef CGAL_RT3_IGNORE_TDS_CONCEPT
+          if(!m_rt.tds().vertices().is_used(hint))
+#else
+          if(!m_rt.tds().is_vertex(hint))
+#endif
```
[the remark this answers is not in the document]
Comment (lrineau) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: In my opinion, the concepts `TDS_2` are `TDS_3` are just a way to document the actual concrete implementation. I am pretty sure that there are already a lot of things that are not really documented in those concepts, and we can go on and add new undocumented stuff, in my opinion.

On the other hand, you can also document the new requirement.

[the remark this answers is not in the document]
Comment (lrineau) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: Your bench times are probably not reliable: the "system time" of the first result probably indicates a loaded machine.

[the remark this answers is not in the document]
Comment (MaelRL) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: I do get the same results consistently and the machine has nothing else running. I know practically nothing about kernel mode instructions, but won't going through all the items of the compact container require a lot of caching, which would then create this dramatic increase in system time?

File: Triangulation_3/include/CGAL/Regular_triangulation_3.h (hunk 1 above)
Comment (MaelRL) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: Documenting it is difficult because we already don't expose the vertex/cell containers. Also, there are indeed some calls to undocumented functions from the TDS at a few points, but nothing "as bad" as calling the containers.

aa1e0acbeef802a1ae8cbdfeaec2f0808211d4d5 does something legal and the time loss compared to directly calling the function is hardly noticeable. Is this ok?

Comment (lrineau) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: I really do not like specializations, because that breaks easily. We have seen that on several occasions (for example the first version of the implementation of the structural filtering was almost only used in the test cases, but not in real uses cases).

Could it be related to the detection of a tag, instead?

Comment (MaelRL) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: How would a tag ensure that other TDS without such tag be properly tested or used in real cases ? In any case, we don't have any tests checking that T3 concepts match the actual code requirements (and they don't).

Comment (lrineau) [reply Triangulation_3/include/CGAL/Regular_triangulation_3.h]: Anyway, nothing will ensure that "other TDS" will be properly tested, because there exists only one concept `TDS_3` in the world.

But the use of a tag (instead of a specialization) will ensure that the trick will not break if:
  - one derives from a TDS, or if
  - one adds new templates parameters to TDS_3, will default values,
  - other maybe other patterns that can break easily with a specialization, and that I do not know of.

The truth is just that specialization on full classes is generally bad, whereas specialization on tags is acceptable.

And the worst is that the trick could turn unused without any compiler warning or failure. That is exactly what happened with the structural filtering, that was triggered by a full-specialization on `CGAL::Epick`

**Comment by sloriot** [comment]
@MaelRL  what is the status of this PR wrt the Tests failing?

**Comment by MaelRL** [comment]
Tests failing are irrelevant, I have to change the way the detection of CGAL::TDS_3 is coded (see https://github.com/CGAL/cgal/pull/3367#discussion_r224474228), but I haven't gotten around to it yet.

**Comment by lrineau** [comment]
You could also assume that `CGAL::TDS_3` is mandatory. Anyway, that is the only thing we have been testing for years.

**Comment by MaelRL** [comment]
I have used a tag in 82e458d. Should be good to test now if CR / Travis are okay.

**Comment by lrineau** [comment]
Travis is OK.

**Comment by lrineau** [comment]
Warnings on Windows: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-46.shtml#Triangulation_3

**Comment by lrineau** [comment]
@MaelRL Can you please merge this PR in `integration`, and fix the conflicts with `master`?

Maybe you should create another PR for 4.13 or `master`, to avoid those conflicts.

**Comment by sloriot** [comment]
Successfully tested in CGAL-4.14-Ic-87
