### PR TITLE
Triangulation_2: Fix CDT_plus_2::remove_constraint()

### LINKED ISSUE #4010: Remove and restore constraint with Constrained_triangulation_plus_2
Hello,

I wonder if if it is possible to restore a constraint after it has been removed with Constraint triangulation plus.

The code below returns a false value because the last  insert_constaint() method call returns a null constraint id : the constraint is not inserted as if it is still existing.
This null value seems result from the constraint_map of the hierarchy. The key value seems not be removed from the map when the constraint is removed.

Is this behavior is normal ?

Thanks

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Triangulation_2.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Constrained_triangulation_plus_2.h>


typedef CGAL::Exact_predicates_inexact_constructions_kernel                 K;
typedef CGAL::Polygon_2<K>                                                Polygon_2;
typedef CGAL::Exact_intersections_tag                                     Itag_;
typedef CGAL::Constrained_Delaunay_triangulation_2<K,CGAL::Default, Itag_> CDT;
typedef CGAL::Constrained_triangulation_plus_2<CDT>                       CDTP;

typedef CDTP::Point                                                       Point;
typedef CDTP::Constraint_id                                               Cid;
typedef CDTP::Vertex_handle                                               Vertex_handle;


bool testCDTP()
{
    CDTP cdtp;

    Vertex_handle handle1=cdtp.insert(Point(0,0));
    Vertex_handle handle2=cdtp.insert(Point(0,10));
    Vertex_handle handle3=cdtp.insert(Point(10,10));
    Vertex_handle handle4=cdtp.insert(Point(10,0));

    cdtp.insert_constraint(handle1,handle3);

    cdtp.remove_constraint(handle1,handle3);

    auto lastConstraintId=cdtp.insert_constraint(handle1,handle3);

    return (lastConstraintId != nullptr);

}
```

## Environment

* Operating system Linux debian 64 bits
* Compiler: GCC
* Release or debug mode: debug

* CGAL version: 4.13
* Boost version: 1.67

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Fix the bookkeeping of constraints. Forgot to remove it from a `std::map`.

**This must NOT go into master**, as we have removed the function `remove_constraint()` which takes two vertex handles as key.

## Release Management

* Affected package(s): Triangulation_2
* Issue(s) solved (if any): fix #4010

### CODE REVIEW

File: Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h [hunk 1]
```diff
@@ -256,6 +256,7 @@ class Polyline_constraint_hierarchy_2
   void remove_constraint(Vertex_handle va, Vertex_handle vb)
   {
     remove_constraint(constraint_map[make_edge(va,vb)]);
+    constraint_map.erase(make_edge(va,vb));
```
Comment (lrineau) [inline Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h]: It seems there are two lookups in `constraint_map`. You can probably use a single lookup with  `map.find`.

**Comment by lrineau** [comment]
Actually, we have no way to test this pull-request. I will merge it as soon as Travis is OK with it.
