### PR TITLE
Polyhedron demo: Fix shrinking in c3t3

### LINKED ISSUE #2418: Default shrink factor of a c3t3 in the demo
When loading a c3t3 in the demo, the facets are already shrinked a bit. Is it a bug or is it expected?

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

Set the shrinking cursor value after setting its maximum.

## Release Management
* Issue(s) solved (if any): fix #2418

### CODE REVIEW

File: Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp [hunk 1]
```diff
@@ -273,9 +273,9 @@ struct Scene_c3t3_item_priv {
   {
     init_default_values();
     tet_Slider = new QSlider(Qt::Horizontal);
-    tet_Slider->setValue(100);
     tet_Slider->setMinimum(0);
     tet_Slider->setMaximum(100);
+    tet_Slider->setValue(100);
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp]: Whoah, that one was a nasty bug! Previously the `setValue(100)` was called before `setMaximum(100)`, and the default maximum is... 99, as far as I know!
