### PR TITLE
Polygonal Surface Reconstruction: Remapping of plane_indices in input data to range [0..n-1]

### LINKED ISSUE #7433: The Polygonal Surface Reconstruction algorithm run failed
_Please use the following template to help us solving your issue._

## Issue Details
I'm using the the example of Reconstruction with User-Provided Planes  from CGAL's"Polygonal_surface_reconstruction/polyfit_example_user_provided_planes.cpp", I have split point cloud planes, each plane with different color information（PCD format）.Then I converted it to the  ply format according to the source code, The properties of the converted ply file are given below, but the program will report an exception when running, please how can I solve this problem?

##Ply file
My converted ply file is here ： [ply.zip](https://github.com/CGAL/cgal/files/11431216/ply.zip)

V@I$(SR13AFBOZ~WA`HDEU1

The place circled in the image below will be abnormal
6D1~OU9UJR8_TPMX_N50D5M
8 O CNK{EKN8X(@YZ4J8A0G
60_1JVKGMFRRZ{7R_)2L%1P

## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/IO/read_points.h>
#include <CGAL/property_map.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygonal_surface_reconstruction.h>
//#define CGAL_USE_SCIP  // defined (or not) by CMake scripts, do not define by hand
/*#include <CGAL/SCIP_mixed_integer_program_traits.h>
typedef CGAL::SCIP_mixed_integer_program_traits<double>*/                        //MIP_Solver;
#define CGAL_USE_GLPK  // defined (or not) by CMake scripts, do not define by hand
#include <CGAL/GLPK_mixed_integer_program_traits.h>
typedef CGAL::GLPK_mixed_integer_program_traits<double>                        MIP_Solver;


#include <CGAL/Timer.h>
#include <fstream>
typedef CGAL::Exact_predicates_inexact_constructions_kernel                Kernel;
typedef Kernel::Point_3                                                                                        Point;
typedef Kernel::Vector_3                                                                                Vector;
typedef        CGAL::Polygonal_surface_reconstruction<Kernel>                        Polygonal_surface_reconstruction;
typedef CGAL::Surface_mesh<Point>                                                                Surface_mesh;
// Point with normal, and plane index
typedef boost::tuple<Point, Vector, int>                                                PNI;
typedef CGAL::Nth_of_tuple_property_map<0, PNI>                                        Point_map;
typedef CGAL::Nth_of_tuple_property_map<1, PNI>                                        Normal_map;
typedef CGAL::Nth_of_tuple_property_map<2, PNI>                                        Plane_index_map;
/*
* The following example shows the reconstruction using user-provided
* planar segments stored in PLY format. In the PLY format, a property
* named "segment_index" stores the plane index for each point (-1 if
* the point is not assigned to a plane).
*/
int main(int argc, char* argv[])
{
    const std::string input_file = ("output.ply");
    std::ifstream input_stream(input_file.c_str());
    std::vector<PNI> points; // store points
    std::cout << "Loading point cloud: " << input_file << "...";
    CGAL::Timer t;
    t.start();
    if (!CGAL::IO::read_PLY_with_properties(input_stream,
        std::back_inserter(points),
        CGAL::make_ply_point_reader(Point_map()),
        CGAL::make_ply_normal_reader(Normal_map()),
        std::make_pair(Plane_index_map(), CGAL::PLY_property<int>("segment_index"))))
    {
        std::cerr << "Error: cannot read file " << input_file << std::endl;
        return EXIT_FAILURE;
    }
    else
        std::cout << " Done. " << points.size() << " points. Time: " << t.time() << " sec." << std::endl;
    std::cout << "Generating candidate faces...";
    t.reset();
    Polygonal_surface_reconstruction algo(
        points,
        Point_map(),
        Normal_map(),
        Plane_index_map()
    );
    std::cout << " Done. Time: " << t.time() << " sec." << std::endl;
    Surface_mesh model;
    std::cout << "Reconstructing...";
    t.reset();
    if (!algo.reconstruct<MIP_Solver>(model)) {
        std::cerr << " Failed: " << algo.error_message() << std::endl;
        return EXIT_FAILURE;
    }
    // Saves the mesh model
    const std::string& output_file("user_provided_planes_result.off");
    if (CGAL::IO::write_OFF(output_file, model))
        std::cout << " Done. Saved to " << output_file << ". Time: " << t.time() << " sec." << std::endl;
    else {
        std::cerr << " Failed saving file." << std::endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}

```

## Environment

* Operating system (Windows 64 bits):
* Compiler: VS2019
* debug mode
* CGAL version: 5.5.2 
* Boost version: 1.82.0#1

### PR DESCRIPTION
**Pull request by soesau**
## Summary of Changes

Remapping of plane_indices in input data to range [0..n-1] as required by method.

## Release Management

* Affected package(s): Polygonal Surface Reconstruction
* Issue(s) solved (if any): fix #7433

### CODE REVIEW

File: Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h [hunk 1]
```diff
@@ -136,29 +136,23 @@ namespace CGAL {
...
-
                                 std::size_t idx = 0;
                                 for (typename PointRange::const_iterator it = points.begin(); it != points.end(); ++it) {
                                         Base_class::m_points[idx] = get(point_map, *it);
                                         Base_class::m_normals[idx] = get(normal_map, *it);
                                         int plane_index = get(plane_index_map, *it);
                                         if (plane_index != -1) {
-                                                Planar_segment* ps = planar_segments_[plane_index];
-                                                ps->push_back(idx);
+                                          if (plane_index_remap.find(plane_index) == plane_index_remap.end()) {
```
Comment (sloriot) [inline Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h:149]: you should use find to get the iterator and use the iterator to update the value (instead of 2 queries

Comment (sloriot) [reply Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h:149]: 3 queries actually

Comment (soesau) [reply Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h]: Should be resolved with the second commit

File: Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h [hunk 2]
```diff
@@ -136,29 +136,25 @@ namespace CGAL {
...
                                         if (plane_index != -1) {
-                                                Planar_segment* ps = planar_segments_[plane_index];
-                                                ps->push_back(idx);
+                                          auto it = plane_index_remap.find(plane_index);
+                                          if (it == plane_index_remap.end()) {
+                                            plane_index_remap[plane_index] = planar_segments_.size();
+                                            planar_segments_.push_back(new Planar_segment(this));
+                                            planar_segments_.back()->push_back(idx);
+                                          }
+                                          else planar_segments_[it->second]->push_back(idx);
```
[the remark this answers is not in the document]
Comment (sloriot) [reply Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h:155]: @soesau do you agree?

[the remark this answers is not in the document]
Comment (soesau) [reply Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h]: Almost, one line was missing. I made a checkin including your suggestion.
