### PR TITLE
Fix GT/VPM usage in approximate Hausdorff distance computations

### LINKED ISSUE #6536: CGAL::Polygon_mesh_processing::approximate_Hausdorff_distance crashes with empty meshes
## Issue Details

`CGAL::Polygon_mesh_processing::approximate_Hausdorff_distance(sm1, sm2)` crashes with assertions if any of the two meshes is empty. But that is not documented.

It should either be documented as a precondition, or return +∞.

## Environment

* CGAL version: 5.4, master

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

Also, make the fact that non-empty ranges are expected clear in the doc and add missing preconditions.

## Release Management

* Affected package(s): `PMP`
* Issue(s) solved (if any): fix #6536 
* Feature/Small Feature (if any): -
* License and copyright ownership: no change

### CODE REVIEW

File: Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h [hunk 1]
```diff
@@ -1045,55 +1053,85 @@ sample_triangle_soup(const PointRange& points,
...
-                                      VertexPointMap vpm)
+          class PointRange,
+          class NamedParameters = parameters::Default_named_parameters>
+double max_distance_to_triangle_mesh(const PointRange& points,
+                                     const TriangleMesh& tm,
+                                     const NamedParameters& np = parameters::default_values())
 {
-  CGAL_assertion(is_triangle_mesh(tm));
+  CGAL_precondition(!is_empty(tm) && is_triangle_mesh(tm));
+  CGAL_precondition(!is_empty(tm));
```
Comment (sloriot) [inline Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h:1098]:
```suggestion
```

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-77

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-83
