### PR TITLE
Mesh_3: fix issue #9277

### LINKED ISSUE #9277: Mesh_3: bug mesh_3D_image_with_image_initialization
```plain
------------------------------------------------------------------
- Mesh_3_Examples/ProgramOutput.execution   of  mesh_3D_image_with_image_initialization
------------------------------------------------------------------

CGAL::Random()::get_seed() = 1768256345
Searching for connected components...
  51 components were found.
Construct initial points...
  986 initial points were constructed.
Failure: 49 subdomains were meshed. Expected 50 instead.
```

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.2-Ic-81/Mesh_3_Examples/TestReport_Taylor_macOS-Apple_M2-boost_backend-arm64.gz

Can be reproduced on Linux with:

```c++
CGAL::get_default_random() = CGAL::Random(1768285287);
```

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

During the initialization of labeled images, PR #6978 skipped seeds for which the component seemed already initialized. But the criterion "already initialized" was not right: later insertions of points could alter it.

This PR retries the initialization of seeds that were previouly skipped.

## Release Management

* Affected package(s): Mesh_3 
* Issue(s) solved (if any): fix #9277

### CODE REVIEW

File: Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h [hunk 1]
```diff
@@ -347,7 +350,18 @@ struct Construct_initial_points_labeled_image
           ++nb_of_points;
         }
       }
+    };
+    for(;;)
```
Comment (janetournois) [inline Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h]: what about replacing this infinite loop by a `while()` loop using the criterion

```c++
nb_of_points_before == nb_of_points || rejected_seeds.empty()
```

?

Comment (lrineau) [reply Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h]: I would welcome a patch. I had difficulties to set that up, and that infinite loop was the best I found. Instead of a `break`, we could use `return` instead.

If `treat_seed` returns the number of points it has inserted, then it could be:

```c++
while(std::transform_reduce(seeds.begin(), seeds.end(), 0, std::plus<>, treat_seed) > 0
      && false == rejected_seeds.empty())
{
  seeds = std::move(rejected_seeds);
  rejected_seeds.clear();
}
```

but is that really easier to read?

**Comment by janetournois** [comment]
@lrineau I wrote a suggestion to remove the infinite loop (easy to read ;-))
On my machine, with the seed given in the issue, the example passes with 50 spheres -> 50 subdomains

**Comment by lrineau** [comment]
> @lrineau I wrote a suggestion to remove the infinite loop (easy to read ;-)) On my machine, with the seed given in the issue, the example passes with 50 spheres -> 50 subdomains

Thanks. That looks good to me.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.2-Ic-101
