### PR TITLE
Fix conversion error in METIS wrappers

### LINKED ISSUE #5410: METIS partition graph type conversion error
# Issue Details
In [partition_graph()](https://doc.cgal.org/latest/BGL/group__PkgBGLPartition.html#gae7e37b6101e63f4c5959f1ae6c6fe7d2) function that we can found in `CGAL-5.1.1/include/CGAL/boost/graph/METIS/partition_graph.h` the `nparts` parameter is an `int`.
Inside partition_graph(), the METIS_PartMeshNodal() function (from `metis.h`) is called, and it take `nparts` as parameter.

The problem is that in METIS_PartMeshNodal(), `nparts` is of type `idx_t*` and not `int*`.
`idx_t` is a typedef for `long long` so it doesn't seem to me that conversion should be a problem, but VisualStudio throw me this error: 

```
'int METIS_PartMeshNodal(idx_t *,idx_t *,idx_t *,idx_t *,idx_t *,idx_t *,idx_t *,real_t *,idx_t *,idx_t *,idx_t *,idx_t *)': cannot convert argument 7 from 'int *' to 'idx_t *'
```

Somebody know why he don't want to convert an `int*` to an `long long *` ?

# Environment
Operating system: Windows 10, 64 bits
Compiler: MSVC 14.2
Release or debug mode: Release
CGAL version: 5.1.1
Boost version: 1.74.0
Eigen version: 3.3.9
Metis version: 5.1.0

### PR DESCRIPTION
**Pull request by MaelRL**
## Release Management

* Affected package(s): `BGL`
* Issue(s) solved (if any): fix #5410
* Feature/Small Feature (if any): -
* License and copyright ownership: no change

### CODE REVIEW

File: BGL/include/CGAL/boost/graph/METIS/partition_dual_graph.h [hunk 1]
```diff
@@ -98,7 +98,7 @@ void partition_dual_graph(const TriangleMesh& tm,
   CGAL_assertion_code(int ret =)
     METIS_PartMeshDual(&ne, &nn, eptr, eind,
                        nullptr /* elements weights*/, nullptr /*elements sizes*/,
-                       &ncommon, &nparts,
+                       &ncommon, static_cast<idx_t*>(&nparts),
```
Comment (lrineau) [inline BGL/include/CGAL/boost/graph/METIS/partition_dual_graph.h:101]: That cannot work. The variable `nparts` is a parameter of the function, of type `int`, on the stack. If `idx_t` and `int` have different size (and they seem so), then reading `nparts` through a point to `long long` will add 32 bits to the type, and whatever is in memory in those 32 bits (4 octets) will be added to the value as the 32 most significant bits.

The right solution is to create a real variable of the right type, with the right value:
```c++
idx_t nparts_as_idx_t = nparts;
// [...]
METIS_PartMeshDual(&ne, &nn, eptr, eind,
                       nullptr /* elements weights*/, nullptr /*elements sizes*/,
                       &ncommon, &nparts_as_idx_t,
                       nullptr /* partitions weights */,
                       *options,
                       &objval, epart, npart);
```

**Review by lrineau — APPROVED** [review]

File: BGL/include/CGAL/boost/graph/METIS/partition_dual_graph.h (hunk 1 above)
Comment (MaelRL) [reply BGL/include/CGAL/boost/graph/METIS/partition_dual_graph.h]: Right, thank you.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-100
