### PR TITLE
Nef_3: Fix broken greater-than

### LINKED ISSUE #6151: Broken greater-than operator for Nef_polyhedron_3
## Issue Details

For two disjoint Nef polyhedra `poly1` and `poly2`, `poly1 > poly2` returns `true`.  The other comparison operators don't seem to be affected. Most likely this is caused by a missing `N1` in [this line](https://github.com/CGAL/cgal/blob/cce94c21c5aad8a55ca5bc272229628e70bb3049/Nef_3/include/CGAL/Nef_polyhedron_3.h#L1559), i.e. it should be `return N1.difference(*this).is_empty() && !difference(N1).is_empty();`.

## Source Code

```c++
#include <CGAL/Exact_integer.h>
#include <CGAL/Extended_homogeneous.h>
#include <CGAL/Nef_polyhedron_3.h>

typedef CGAL::Exact_integer  NT;
typedef CGAL::Extended_homogeneous<NT>  Kernel;
typedef CGAL::Nef_polyhedron_3<Kernel>  Nef_polyhedron;
typedef Kernel::Plane_3 Plane_3;
int main() {

  Nef_polyhedron N1(Plane_3(2,5,7,11), Nef_polyhedron::INCLUDED);
  Nef_polyhedron N2(Plane_3(-2,-5,-7,-10), Nef_polyhedron::INCLUDED);

  CGAL_assertion(!(N1 >= N2));
  CGAL_assertion(!(N2 <= N1));
  CGAL_assertion(N1 != N2);
  CGAL_assertion(!(N2 < N1));
  CGAL_assertion(!(N1 > N2));  // fails

  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux x64
* Compiler: GCC
* Release or debug mode: Debug
* Specific flags used (if any): /
* CGAL version: master
* Boost version: Boost-1.71.0  
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Fix a reported issue.

## Release Management

* Affected package(s): Nef_3
* Issue(s) solved (if any): fix #6151
* License and copyright ownership: unchanged

### CODE REVIEW

File: Nef_3/test/Nef_3/test_nef_3_operator.cpp [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+
+#include <iostream>
+typedef CGAL::Exact_predicates_exact_constructions_kernel K;
+typedef K::Point_3 Point_3;
+typedef CGAL::Surface_mesh<K::Point_3> Polygon_mesh;
+
+typedef CGAL::Nef_polyhedron_3<K> Nef_polyhedron;
+
+int main(int argc, char* argv[])
```
Comment (sloriot) [inline Nef_3/test/Nef_3/test_nef_3_operator.cpp:14]:
```suggestion
int main()
```

File: Nef_3/test/Nef_3/test_nef_3_operator.cpp [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+{
+  Point_3 p0(1,1,1), p1(2,1,1), p2(2,2,1), p3(1,2,1), p4(1,2,2), p5(1,1,2), p6(2,1,2), p7(2,2,2);
+  Point_3 q0(0,0,0), q1(3,0,0), q2(3,3,0), q3(0,3,0), q4(0,3,3), q5(0,0,3), q6(3,0,3), q7(3,3,3);
+
+    Polygon_mesh A1, A2, A3, A4, A5, A6;
```
Comment (sloriot) [inline Nef_3/test/Nef_3/test_nef_3_operator.cpp:19]:
```suggestion
    Polygon_mesh A1, A2;
```

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-106.
The new warnings were in the new test file. I locally check that I have them and that the latest commits fix them.
