### PR TITLE
Gsoc2025 aos demo shepard

### LINKED ISSUE #8902: 2D Rendering Fails
## Issue Details

2D rendering, such as rendering of 2D arrangements fails since switch to using shaders to draw edges and vertices (contrary to using old opengl lines and points). For 2D arrangements the switch was applied in commit c6c9f77ae466eaca252184db39326d62649cee68.
The rendering of edges and vertices in 2D should not depend on the workspace, The radius of a point and the width of a line should be specified in window coordinates and should be consistent across all drawings.

I assume that it relates to the general issue of mapping 1 unit in window space (that is 1 pixel) to world space. This is needed for other purposes as well, such as approximating non-linear curves using polylines. In this case, the maximum distance between the approximated polyline and the original curve should be specified in window coordinates (e.f., 1 pixel).

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: since commit commit c6c9f77ae466eaca252184db39326d62649cee68
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by efifogel**
## Summary of Changes

1. Fixed the drawing of arrangements on the plane induced by segments, circular arcs, and conics
2. Developed the code necessary to draw arrangements on the plane induced by unbounded curves and enabled the drawing of arrangement instantiated with `Arr_linear_traits_2`.
3. Developed the code necessary to draw arrangements on the sphere induced by geodesic arcs

This pull request depends on the small feature [Aos2 Unbounded Drawing](https://cgalwiki.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Aos2 Unbounded Drawing), which is associated with PR #9036, which consists of the API changes required to support the drawing of arrangements induced by unbounded curves. 

Observe that #9036 must be integrated before this one is integrated.

## Release Management

* Affected package(s): Arrangement_on_surface_2
* Issue(s) solved (if any): Partially fixes #8902, which I believe is a show-stopper. (The fix only applies to 2D arrangements.)
* Feature/Small Feature (if any): this PR depends on the small feature [Aos2 Unbounded Drawing](https://cgalwiki.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Aos2 Unbounded Drawing)
* License and copyright ownership: TAU

### CODE REVIEW

**Comment by sloriot** [comment]
Warnings and errors in CGAL-6.2-Ic-21

You should also merge `main` to the branch to resolve conflicts

**Comment by efifogel** [comment]
ok, I will
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Can you please fix the conflict with main?

**Comment by efifogel** [comment]
Yes, I'm working on it.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
I'm done.
I hope that I caught all errors and warnings.
The branch is ready for integration.

Observe that this PR subsumes #9036 <https://github.com/CGAL/cgal/pull/9036>
.
First, I merged the main branch with #9036
<https://github.com/CGAL/cgal/pull/9036> (Aos 2 approximate unbounded).
Second, I merged #9036 <https://github.com/CGAL/cgal/pull/9036> with this
one.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Warnings in CGAL-6.2-Ic-26

**Comment by efifogel** [comment]
One of the issues triggered my attention, and it turned out to be related
to a larger issue.
I've decided to fix it in this branch.
Shepard, the GSoC who developed this feature, agreed to fix it.
It will take (him) a few more days.

While Shepard was working on this, he stumbled on the cause of the
exaggerated segment width drawn by Basic_viewer:

He says, and I quote:
The issue lies with the line m_size_edges=d in
Basic_viewer::initialize_vertices_and_edges_size(). It should be set to
m_size_edges=1. The geometry shaders are already designed to map screen
space size to world coordinates, making the initialization of the edge size
based on the scene bounding box redundant and often problematic.
Perhaps while Shpard is working on the fix above, someone can look into
this easy fix to the segment width problem.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

File: Arrangement_on_surface_2/examples/Arrangement_on_surface_2/draw_arr.cpp [hunk 1]
```diff
@@ -75,49 +74,175 @@ hsv_to_rgb(float hue, float sat, float value) {
...
+      gso;
+  gso.colored_face = [](const Arrangement&, Arrangement::Face_const_handle) -> bool { return true; };
 
- CGAL::Graphics_scene_options<Arrangement_2,
-                              typename Arrangement_2::Vertex_const_handle,
-                              typename Arrangement_2::Halfedge_const_handle,
-                              typename Arrangement_2::Face_const_handle> gso;
- gso.colored_face=[](const Arrangement_2&, Arrangement_2::Face_const_handle) -> bool
- { return true; };
+  gso.face_color = [](const Arrangement& arr, Arrangement::Face_const_handle fh) -> CGAL::IO::Color {
```
Comment (sloriot) [inline Arrangement_on_surface_2/examples/Arrangement_on_surface_2/draw_arr.cpp]: `arr` is not used --> warning

**Comment by efifogel** [comment]
I think that I fixed the last error. (I couldn't verify it, because the failure occurs only with clang 12, which I don't have access to.)
I've decided to postpone all other changes (and apply them in a different branch as part of a separate feature).
This implies that the PR is ready again for final testing and integration.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.2-Ic-30

File: Installation/CHANGES.md [hunk 2]
```diff
@@ -73,6 +58,71 @@ Release date: Sept 2025
...
+-   Added a new named parameter for `CGAL::Subdivision_method_3::Loop_subdivision()` and
+    `CGAL::Subdivision_method_3::CatmullClark_subdivision()`, which enables users to subdivide
+    a mesh without modifying its geometry.
+
+### [2D Triangulations](https://doc.cgal.org/6.1/Manual/packages.html#PkgTriangulation2)
+
+-  **Breaking change**: In the class template `Constrained_triangulation_plus_2`, the value type of the range returned
+   by `subconstraints()` has changed from `const std::pair<const Subconstraint, std::list<Context>*>` to `Subconstraint`.
+   The old range type is now returned by a new function named `subconstraints_and_contexts()`.
+
```
Comment (lrineau) [inline Installation/CHANGES.md:125]: That change of `CHANGES.md` has been merged into `main`, and it now had duplicated sections.
