### PR TITLE
IO: write_PLY() for Epeck

### LINKED ISSUE #7327: Writing a binary PLY file does not work with an EPECK mesh
Hello,

I solved my problem by using EPICK instead of EPECK. See [here](https://stackoverflow.com/q/75208029/1100107) and [here](https://github.com/CGAL/cgal/discussions/7179).

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

As reported in #7868 the function `CGAL::IO::write_PLY()`  used in binary mode does not correctly write the coordinates if the points are from a kernel with exact constructions.   
~~This PR applies `to_double()" to the coordinates.~~

~~After a discussion with @MaelRL we decided that the user is in charge to pass a `vertex_point_map`  as named parameter that does the conversion. This is straightforward as we offer the [`Cartesian_converter_property_map`](https://doc.cgal.org/latest/Property_map/structCGAL_1_1Cartesian__converter__property__map.html).~~

Moving back to the previous proposal: hardcode some to_double and to_float casts such that we meet the requirements of the file format, whatever the input.

As the problem is the same for the vertex normals we add a named parameter `vertex_normal_map`.

### Todo
- [x] Fix the generic function `write_polygon_mesh()`. Currently it is fixed for `Surface_mesh`

## Release Management

* Affected package(s): Stream_support
* Issue(s) solved (if any): fix #7868 and fix https://github.com/CGAL/cgal/issues/7327
* License and copyright ownership:  unchanged
* upcoming integration, update #9072 and test it

### CODE REVIEW

**Comment by sloriot** [comment]
BGL tests failing in CGAL-6.0-Ic-112

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-116

**Comment by afabri** [comment]
> @afabri There is still an undone TODO in the top message of this other PR. Do you want this PR merged as it is?

No, I still want to fix the generic code.

**Comment by sloriot** [comment]
@afabri any chance you can fix that today (if inclusion in 5.6.1 is needed)?

**Comment by sloriot** [comment]
@afabri, this PR was marqued tested 2 month ago and is still waiting for a TODO. Maybe you want to open an issue instead and integrate the PR.

**Comment by lrineau** [comment]
Ping @afabri

**Comment by MaelRL** [comment]
Note that https://github.com/CGAL/cgal/commit/6096748402d738f311d960189944918aaf6e4b56#diff-7a13764173912394a4970cfc328f818e714d19b9ac486d1ded974155934cdc8fR59 goes in the other direction from the current conclusion (users must give a VPM that converts to `double`), so this will need more discussions.

File: BGL/include/CGAL/boost/graph/IO/PLY.h [hunk 1]
```diff
@@ -153,6 +174,7 @@ bool read_PLY(std::istream& is,
 
   \param fname the name of the input file
   \param g the graph to be built from the input data
+  \param comments a string included line by line in the header of the PLY stream (each line will be precedeed by "comment
```
Comment (MaelRL) [inline BGL/include/CGAL/boost/graph/IO/PLY.h]:
```suggestion
  \param comments a string included line by line in the header of the PLY stream (each line will be precedeed by "comment "
```

File: BGL/include/CGAL/boost/graph/IO/PLY.h [hunk 2]
```diff
@@ -138,9 +156,12 @@ bool read_PLY(std::istream& is,
 #endif
               )
 {
-  return internal::read_PLY_BGL(is, g, np);
+  std::string unused_comments;
+  return internal::read_PLY_BGL(is, g, unused_comments, np);
 }
 
+
+
```
Comment (MaelRL) [inline BGL/include/CGAL/boost/graph/IO/PLY.h]:
```suggestion
```

File: BGL/include/CGAL/boost/graph/IO/PLY.h [hunk 3]
```diff
@@ -288,6 +333,10 @@ bool read_PLY(const std::string& fname,
     \cgalParamNEnd
  \cgalNamedParamsEnd
 
+\note The point and vector types of the point and normal property map must be `double`or `float`
+      in order to respect the specification of the  PLY file format.
+       A `Cartesian_converter_property_map` can be used to convert the points and vectors on the fly.
```
Comment (MaelRL) [inline BGL/include/CGAL/boost/graph/IO/PLY.h]: obsolete (see other places too)

File: BGL/include/CGAL/boost/graph/IO/PLY.h [hunk 4]
```diff
@@ -259,6 +295,15 @@ bool read_PLY(const std::string& fname,
                       must be available in `Graph`.}
     \cgalParamNEnd
 
+   \cgalParamNBegin{vertex_normal_map}
+      \cgalParamDescription{a property map associating normals to the vertices of `g`}
+      \cgalParamType{a class model of `ReadablePropertyMap` with `boost::graph_traits<Graph>::%vertex_descriptor`
+                     as key type and `%Vector_3` as value type}
+      \cgalParamDefault{`boost::get(CGAL::vertex_point, g)`}
+      \cgalParamExtra{If this parameter is omitted, an internal property map for `CGAL::vertex_point_t`
+                      must be available in `Graph`.}
```
Comment (MaelRL) [inline BGL/include/CGAL/boost/graph/IO/PLY.h:304]: Default and Extra are for VPMs (see other places too)

File: BGL/include/CGAL/boost/graph/IO/PLY.h [hunk 5]
```diff
@@ -379,7 +454,15 @@ bool write_PLY(std::ostream& os,
...
-    internal::output_properties(os, &p, make_ply_point_writer (CGAL::Identity_property_map<Point_3>()));
+    internal::output_properties(os, &p, make_ply_point_writer (Identity_property_map<Point_3>()));
+    if constexpr (!parameters::is_default_parameter<CGAL_NP_CLASS, internal_np::vertex_normal_map_t>::value)
+  {
+    auto vnm = get_parameter(np, internal_np::vertex_normal_map);
+    typedef decltype(vnm) Normal_map;
+    typedef typename Normal_map::value_type Vector_3;
+    Vector_3 vec = get(vnm,vd);
+    internal::output_properties(os, &vec, make_ply_normal_writer (Identity_property_map<Vector_3>()));
+  }
```
Comment (MaelRL) [inline BGL/include/CGAL/boost/graph/IO/PLY.h]: indentation

File: BGL/include/CGAL/boost/graph/IO/PLY.h [hunk 6]
```diff
@@ -326,6 +375,11 @@ bool write_PLY(std::ostream& os,
 
   bool has_vcolor = !is_default_parameter<CGAL_NP_CLASS, internal_np::vertex_color_map_t>::value;
   bool has_fcolor = !is_default_parameter<CGAL_NP_CLASS, internal_np::face_color_map_t>::value;
+  bool has_vnormal = false;
+  if constexpr (!parameters::is_default_parameter<CGAL_NP_CLASS, internal_np::vertex_normal_map_t>::value)
+  {
+    has_vnormal = true;
+  }
```
Comment (MaelRL) [inline BGL/include/CGAL/boost/graph/IO/PLY.h]: copy the style of the other Boolean definitions?

File: BGL/include/CGAL/boost/graph/IO/PLY.h [hunk 7]
```diff
@@ -379,7 +454,15 @@ bool write_PLY(std::ostream& os,
...
     const Point_3& p = get(vpm, vd);
-    internal::output_properties(os, &p, make_ply_point_writer (CGAL::Identity_property_map<Point_3>()));
+    internal::output_properties(os, &p, make_ply_point_writer (Identity_property_map<Point_3>()));
+    if constexpr (!parameters::is_default_parameter<CGAL_NP_CLASS, internal_np::vertex_normal_map_t>::value)
+  {
+    auto vnm = get_parameter(np, internal_np::vertex_normal_map);
+    typedef decltype(vnm) Normal_map;
+    typedef typename Normal_map::value_type Vector_3;
+    Vector_3 vec = get(vnm,vd);
+    internal::output_properties(os, &vec, make_ply_normal_writer (Identity_property_map<Vector_3>()));
```
Comment (MaelRL) [inline BGL/include/CGAL/boost/graph/IO/PLY.h]: This should wrap with a Cartesian converter, then?

File: Stream_support/include/CGAL/IO/PLY/PLY_writer.h [hunk 8]
```diff
@@ -253,6 +254,7 @@ class Property_printer
   }
 };
 
+
```
Comment (MaelRL) [inline Stream_support/include/CGAL/IO/PLY/PLY_writer.h]:
```suggestion
```

File: Stream_support/include/CGAL/IO/STL.h [hunk 9]
```diff
@@ -317,7 +317,7 @@ bool write_STL(std::ostream& os,
       const Point& q = get(point_map, points[face[1]]);
       const Point& r = get(point_map, points[face[2]]);
 
-      const Vector_3 n = collinear(p,q,r) ? Vector_3(1,0,0) : unit_normal(p,q,r);
+      const Vector_3 n = internal::construct_normal_of_STL_face(p, q, r, k);
```
Comment (MaelRL) [inline Stream_support/include/CGAL/IO/STL.h:320]: read_STL as well as other writers need the Cartesian converter mechanisms with SC<float> everywhere, then. This only compiles with EPECK because `<< EPECK::Point_3` casts to `double`.

File: Stream_support/test/Stream_support/issue_7874.cpp [hunk 10]
```diff
@@ -0,0 +1,154 @@
+#include <CGAL/Surface_mesh.h>
+#include <CGAL/Polyhedron_3.h>
+#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
```
Comment (MaelRL) [inline Stream_support/test/Stream_support/issue_7874.cpp:4]: I'd not use EPECK such that there is no accident casting to doubles.

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 11]
```diff
@@ -420,44 +421,76 @@ class Surface_mesh_filler
...
 bool fill_simplex_specific_header(std::ostream& os,
                                   const Surface_mesh<Point>& sm,
                                   std::vector<Abstract_property_printer<
                                     typename Surface_mesh<Point>::Vertex_index>*>& printers,
-                                  const std::string& prop)
+                                  const std::string& prop,
+                                  const NamedParameter& np)
 {
+  using CGAL::parameters::choose_parameter;
+  using CGAL::parameters::get_parameter;
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h:433]:
```suggestion
  using CGAL::parameters::get_parameter;

```

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 12]
```diff
@@ -420,44 +421,76 @@ class Surface_mesh_filler
...
   typedef Surface_mesh<Point>                                     SMesh;
   typedef typename SMesh::Vertex_index                            VIndex;
   typedef typename Kernel_traits<Point>::Kernel                   Kernel;
   typedef typename Kernel::FT                                     FT;
   typedef typename Kernel::Vector_3                               Vector;
-  typedef typename SMesh::template Property_map<VIndex, Point>    Point_map;
+
+  typedef typename GetVertexPointMap<Surface_mesh<Point>, NamedParameter>::const_type Point_map;
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]:
```suggestion
  typedef typename GetVertexPointMap<SMesh, NamedParameter>::const_type Point_map;
```

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 13]
```diff
@@ -467,14 +500,17 @@ bool fill_simplex_specific_header(std::ostream& os,
...
       else
       {
         os << "property double nx" << std::endl
            << "property double ny" << std::endl
            << "property double nz" << std::endl;
+        auto fvnm = CGAL::make_cartesian_converter_property_map<Epick::Vector_3>(*pmap);
+        printers.push_back(new Property_printer<VIndex, decltype(fvnm)>(fvnm));
       }
-      printers.push_back(new Property_printer<VIndex, Vector_map>(*pmap));
+      // printers.push_back(new Property_printer<VIndex, Vector_map>(*pmap));
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]:
```suggestion
```

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 14]
```diff
@@ -420,44 +421,76 @@ class Surface_mesh_filler
...
+      os << "property float nx" << std::endl
+          << "property float ny" << std::endl
+          << "property float nz" << std::endl;
+      printers.push_back(new Property_printer<VIndex, Normal_map>(vnm));
+    }
+    else
+    {
+      os << "property double nx" << std::endl
+          << "property double ny" << std::endl
+          << "property double nz" << std::endl;
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]:
```suggestion
      os << "property double nx" << std::endl
         << "property double ny" << std::endl
         << "property double nz" << std::endl;
```

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 15]
```diff
@@ -420,44 +421,76 @@ class Surface_mesh_filler
...
+  if constexpr (!parameters::is_default_parameter<NamedParameter, internal_np::vertex_normal_map_t>::value)
+  {
+    auto vnm = get_parameter(np, internal_np::vertex_normal_map);
+    typedef decltype(vnm) Normal_map;
+    typedef typename Kernel_traits<typename Normal_map::value_type>::Kernel::FT FloatDouble;
+    if constexpr (std::is_same<FloatDouble, float>::value)
+    {
+      os << "property float nx" << std::endl
+          << "property float ny" << std::endl
+          << "property float nz" << std::endl;
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]:
```suggestion
      os << "property float nx" << std::endl
         << "property float ny" << std::endl
         << "property float nz" << std::endl;
```

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 16]
```diff
@@ -773,21 +812,28 @@ void fill_header(std::ostream& os, const Surface_mesh<Point>& sm,
 /// \param comments a string used to store the potential comments found in the PLY header.
 ///        Each line starting by "comment " in the header is appended to the `comments` string
 ///        (without the "comment " word).
-/// \param verbose whether extra information is printed when an incident occurs during reading
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h:776]: The NP should be documented?

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 17]
```diff
@@ -874,6 +920,18 @@ bool read_PLY(std::istream& is,
 
 /// \cond SKIP_IN_MANUAL
 
+#if 0
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]: todo

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 18]
```diff
@@ -927,6 +985,8 @@ namespace IO {
 /// \cgalNamedParamsEnd
 ///
 /// \returns `true` if writing was successful, `false` otherwise.
+
+
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]:
```suggestion
```

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h [hunk 19]
```diff
@@ -939,7 +999,6 @@ bool write_PLY(std::ostream& os,
   typedef typename SMesh::Face_index FIndex;
   typedef typename SMesh::Edge_index EIndex;
   typedef typename SMesh::Halfedge_index HIndex;
-
   if(!os.good())
```
Comment (MaelRL) [inline Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h:1011]:
```suggestion

  if(!os.good())
```

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h (hunk 16 above)
Comment (afabri) [reply Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h:776]: We just discussed that it will not be documented.

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h (hunk 17 above)
Comment (afabri) [reply Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]: It leads to an ambiguity with the overload with the named parameter.

Comment (MaelRL) [reply Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]: The NP macros do not remove the ambiguity?

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h (hunk 16 above)
Comment (MaelRL) [reply Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h:776]: For the extra maps, sure: but you're removing a documented `verbose` parameter, its new equivalent should be documented

Comment (afabri) [reply Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h:776]: You mean documenting the named parameter `verbose`. right.

Comment (sloriot) [reply Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h:776]: @afabri please undo

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h (hunk 17 above)
Comment (sloriot) [reply Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h]: surprising as it is strongly typed

**Comment by sloriot** [comment]
@afabri please resolve all conversations

File: Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h (hunk 16 above)
Comment (afabri) [reply Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h:776]: I'ts back in line 817 .,

File: Stream_support/test/Stream_support/issue_7874.cpp (hunk 10 above)
Comment (afabri) [reply Stream_support/test/Stream_support/issue_7874.cpp:4]: I do not understand what you want to say. Epeck had a problem when writing binary mode.

File: Stream_support/include/CGAL/IO/STL.h (hunk 9 above)
Comment (afabri) [reply Stream_support/include/CGAL/IO/STL.h:320]: That is dealt with in the other pull request about IO and binary for Epeck. See [here](https://github.com/CGAL/cgal/pull/9072/files#diff-0fc69b13e0465b6be76d73055c6136ff40d9dc9f9dc106eecae3370ce999f9f8)

File: Stream_support/test/Stream_support/issue_7874.cpp (hunk 10 above)
Comment (MaelRL) [reply Stream_support/test/Stream_support/issue_7874.cpp:4]: EPECK's `operator<<` already has a `to_double` cast so whether the IO functions properly apply that cast is not checkable. Thus, we could use a Simple_cartesian<Exact_rational> to check that the output has properly been converted to double via the operators in the IO functions.

Comment (afabri) [reply Stream_support/test/Stream_support/issue_7874.cpp:4]: changed to `Simple_cartesian<Exact_rational>`

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.2-Ic-39
