### PR TITLE
Heat_method_3 - avoid degenerate faces

### LINKED ISSUE #5010: Infinite loop when building intrinsic Delaunay triangulation in Heat_method_3
## Issue Details

Using the `Heat_method_3` package in `Intrinsic_Delaunay` mode with a mesh containing degenerate triangles will cause the algorithm to get stuck in an infinite loop.

The responsible loop can be found in [internal/Intrinsic_Delaunay_triangulation_3.h:293](https://github.com/CGAL/cgal/blob/cd7907194fcbaba9e85e3e2333697477a5eea650/Heat_method_3/include/CGAL/Heat_method_3/internal/Intrinsic_Delaunay_triangulation_3.h#L293). When flipping edges to build the Delaunay triangulation, the algorithm will try to add/remove the same cycle of edges to the stack indefinitely. (On the line just above there is also a `int a = 0;` declaration which serves no purpose).

This infinite loop is in turn caused by a division by zero when computing cotangents in [internal/Intrinsic_Delaunay_triangulation_3.h:226](https://github.com/CGAL/cgal/blob/cd7907194fcbaba9e85e3e2333697477a5eea650/Heat_method_3/include/CGAL/Heat_method_3/internal/Intrinsic_Delaunay_triangulation_3.h#L226). When encountering a degenerate triangle of the "needle" kind (having two vertices with identical positions), a `NaN` value will be produced, causing the `is_edge_locally_delaunay` function to return `false`, and finally the `loop_over_edges` to goes on forever.

(If the algorithm instead encounters a degenerate triangle of the "cap" kind, with 3 collinear but distinct points, then an `inf` value will be produced, the loop will terminate, and you will get a `Eigen Decomposition in cotan failed` assertion exception later on in the linear solver.)

The `Heat_method_3` package make some common assumptions on the input mesh (such as it being a triangle mesh, etc) so it might be expected that it will fail if you feed it a mesh containing degeneracies, but as there is no assertions checking for that the software will just silently freeze at some point. I believe that degeneracies might also be created during the edge flipping phase due to floating-point rounding errors (this package only works with `double` data type so we can't use exact arithmetic there).  

See [the original paper describing the heat method](https://www.cs.cmu.edu/~kmcrane/Projects/HeatMethod/index.html) for additional details on this algorithm.

## Source Code

Minimal example :

```cpp
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh/Surface_mesh.h>
#include <CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h>

int main(int argc, char* argv[]) {

    using namespace CGAL;
    using Kernel = Exact_predicates_inexact_constructions_kernel;
    using Mesh = Surface_mesh<Kernel::Point_3>;

    Mesh mesh;
    Mesh::Vertex_index v1 = mesh.add_vertex( Mesh::Point(0, 0, 0) );
    Mesh::Vertex_index v2 = mesh.add_vertex( Mesh::Point(0, 0, 0) );
    Mesh::Vertex_index v3 = mesh.add_vertex( Mesh::Point(1, 0, 0) );
    Mesh::Vertex_index v4 = mesh.add_vertex( Mesh::Point(0, 1, 0) );
    mesh.add_face(v1, v2, v4);
    mesh.add_face(v2, v3, v4);
    mesh.add_face(v1, v3, v2);

    Mesh::Property_map<Mesh::Vertex_index, double> dmap
        = mesh.add_property_map<Mesh::Vertex_index, double>("v:dist").first;

    using Mode = Heat_method_3::Intrinsic_Delaunay;
    Heat_method_3::Surface_mesh_geodesic_distances_3<Mesh, Mode> heat(mesh);
    heat.add_source(v1);
    heat.estimate_geodesic_distances(dmap);

    return EXIT_SUCCESS; // this will never happen
}
```

## Suggestions

I didn't submit a pull request for this issue because I am not sure of the preferred way to fix it. Below are some suggestions.

* Simply add an assertion checking for degeneracies and/or divisions by zero, so at least the algorithm will terminate.
* Catch `NaN` values and replace them by something sane which will produce the expected behaviour from the algorithm (if that's possible).
* Detect degenerate triangles and remove them from the intrinsic Delaunay triangulation, for example by using the `remove_degenerate_faces` function (but see also [this related issue](https://github.com/CGAL/cgal/pull/5001)).
* Introduce some small random pertubation to remove degeneracies (after all the heat method is already a non-exact method for computing distances).
* Improve the `Heat_method_3` package by implementing the method described in [this recent paper by the same author](https://www.cs.cmu.edu/~kmcrane/Projects/NonmanifoldLaplace/index.html) which I believe could solve this and other issues related to non-manifold meshes (but that would require much more work).

## Environment

* Operating system: Linux 5.8.10 x86_64
* Compiler: gcc 10.2.0
* Release or debug mode: both
* CGAL version: master/5.1
* Boost version: 1.72.0
* Eigen version: 3.3.7

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

Degenerate faces in the input triangle mesh cause an infinite loop in `loop_over_edges()`.
This PR adds a precondition to avoid degenerate faces in input.

## Release Management

* Affected package(s): Heat_method_3
* Issue(s) solved (if any): fix #5010 
* License and copyright ownership: unchanged

### CODE REVIEW

File: Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h [hunk 1]
```diff
@@ -743,7 +770,7 @@ struct Base_helper<TriangleMesh, Traits, Intrinsic_Delaunay, LA, VertexPointMap>
  *         is used as default
  * \tparam Traits a model of `HeatMethodTraits_3`. The default is the Kernel of the value type
  *         of the vertex point map (extracted using `Kernel_traits`).
- *
+ * \pre
```
Comment (lrineau) [inline Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h:773]: Empty `\pre`?

Comment (janetournois) [reply Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h:773]: forgotten extra `\pre`...
I remove it

**Comment by oboes** [comment]
See also [PR #5037](https://github.com/CGAL/cgal/pull/5037) for an alternative possible solution to the same issue.

**Comment by maxGimeno** [comment]
[34m[1mCheck header Shape_detection/include/CGAL/Shape_detection/Region_growing/Region_growing_on_polygon_mesh/Least_squares_plane_fit_region.h[0m
/home/travis/build/CGAL/cgal/Installation/../Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h:483:24: error: no member named 'has_degenerate_faces' in namespace 'CGAL::Heat_method_3::internal'; did you mean 'Polygon_mesh_processing::degenerate_faces'?
    CGAL_precondition(!internal::has_degenerate_faces(triangle_mesh(), vertex_point_map()));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       Polygon_mesh_processing::degenerate_faces
/home/travis/build/CGAL/cgal/STL_Extension/include/CGAL/assertions.h:196:20: note: expanded from macro 'CGAL_precondition'
   (CGAL::possibly(EX)?(static_cast<void>(0)): ::CGAL::precondition_fail( # EX , __FILE__, __LINE__))
                   ^~
/home/travis/build/CGAL/cgal/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/shape_predicates.h:270:16: note: 'Polygon_mesh_processing::degenerate_faces' declared here
OutputIterator degenerate_faces(const FaceRange& faces,
               ^
1 error generated.
CMake Error at /home/travis/build/CGAL/cgal/Installation/cmake/modules/run_cmd_redirection_cerr.cmake:32 (message):


Installation/CMakeFiles/check_pkg_Heat_method_3_headers.dir/build.make:61: recipe for target 'package_info/Heat_method_3/check_headers/check_CGAL__Heat_method_3__Surface_mesh_geodesic_distances_3_h' failed
make[3]: *** [package_info/Heat_method_3/check_headers/check_CGAL__Heat_method_3__Surface_mesh_geodesic_distances_3_h] Error 1
make[3]: Target 'Installation/CMakeFiles/check_pkg_Heat_method_3_headers.dir/build' not remade because of errors.
CMakeFiles/Makefile2:2256: recipe for target 'Installation/CMakeFiles/check_pkg_Heat_method_3_headers.dir/all' failed
make[2]: *** [Installation/CMakeFiles/check_pkg_Heat_method_3_headers.dir/all] Error 2
[35m[1mScanning dependencies of target check_pkg_Generator_headers[0m

**Comment by maxGimeno** [comment]
The error is still there : https://travis-ci.com/github/CGAL/cgal/jobs/402409362#L7259

**Comment by maxGimeno** [comment]
ping @janetournois

File: Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h [hunk 2]
```diff
@@ -480,7 +480,8 @@ class Surface_mesh_geodesic_distances_3
   template<class VertexDistanceMap>
   void estimate_geodesic_distances(VertexDistanceMap vdm)
   {
-    CGAL_precondition(!internal::has_degenerate_faces(triangle_mesh(), vertex_point_map()));
+    CGAL_precondition(
+      !CGAL::Heat_method_3::internal::has_degenerate_faces(triangle_mesh(), vertex_point_map()));
```
Comment (lrineau) [inline Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h:484]: The error reported by Travis was:
```
 /home/travis/build/CGAL/cgal/Installation/../Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h:483:24: error: no member named 'has_degenerate_faces' in namespace 'CGAL::Heat_method_3::internal'; did you mean 'Polygon_mesh_processing::degenerate_faces'?
CGAL_precondition(!internal::has_degenerate_faces(triangle_mesh(), vertex_point_map()));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

That patch will not change anything: the compiler does not see the declaration of `CGAL::Heat_method_3::internal::has_degenerate_faces` because it is declared *after* in the same file.

You can either move the declaration/definition, or forward-declare it.

**Comment by maxGimeno** [comment]
Errors : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-36.shtml#Heat_method_3

**Comment by maxGimeno** [comment]
@janetournois this won't get into 5.2, it's too late now

**Comment by lrineau** [comment]
As a bug-fix, this PR can be integrated after CGAL-5.2-beta, before the final release.

**Comment by maxGimeno** [comment]
...if it is ready then.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-50.shtml
