### PR TITLE
[isotropic_remeshing] do no flip if creating a degenerate face

### LINKED ISSUE #8412: The program occasionally experiences an infinite loop exception when performing remeshing.
_Please use the following template to help us solving your issue._

## Issue Details

I occasionally encounter an infinite loop issue when using Remeshing, and upon investigation, I found that the fix_degenerate_faces function has design flaws. There are two problems with this function: 1. Previously processed degenerate faces are processed repeatedly (because the face becomes degenerate again when processing other degenerate faces); 2. It doesn't avoid introducing new degenerate faces while fixing degenerate faces. On my own computer, I can temporarily avoid the program falling into an infinite loop by recording the processed degenerate faces. Below is my local solution code (with 3 new lines added) for reference only.

```
template<typename Bimap>
bool fix_degenerate_faces(const vertex_descriptor& v,
						  Bimap& short_edges,
						  const double& sq_low,
						  const bool collapse_constraints)
{
  std::unordered_set<halfedge_descriptor> degenerate_faces;
  std::unordered_set<halfedge_descriptor> visited_faces;// my code
  for(halfedge_descriptor h :
	  halfedges_around_target(halfedge(v, mesh_), mesh_))
  {
	if(!is_border(h, mesh_) &&
	   is_degenerate_triangle_face(face(h, mesh_), mesh_,
								   parameters::vertex_point_map(vpmap_)
											   .geom_traits(gt_)))
	  degenerate_faces.insert(h);
  }

  if(degenerate_faces.empty())
	return true;

  bool done = false;
  while(!degenerate_faces.empty())
  {
	
	halfedge_descriptor h = *(degenerate_faces.begin());
	degenerate_faces.erase(degenerate_faces.begin());
	if (visited_faces.contains(h)) continue;// my code
	visited_faces.insert(h);// my code
	// ...
  }
#ifdef CGAL_PMP_REMESHING_DEBUG
  debug_status_map();
#endif
  return done;
}
```

## Source Code

```
// at line 1686 of file include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
template<typename Bimap, typename SizingFunction>
bool fix_degenerate_faces(const vertex_descriptor& v,
                                           Bimap& short_edges,
                                           const SizingFunction& sizing,
                                           const bool collapse_constraints)；
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux, 64 bits
* Compiler: CLang 18.1.3 x86_64-pc-linux-gnu
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: CGAL_VERSION 5.6
* Boost version: BOOST_VERSION 108300
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by sloriot**
Should fix #8412

### CODE REVIEW

File: Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h [hunk 1]
```diff
@@ -1704,28 +1704,21 @@ namespace internal {
...
-        if (!is_degenerate_triangle_face(face(h, mesh_), mesh_,
-                                         parameters::vertex_point_map(vpmap_)
-                                                    .geom_traits(gt_)))
-          //this can happen when flipping h has consequences further in the mesh
-          continue;
-
-        //check that opposite is not also degenerate
-        degenerate_faces.erase(opposite(h, mesh_));
-
         if(is_border(h, mesh_))
```
Comment (sloriot) [inline Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h:1713]: @janetournois  in such a case, you can simply remove the face. Basically the opposite of [`add_face_to_border()`](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#ga8666be89a7ffa73a5fe82b6b2bdc6f19)

Comment (sloriot) [reply Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h:1713]: `Euler::remove_face()` should be safe (could be a face with 2 border halfedges)

**Review by janetournois — APPROVED** [review]

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-318
