### PR TITLE
Polyhedron Demo: Fix View Menu

### LINKED ISSUE #4070: Polyhedron demo: regressions in the View menu
## Issue Details

The menu View of the 3D demo:
- In CGAL-4.14:
Screenshot_20190709_144359
- In CGAL-5.0-dev:
Screenshot_20190709_144424

Issues:
- Draw Two Sides has lost its shortcut <kbd>Ctrl+T</kbd>
- The mnemonic <kbd>Alt+M</kbd> is lost for Camera
- Recenter scene is present twice.
- "Organize viewer" should be renamed "Rearrange viewers", and be hidden when there is only one viewer that is fullscreen.
- Set the mnemonic of Quick Camera Mode on the `Q`,
- Set the mnemonic of Orthographic Projection on the `O`.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

- [x] Draw Two Sides has lost its shortcut Ctrl+T
- [x] The mnemonic Alt+M is lost for Camera
- [x] Recenter scene is present twice.
- [x] "Organize viewer" should be renamed "Rearrange viewers", and be hidden when there is only one viewer that is fullscreen.
- [x] Set the mnemonic of Quick Camera Mode on the Q,
- [x] Set the mnemonic of Orthographic Projection on the O.
## Release Management
* Issue(s) solved (if any): fix #4070

### CODE REVIEW

File: Polyhedron/demo/Polyhedron/MainWindow.cpp [hunk 1]
```diff
@@ -183,7 +183,15 @@ MainWindow::MainWindow(const QStringList &keywords, bool verbose, QWidget* paren
...
-
+    shortcut = new QShortcut(QKeySequence(Qt::CTRL+Qt::Key_T), this);
+    connect(shortcut, &QShortcut::activated,
+            this,
+            [this](){
+      Viewer* viewer = qobject_cast<Viewer*>(CGAL::Three::Three::activeViewer());
+      bool b = viewer->property("draw_two_sides").toBool();
+      viewer->setTwoSides(!b);
+    }
+            );
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/MainWindow.cpp]: There might be a warning because it seems the capture of `this` is not used.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-87.shtml
