### PR TITLE
Check that the input can be read in the Mesh_3 examples

### LINKED ISSUE #800: Package Mesh_3 / example mesh_polyhedral_domain / precondition violation error in AABB_tree.h
Dear all,
I just install CGAL and try a few examples of my package of interest: 3D mesh generation (mesh_3).
All examples worked except mesh_polyhedral_domain and mesh_polyhedral_domain_with_features. When I launch the exe file via command prompt I have the following error:

CGAL error: precondition violation!
Expression : !empty()
File : C:\dev\CGAL-4.7\include\CGAL/AABB_tree.h
Line : 223
Explanation:
Refer to the bug-reporting intructions at http://www.cgal.org/bug_report.html

I look at other bug reports on this website and on stackoverflow but I didn't find any answer for my problem.

I use Visual C++ express 2010: the compilation of the example was performed both in debug and release with no displayed errors.

I don't know if I had to had all my installation procedure for CGAL, if you need it or any kinds of  informations, feel free to ask!!

Thank you for your time and help!!!

Best regards,

Jérémie

### PR DESCRIPTION
**Pull request by afabri**
At the same time allow to process argc[1] if present. 

This should fix #800 
Almost, as there is still an example with a domain where we call the constructor with a file name. See also  #488

### CODE REVIEW

File: Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp [hunk 1]
```diff
@@ -34,12 +34,17 @@ typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;
...
 {
+  const char* fname = (argc>1)?argv[1]:"data/elephant.off";
   // Create input polyhedron
   Polyhedron polyhedron;
-  std::ifstream input("data/elephant.off");
+  std::ifstream input(fname);
   input >> polyhedron;
+  if(input.bad()){
+    std::cerr << "Error: Cannot read file " <<  fname << std::endl;
+  }
```
Comment (sloriot) [inline Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp]: missing `return 1;`?

File: Mesh_3/examples/Mesh_3/mesh_polyhedral_edge_tolerance_region.cpp [hunk 2]
```diff
@@ -41,12 +33,16 @@ typedef Mesh_criteria::Cell_criteria Cell_criteria;
...
 {
+  const char* fname = (argc>1)?argv[1]:"data/star.off";
   // Create polyhedron
   Polyhedron polyhedron;
-  std::ifstream input("data/star.off");
+  std::ifstream input(fname);
   input >> polyhedron;
+  if(input.bad()){
+    std::cerr << "Error: Cannot read file " <<  fname << std::endl;
+  }
```
Comment (sloriot) [inline Mesh_3/examples/Mesh_3/mesh_polyhedral_edge_tolerance_region.cpp]: missing `return 1`;?

File: Mesh_3/examples/Mesh_3/mesh_polyhedral_implicit_function.cpp [hunk 3]
```diff
@@ -38,12 +32,16 @@ typedef Mesh_criteria::Facet_criteria Facet_criteria;
...
 {
+  const char* fname = (argc>1)?argv[1]:"data/elephant.off";
   // Create and fill polyhedron
   Polyhedron polyhedron;
-  std::ifstream input("data/elephant.off");
+  std::ifstream input(fname);
   input >> polyhedron;
+  if(input.bad()){
+    std::cerr << "Error: Cannot read file " <<  fname << std::endl;
+  }
```
Comment (sloriot) [inline Mesh_3/examples/Mesh_3/mesh_polyhedral_implicit_function.cpp]: missing `return 1`?

File: Mesh_3/examples/Mesh_3/mesh_polyhedral_surface_tolerance_region.cpp [hunk 4]
```diff
@@ -39,12 +31,16 @@ typedef Mesh_criteria::Facet_criteria Facet_criteria;
...
 {
+  const char* fname = (argc>1)?argv[1]:"data/elephant.off";
   // Create and fill polyhedron
   Polyhedron polyhedron;
-  std::ifstream input("data/elephant.off");
+  std::ifstream input(fname);
   input >> polyhedron;
+  if(input.bad()){
+    std::cerr << "Error: Cannot read file " <<  fname << std::endl;
+  }
```
Comment (sloriot) [inline Mesh_3/examples/Mesh_3/mesh_polyhedral_surface_tolerance_region.cpp]: missing `return 1;`?

Comment (sloriot) [inline Mesh_3/examples/Mesh_3/mesh_polyhedral_surface_tolerance_region.cpp]: still missing one here

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-145
