### PR TITLE
Test deprecated result_of.h

### LINKED ISSUE #5729: CGAL/result_of.h should compile
@maxGimeno 
The file  should still be tested, and working, even if it is deprecated. Now it gives an error:

```
.../STL_Extension/include/CGAL/result_of.h:59:9: error: redefinition of ‘class CGAL::cpp11::result_of<F(Args ...)>’
   59 |   class result_of<F(Args...)> : public std::invoke_result<F, Args...> { };
      |         ^~~~~~~~~~~~~~~~~~~~~

.../Installation/include/CGAL/config.h:672:11: note: previous definition of ‘class CGAL::cpp11::result_of<F(Args ...)>
```

_Originally posted by @lrineau in https://github.com/CGAL/cgal/issues/5671#issuecomment-847785069_

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Replace `result_of.h`'s content by a simple include to config.h, and test it in `test_stl_extension.cpp`

## Release Management

* Affected package(s):STL_Extension
* Issue(s) solved (if any): fix #5729

### CODE REVIEW

File: STL_Extension/test/STL_Extension/test_stl_extension.cpp [hunk 1]
```diff
@@ -50,6 +50,9 @@
 #include <boost/type_traits/is_same.hpp>
 #include <boost/typeof/typeof.hpp>
 
+#include <CGAL/disable_warnings.h>
+#include <CGAL/result_of.h>
+#include<CGAL/enable_warnings.h>
```
Comment (lrineau) [inline STL_Extension/test/STL_Extension/test_stl_extension.cpp:55]:
```suggestion
#include <CGAL/internal/disable_deprecation_warnings_and_errors.h>
#include <CGAL/result_of.h>
```

**Review by lrineau — APPROVED** [review]

**Review by lrineau — APPROVED** [review]

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-135.shtml
