### PR TITLE
Fix static filter of Do_intersect_3(Bbox_3,Triangle_3)

### LINKED ISSUE #6808: do_intersect(Triangle_3,Bbox_3) is incorrect
## Issue Details

do_intersect(Triangle_3,Bbox_3) is incorrect

## Source Code

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <iostream>

typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef K::Point_3 Point_3;
typedef K::Triangle_3 Triangle_3;
typedef CGAL::Bbox_3 Bbox_3;

int main()
{
  Point_3 p0(-34.1128,-4.00842,39.5061);
  Point_3 p1(-36.0938,-3.6615,36.87);
  Point_3 p2(-34.5781,-3.61804,39.9716);
  Triangle_3 cgt(p0,p1,p2);
  Bbox_3 triBox(cgt.bbox());
  
  Bbox_3 otherBox(-52.3586,-14.3376,25.3037,-38.021,0,39.6414);
  
  if(do_intersect(cgt,otherBox)) std::cout<<"cgt and otherBox intersect"<< std::endl;
  else std::cout<<"cgt and otherBox do not intersect" << std::endl;
  if(do_intersect(triBox,otherBox)) std::cout<<"triBox and otherBox intersect"<<std::endl;
  else std::cout<<"triBox and otherBox do not intersect"<<std::endl;
  return 0;
}

```

The above code outputs:

```
cgt and otherBox intersect
triBox and otherBox do not intersect
```

In the below image otherBox is green, triBox is gray and cgt is red:

a

## Environment

OS: Ubuntu 22.04
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Release
CGAL 5.5
Boost 1.66

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

Fix static filter of `Do_intersect_3(Bbox_3,Triangle_3)`.

See the publication at https://www.semanticscholar.org/paper/High-performance-triangle-versus-box-intersection-Christensen-Karlsson/bad661b58359ec01be2deb2f47ec8fd8eb293747.

The test of intersection of `bbox` and `triangle.bbox` was missing. It implements 3 of the test out of the 13 that are needed.

## Release Management

* Affected package(s): Filtered_kernel
* Issue(s) solved (if any): fix #6808
* License and copyright ownership: maintenance by GeometryFactory

### CODE REVIEW

File: Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Triangle_3_do_intersect.h [hunk 1]
```diff
@@ -273,29 +273,29 @@ do_intersect_bbox_or_iso_cuboid_impl(const std::array< std::array<FT, 3>, 3>& tr
   }};
 
   int forbidden_axis = -1;
-  int forbidden_size = -1;
+  int forbidden_side = -1;
```
Comment (afabri) [inline Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Triangle_3_do_intersect.h:276]: In fact I had not understood the meaning of size.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-65.
