### PR TITLE
Respected verbose

### LINKED ISSUE #9034: Several Problems in Reading OFF files
I've quickly searched the issues list and couldn't find anything similar, so I believe that most of not all of the content of this issue is relevant, but I could be wrong.

## Issue Details

There are several problems with the way CGAL handles files in the `OFF` format. The code listed below is an attempt to cover those reported herel; thus, a bit longer than the typical minimal program. The program reads a file in the `OFF` format and displays it. It constructs an object the type of which is either an instance of the templates `Polyhedron_3` or `Surface_mesh`, depending on whether the macro `USE_SURFACE_MESH` is defined; see Line 4 in the listing,

1. The first line of a file in the `OFF` format has the letters `OFF` to mark the file type. (This is typically referred to as the _magic_ string.) It turns out that the CGAL reader(s) accept either `OFF` or `COFF` as the magic string, where `COFF` indicates that the file has colors (with faces or vertices). The string `COFF` is not in the standard; thus, redundant. I can live with the fact the when `COFF` is indicated, colors are expected; however, I believe that if `OFF` is indicated, colors should still be handled properly. Currently, if `OFF` is indicated, colors seem to be ignored. I must add and say that I find it of high priority, because it has to do with standards,
2. It seems that different pieces of code are used to read files in the `OFF` format based on the provided (named) parameters. This is, naturally bad practice, but here we actually get different behaviors. Assume that the definition of `USE_SURFACE_MESH` is commented out; that is, we are using Polyhedron_3. Assume we are only passing `verbose` and `repair_polygon_soup` (Line 61). Then, if the input data is inconsistent, the build of the mesh fails with a useful error message, e.g.,:

> CGAL::Polyhedron_incremental_builder_3<HDS>::
> lookup_halfedge(): input error: facet 336 shares a halfedge from vertex 0 to vertex 1 with facet 0.

However, if we call `read_polygon_mesh()` and also provide a color map, the call returns `false`, but we do not get any error message. The split in the code occurs in the file `Polyhedron_OFF_iostream.h`, Line 69. When providing a color map we end up calling `read_OFF_BGL()`, and in turn `CGAL::Euler::add_face(face, g)`; see Line 146 in File `Generic_facegraph_builder.h`. One quick fix is testing whether `verbose` is `true`, and if so, precede the call to `add_face()` with a check in the form of a call to `can_add_face()`. I think that if we use the `Surface_mesh` template we don't get any useful error messages whatsoever, so if we use different code, then it should be fixed there as well.

3. The reference of [CGAL::Polygon_mesh_processing::IO::read_polygon_mesh](javascript:void(0)) is missing the following options:

    - face_color_map
    - vertex_color_map
    - vertex_normal_map
    - vertex_texture_map

4. While at it, it would be nice if the very simple example `draw_polyhedron.cpp` is enhanced with the ability to read and respect face colors as done here.

```
#include <iostream>
#include <string>

// #define USE_SURFACE_MESH

#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#if defined(USE_SURFACE_MESH)
#include <CGAL/Surface_mesh.h>
#include <CGAL/draw_surface_mesh.h>
#else
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Polyhedron_traits_with_normals_3.h>
#include <CGAL/draw_polyhedron.h>
#endif

#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>
#include <CGAL/IO/Color.h>

#if ! defined(USE_SURFACE_MESH)
#include "Extended_polyhedron_items.h"
#endif

int main(int argc, char* argv[]) {
  using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;

#if defined(USE_SURFACE_MESH)
  using Mesh   = CGAL::Surface_mesh<Kernel::Point_3>;
#else
  using Traits = CGAL::Polyhedron_traits_with_normals_3<Kernel>;
  using Mesh = CGAL::Polyhedron_3<Traits, Extended_polyhedron_items>;
  using Face_color_map = boost::property_map<Mesh, CGAL::dynamic_face_property_t<CGAL::IO::Color> >::type;
#endif

  using Vertex_descriptor = boost::graph_traits<Mesh>::vertex_descriptor;
  using Edge_descriptor = boost::graph_traits<Mesh>::edge_descriptor;
  using Face_descriptor = boost::graph_traits<Mesh>::face_descriptor;

  const char* filename = (argc > 1) ? argv[1] : "cube.off";
  std::cout << filename << std::endl;
  Mesh mesh;

#if defined(USE_SURFACE_MESH)
  if (! CGAL::IO::read_polygon_mesh(filename, mesh, CGAL::parameters::verbose(true).repair_polygon_soup(true))) {
    std::cerr << "Error: could not read mesh from '" << filename << "'.\n";
    return 1;
  }
  std::cout << "Loaded mesh with " << num_vertices(mesh) << " vertices, " << num_faces(mesh) << " faces.\n";

  auto face_property_maps = mesh.properties<Face_descriptor>();
  for (const auto& pm : face_property_maps) std::cout << pm << std::endl;

  // Show colors for faces
  auto fcolors_optional = mesh.property_map<Face_descriptor, CGAL::IO::Color >("f:color");
  if (! fcolors_optional) {
     std::cerr << "Error: could not read colors from '" << filename << "'.\n";
     return 1;
  }
  auto fcolors = fcolors_optional.value();

#else
  Face_color_map fcolors;
#if 0
  if (! CGAL::IO::read_polygon_mesh(filename, mesh, CGAL::parameters::verbose(true).repair_polygon_soup(true))) {
#else
  if (! CGAL::IO::read_polygon_mesh(filename, mesh, CGAL::parameters::verbose(true).repair_polygon_soup(true).
                                    face_color_map(fcolors))) {
#endif
    std::cerr << "Error: could not read mesh from '" << filename << "'.\n";
    return 1;
  }
  std::cout << "Loaded mesh with " << num_vertices(mesh) << " vertices, " << num_faces(mesh) << " faces.\n";
#endif

  std::size_t idx = 0;
  for (auto fd : CGAL::faces(mesh)) {
    CGAL::IO::Color c = get(fcolors, fd);
    std::cout << "face[" << idx++ << "]: ("
              << int(c.red())   << ", "
              << int(c.green()) << ", "
              << int(c.blue())  << ", "
              << int(c.alpha()) << ")\n";
  }

  CGAL::Graphics_scene_options<Mesh, Vertex_descriptor, Edge_descriptor, Face_descriptor> gso;
#if ! defined(USE_SURFACE_MESH)
  gso.colored_face=[](const Mesh&, Face_descriptor) -> bool { return true; };
  gso.face_color=[&](const Mesh& mesh, Face_descriptor fd) -> CGAL::IO::Color { return get(fcolors, fd); };
#endif
  CGAL::draw(mesh, gso, filename);

  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by efifogel**
## Summary of Changes

Added a small piece of code that generates an error message if verbose is on and adding a face fails.
This fix is the bare minimum....
It would be nice to normalize all error messages and make them look similar.

## Release Management

* Affected package(s): BGL
* Issue(s) solved (if any): fix #9034 partially. It partially fixes item 4. in the list of the bug report
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:

### CODE REVIEW

File: BGL/include/CGAL/boost/graph/IO/Generic_facegraph_builder.h [hunk 1]
```diff
@@ -144,6 +144,12 @@ class Generic_facegraph_builder
...
 
       face_descriptor f = CGAL::Euler::add_face(face, g);
+      if (verbose) {
+        if (! CGAL::Euler::can_add_face(face, g)) {
+          std::cerr << "Error: Failed to add face [" << i << "]\n";
+          return false;
+        }
+      }
       if(f == boost::graph_traits<Graph>::null_face())
         return false;
```
Comment (MaelRL) [inline BGL/include/CGAL/boost/graph/IO/Generic_facegraph_builder.h:155]:
```suggestion
      face_descriptor f = CGAL::Euler::add_face(face, g);
      if(f == boost::graph_traits<Graph>::null_face()) {
          if (verbose) {
            std::cerr << "Error: Failed to add face [" << i << "]\n";
          }
          CGAL_assertion_code(bool cannot_add = CGAL::Euler::can_add_face(face, g);)
          CGAL_assertion(!cannot_add);
        }
        return false;
      }
```

**Comment by MaelRL** [comment]
In some branch, I have also modified the function `can_add_face()` to add some verbosity as to understand what was the actual issue:

```cpp
/**
* checks whether a new face defined by a range of vertices (identified by their descriptors,
* `boost::graph_traits<Graph>::%vertex_descriptor`) can be added.
*/
template <typename VertexRange,
          typename PMesh>
bool can_add_face(const VertexRange& vrange,
                  const PMesh& sm,
                  const bool verbose = false)
{
  typedef typename boost::graph_traits<PMesh>::vertex_descriptor vertex_descriptor;
  typedef typename boost::graph_traits<PMesh>::halfedge_descriptor halfedge_descriptor;

  CGAL_precondition_code(for(vertex_descriptor v : vrange))
  CGAL_precondition(is_valid_vertex_descriptor(v, sm));

  std::vector<typename boost::graph_traits<PMesh>::vertex_descriptor> face(vrange.begin(), vrange.end());

  std::size_t N = face.size();
  std::vector<vertex_descriptor> f2(face);
  std::sort(f2.begin(), f2.end());

  typename std::vector<vertex_descriptor>::iterator it = std::unique(f2.begin(),f2.end());

  if((N > 0) && (it != f2.end())){
    if (verbose) {
      std::cerr << "Error: can_add_face: face contains duplicate vertices." << std::endl;
    }
    return false;
  }

  if(N < 3){
    if (verbose) {
      std::cerr << "Error: can_add_face: face must contain at least 3 vertices." << std::endl;
    }
    return false;
  }

  face.push_back(face.front());

  for(std::size_t i=0; i < N; ++i){
    halfedge_descriptor hd;
    bool found;
    std::tie(hd,found) = halfedge(face[i],face[i+1],sm);
    if(found && (! is_border(hd,sm))){
      if (verbose) {
        std::cerr << "Error: can_add_face: face contains an edge that is not a border halfedge." << std::endl;
      }
      return false;
    }
  }

  for(std::size_t i=0; i < N; ++i){
    if(halfedge(face[i],sm) == boost::graph_traits<PMesh>::null_halfedge()){
      continue;
    }

    if(! is_border(face[i],sm)){
      if (verbose) {
        std::cerr << "Error: can_add_face: face contains a vertex that is not a border vertex." << std::endl;
      }
      return false;
    }
  }
  //Test if all halfedges of the new face
  //are possibly consecutive border halfedges in the HDS.
  //Possibly because it may be not directly encoded in the HDS
  //(using next() function ). This situation can occur when one or
  //more facets share only a vertex: For example, the new facet we try to add
  //would make the vertex indices[i] a manifold but this should be forbidden
  //if a facet only incident to that vertex has already been inserted.
  //We check this for each vertex of the sequence.
  for(std::size_t i = 0; i < N; ++i) {
    std::size_t prev_index= (i-1+N)%N;
    std::size_t next_index= (i+1)%N;
    vertex_descriptor   previous_vertex = face[ prev_index ];
    vertex_descriptor   next_vertex     = face[ next_index ];

    halfedge_descriptor halfedge_around_vertex = halfedge(face[i],sm);

    if ( halfedge_around_vertex == boost::graph_traits<PMesh>::null_halfedge() ||
         halfedge(previous_vertex,sm) == boost::graph_traits<PMesh>::null_halfedge()||
         halfedge(next_vertex,sm) == boost::graph_traits<PMesh>::null_halfedge() ) {
      continue;
    }

    halfedge_descriptor start=halfedge_around_vertex;
    //halfedges pointing to/running out from vertex indices[i]
    //and that need to be possibly consecutive
    halfedge_descriptor prev_hd= boost::graph_traits<PMesh>::null_halfedge(),next_hd= boost::graph_traits<PMesh>::null_halfedge();

    halfedge_around_vertex = opposite(next(halfedge_around_vertex,sm),sm);
    //look for a halfedge incident to vertex indices[i]
    //and which opposite is incident to previous_vertex
    do{
      if(target(opposite(halfedge_around_vertex,sm),sm)==previous_vertex){
        prev_hd=halfedge_around_vertex;
        CGAL_precondition(is_border(prev_hd,sm));
        break;
      }
      halfedge_around_vertex = opposite(next(halfedge_around_vertex,sm),sm);
    }
    while (halfedge_around_vertex!=start);

    if (prev_hd != boost::graph_traits<PMesh>::null_halfedge()){
      halfedge_around_vertex = opposite(next(halfedge_around_vertex,sm),sm);
      //prev_hd and next are already consecutive in the HDS
      if (target(opposite(halfedge_around_vertex,sm),sm)==next_vertex) continue;

      //look for a border halfedge which opposite is
      //incident to next_vertex: set next halfedge
      do
        {
          if (target(opposite(halfedge_around_vertex,sm),sm)==next_vertex){
            next_hd = opposite(halfedge_around_vertex,sm);
            break;
          }
          halfedge_around_vertex = opposite(next(halfedge_around_vertex,sm),sm);
        }
      while(halfedge_around_vertex != prev_hd);
      if (next_hd==boost::graph_traits<PMesh>::null_halfedge()) continue;

      //check if no constraint prevents
      //prev_hd and next_hd to be adjacent:
      do{
        halfedge_around_vertex = opposite(next(halfedge_around_vertex, sm),sm);
        if ( is_border(opposite(halfedge_around_vertex,sm),sm) ) break;
      }
      while (halfedge_around_vertex != prev_hd);
      if (halfedge_around_vertex == prev_hd) {
        if (verbose) {
          std::cerr << "Error: can_add_face: halfedge_around_vertex == prev_hd" << std::endl;
        }
        return false;
      }
      start = halfedge_around_vertex;
    }
  }

  return true;
}
```

Maybe this could be added into this PR?

File: BGL/include/CGAL/boost/graph/IO/Generic_facegraph_builder.h (hunk 1 above)
Comment (sloriot) [reply BGL/include/CGAL/boost/graph/IO/Generic_facegraph_builder.h:155]: @MaelRL could you please update the suggestion or even directly commit in the branch?

**Comment by MaelRL** [comment]
@efifogel can I modify the PR to add the extra verbose code in can_add_face and the builder?

**Comment by efifogel** [comment]
Of course.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.2-Ic-14
