### PR TITLE
Do not rely on result_type definitions in kernels

### LINKED ISSUE #8578: Applying Construct_center_3 on a Circle_3 object causes segmentation fault
Here is a simple program that generates the issue:

```c++
#include <iostream>
#include <CGAL/Cartesian.h>
int main() {
  using Kernel = CGAL::Cartesian<double>;
  Kernel kernel;
  auto ctr = kernel.construct_center_3_object();
  Kernel::Point_3 p(0,1,2);

  Kernel::Sphere_3 s(p,1);
  const auto b = ctr(s);
  std::cout << "Sphere center: " << b << std::endl;

  Kernel::Vector_3 v(0,0,1);
  Kernel::Circle_3 c(p,1,v);
  const auto a = ctr(c);
  std::cout << "Circle center: " << a << std::endl;

  return 0;
}

```
As a matter of fact, I also get a warning during compilation:

```c++
/home/efif/trees/cgal/cgal_master/Kernel_23/include/CGAL/Kernel/function_objects.h: In instantiation of ‘const Point_3& CGAL::CommonKernelFunctors::Construct_center_3<K>::operator()(const Circle_3&) const [with K = CGAL::Cartesian<double>; CGAL::CommonKernelFunctors::Construct_center_3<K>::result_type = const CGAL::Point_3<CGAL::Cartesian<double> >&; CGAL::CommonKernelFunctors::Construct_center_3<K>::Circle_3 = CGAL::Circle_3<CGAL::Cartesian<double> >]’:
/home/efif/tmp/cgal/test/test.cpp:15:21:   required from here
/home/efif/trees/cgal/cgal_master/Kernel_23/include/CGAL/Kernel/function_objects.h:1559:29: warning: returning reference to temporary [-Wreturn-local-addr]
 1559 |     { return c.rep().center(); }
      |                             ^

```

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

The PR essentially reworks a lot of function object-related code to avoid relying on a `result_type` typedef, which regularly did not correspond to the actual return type of functions.

With modern C++ (`std::invoke_result_t`, `decltype`, etc.), we do not need `result_type` anyway. With `if constexpr` a lot can be simplified, for example in Lazy.h because we do not need to know the classify the result types before actually calling the functors.

Also add missing tests for EPICK & EPECK, and purge dead code.

Return_base_tag rework is out of scope.

TODO:
- [ ] Remove the result type introduced in https://github.com/CGAL/cgal/pull/8810

## Release Management

* Affected package(s): `Kernel_23`
* Issue(s) solved (if any): fix #8578 
* Feature/Small Feature (if any): N/A
* License and copyright ownership: no change

### CODE REVIEW

**Comment by afabri** [comment]
Errors in[ I-c-12](https://cgal.geometryfactory.com/CGAL/testsuite/summary-6.1-Ic-12.html?package=Circular_kernel_3)

**Comment by sloriot** [comment]
Changing the target induces conflicts

**Comment by MaelRL** [comment]
Here is some runtime comparisons for tests that take more than a second on my machine:

```
mrouxell@escher:~/tmp$ sh compare_execution_times.sh ~/log_master.txt ~/log_kernel.txt 
Runtime comparisons:
===================
ex_weighted_periodic_alpha_shapes_3               :   4.25 sec ->   4.18 sec (-1.6%)
successive_wraps                                  :   8.20 sec ->   8.12 sec (-1.0%)
example_mesh_classification                       :   1.13 sec ->   1.09 sec (-3.5%)
mesh_implicit_domains                             :   1.43 sec ->   1.44 sec (+0.7%)
mesh_implicit_domains_2                           :   1.98 sec ->   1.94 sec (-2.0%)
mesh_polyhedral_domain_with_lipschitz_sizing      :   2.34 sec ->   2.38 sec (+1.7%)
mesh_optimization_example                         :   1.97 sec ->   2.03 sec (+3.0%)
mesh_3D_image_with_custom_initialization          :   1.93 sec ->   1.99 sec (+3.1%)
mesh_3D_image_with_initial_points                 :   1.88 sec ->   1.91 sec (+1.6%)
aabb_any_all_benchmark                            :   5.12 sec ->   4.97 sec (-2.9%)
aabb_distance_edge_test                           :   2.27 sec ->   2.25 sec (-0.9%)
aabb_distance_triangle_hint_test                  :   4.69 sec ->   4.63 sec (-1.3%)
aabb_distance_triangle_test                       :   2.24 sec ->   2.21 sec (-1.3%)
aabb_intersection_triangle_test                   :   7.22 sec ->   7.16 sec (-0.8%)
aabb_naive_vs_tree_distance_segment_test          :   4.88 sec ->   4.92 sec (+0.8%)
aabb_naive_vs_tree_distance_triangle_test         :   4.62 sec ->   4.62 sec (+0.0%)
aabb_naive_vs_tree_triangle_test                  :  10.01 sec ->   9.99 sec (-0.2%)
aabb_triangle_datum_covering                      :   3.84 sec ->   3.39 sec (-11.7%) (SIGNIFICANT)
bbox_other_do_intersect_test                      : 121.94 sec -> 122.21 sec (+0.2%)
Cactus_deformation_session                        :   2.53 sec ->   2.47 sec (-2.4%)
convex_hull_containment_benchmarks                :   1.42 sec ->   1.59 sec (+12.0%) (SIGNIFICANT)
corefinement_consecutive_bool_op                  :   1.05 sec ->   1.07 sec (+1.9%)
corefinement_parallel_union_meshes                :   1.34 sec ->   1.35 sec (+0.7%)
edge_collapse_garland_heckbert_variations         :   1.64 sec ->   1.57 sec (-4.3%)
example_delaunay_2                                :   0.94 sec ->   1.03 sec (+9.6%)
extensive_parameterization_test                   :   7.81 sec ->   7.52 sec (-3.7%)
features_and_adaptive_sizing                      :   1.90 sec ->   1.87 sec (-1.6%)
hausdorff_bounded_error_distance_example          :   5.24 sec ->   5.28 sec (+0.8%)
ht2_test_insert_degenerate                        :   1.99 sec ->   1.91 sec (-4.0%)
ht2_test_locate                                   :   2.50 sec ->   2.37 sec (-5.2%)
Iso_rectangle_2_query                             :   3.59 sec ->   3.46 sec (-3.6%)
issue7149                                         :  14.05 sec ->  13.95 sec (-0.7%)
issue_8624                                        :   4.85 sec ->   4.89 sec (+0.8%)
kinetic_3d_test_all                               :  14.80 sec ->  14.61 sec (-1.3%)
ksr_regularization                                :   1.21 sec ->   1.22 sec (+0.8%)
ksr_reorientation                                 :   3.76 sec ->   3.79 sec (+0.8%)
Linear_cell_complex_3_test                        :   4.40 sec ->   4.49 sec (+2.0%)
mesh_and_remesh_with_adaptive_sizing              :  16.41 sec ->  16.74 sec (+2.0%)
mesh_and_remesh_with_sizing                       :  22.48 sec ->  22.83 sec (+1.6%)
mesh_implicit_multi_domain                        :   1.26 sec ->   1.36 sec (+7.9%)
mesh_implicit_shape_with_optimizers               :  12.59 sec ->  12.83 sec (+1.9%)
mesh_implicit_shape_with_subdomains               :   2.56 sec ->   2.70 sec (+5.5%)
mesh_periodic_polyhedral_domain                   :   1.00 sec ->   1.06 sec (+6.0%)
mesh_smoothing_example                            :   1.09 sec ->   1.13 sec (+3.7%)
orient_polygon_soup_test                          :   6.13 sec ->   5.85 sec (-4.6%)
otr2_epeck                                        :   2.06 sec ->   2.69 sec (+30.6%) (SIGNIFICANT)
p4ht2_example_insertion                           :   3.25 sec ->   3.07 sec (-5.5%)
segmentation_example                              :   1.47 sec ->   1.46 sec (-0.7%)
stl_triangular_field                              :   2.12 sec ->   2.13 sec (+0.5%)
Stream_line                                       :   6.22 sec ->   6.29 sec (+1.1%)
Surface_mesh_shortest_path_test_2                 :   2.41 sec ->   2.47 sec (+2.5%)
test_AW3_manifoldness                             :   1.91 sec ->   0.71 sec (-62.8%) (SIGNIFICANT)
test_AW3_multiple_calls                           :   1.18 sec ->   1.34 sec (+13.6%) (SIGNIFICANT)
test_bgl_read_write                               :   1.34 sec ->   1.33 sec (-0.7%)
test_classification_point_set                     :   3.17 sec ->   2.64 sec (-16.7%) (SIGNIFICANT)
test_compute_sdf_values_and_segment_exact_rational:  20.13 sec ->  20.08 sec (-0.2%)
test_delaunay_hierarchy_3                         :   1.10 sec ->   1.15 sec (+4.5%)
test_distance_3                                   :   6.71 sec ->   6.01 sec (-10.4%) (SIGNIFICANT)
test_dummy_point_generation                       :   2.74 sec ->   3.77 sec (+37.6%) (SIGNIFICANT)
test_fixed_alpha_shape_3                          :   5.97 sec ->   5.87 sec (-1.7%)
test_hausdorff_bounded_error_distance             :   3.14 sec ->   3.01 sec (-4.1%)
test_homotopy_with_polygonal_schema               :   5.38 sec ->   5.80 sec (+7.8%)
test_implicit_shapes_bunch                        :   6.64 sec ->   6.97 sec (+5.0%)
test_implicit_shapes_with_features                :   3.41 sec ->   3.57 sec (+4.7%)
test_intersections_Iso_cuboid_3                   :   2.44 sec ->   2.32 sec (-4.9%)
test_max_edge_distance                            :   1.80 sec ->   2.19 sec (+21.7%) (SIGNIFICANT)
test_mesh_and_remesh_polyhedron_with_features_mls :   1.71 sec ->   1.74 sec (+1.8%)
test_mesh_and_remesh_polyhedron_with_features     :   1.70 sec ->   1.81 sec (+6.5%)
test_mesh_and_remesh_with_sizing_field            :  32.72 sec ->  32.00 sec (-2.2%)
test_meshing_3D_image_with_features               :  21.09 sec ->  22.43 sec (+6.4%)
test_meshing_without_features_determinism         :  13.27 sec ->  14.46 sec (+9.0%)
test_mesh_smoothing                               :   7.35 sec ->   7.32 sec (-0.4%)
test_p2t2_delaunay_insert_degenerate              :   2.38 sec ->   2.34 sec (-1.7%)
test_p2t2_delaunay_insert_random                  :   2.38 sec ->   2.30 sec (-3.4%)
test_p2t2_delaunay_performance                    :  18.26 sec ->  18.73 sec (+2.6%)
test_p2t2_triangulation_insert_random             :   3.58 sec ->   3.78 sec (+5.6%)
test_p3rt3_as_p3t3                                :   1.61 sec ->   1.64 sec (+1.9%)
test_p3rt3_insert_remove_point_set                :   3.94 sec ->   4.15 sec (+5.3%)
test_periodic_3_alpha_shape_3                     :   1.81 sec ->   1.73 sec (-4.4%)
test_periodic_3_triangulation_3                   :   5.45 sec ->   5.39 sec (-1.1%)
test_pmp_locate                                   :   4.02 sec ->   4.07 sec (+1.2%)
test_random_qp2                                   :   1.32 sec ->   1.30 sec (-1.5%)
test_random_qp                                    :   3.00 sec ->   2.92 sec (-2.7%)
test_regular_as_delaunay_3                        :   1.16 sec ->   1.20 sec (+3.4%)
test_robust_weighted_circumcenter                 :   2.25 sec ->   2.28 sec (+1.3%)
test_shortest_cycle_non_contractible              :   3.65 sec ->   3.60 sec (-1.4%)
test_sls_extrude                                  :  32.70 sec ->  32.56 sec (-0.4%)
test_sls_offset                                   :  24.37 sec ->  24.90 sec (+2.2%)
test_sls_simple                                   :   8.88 sec ->   9.20 sec (+3.6%)
test_sls_weighted_polygons                        :   5.78 sec ->   6.78 sec (+17.3%) (SIGNIFICANT)
test_sls_weighted_polygons_with_holes             :  35.26 sec ->  24.71 sec (-29.9%) (SIGNIFICANT)
test_solver                                       :   1.10 sec ->   1.12 sec (+1.8%)
test_Spherical_kernel_with_core                   :   1.09 sec ->   1.14 sec (+4.6%)
test_subresultants                                :   1.20 sec ->   1.18 sec (-1.7%)
test_surface_neighbor_3                           :   2.41 sec ->   2.32 sec (-3.7%)
test_tetrahedral_remeshing_mls                    :   1.11 sec ->   1.22 sec (+9.9%)
test_tetrahedral_remeshing                        :   1.08 sec ->   1.16 sec (+7.4%)
test_tetrahedral_remeshing_with_features          :   1.16 sec ->   1.25 sec (+7.8%)
test_triply_periodic_minimal_surfaces             : 164.89 sec -> 165.72 sec (+0.5%)
test_validity_sampled_data                        :   1.21 sec ->   1.26 sec (+4.1%)
test_with_extended_homogeneous                    :   1.36 sec ->   1.35 sec (-0.7%)
tetrahedral_remeshing_example                     :   1.09 sec ->   1.11 sec (+1.8%)
tetrahedral_remeshing_with_features_and_sizing    :   1.35 sec ->   1.39 sec (+3.0%)
triangles_test                                    :  54.23 sec ->  54.13 sec (-0.2%)
triangulate_hole_Polyhedron_3_no_delaunay_test    :   1.44 sec ->   1.45 sec (+0.7%)
vcm_all_test                                      :   1.51 sec ->   1.48 sec (-2.0%)
vsa_correctness_test                              :   2.22 sec ->   2.30 sec (+3.6%)
vsa_kernel_test                                   :   1.56 sec ->   1.45 sec (-7.1%)
```

I don't really see anything significant: most tests with > 10% variation (which have the suffix "(SIGNIFICANT)") are tests where there is a lot of randomness (test_distance_3, test_sls_weighted_polygons, ...)

File: Cartesian_kernel/include/CGAL/Cartesian/Circle_2.h [hunk 1]
```diff
@@ -69,6 +70,25 @@ class CircleC2
 
 };
 
+template < class R >
+typename R::Boolean
+CircleC2<R>::operator==(const CircleC2<R> &t) const
+{
+  if (CGAL::identical(base, t.base))
```
Comment (lrineau) [inline Cartesian_kernel/include/CGAL/Cartesian/Circle_2.h:77]: That name `identical` is really a bad one.

Without any previous knowledge, how can one understand the difference between "equal" and "identical".

Probably `identical` should be renamed `are_same_objects`

Comment (MaelRL) [reply Cartesian_kernel/include/CGAL/Cartesian/Circle_2.h:77]: Adding this missing operator() was already barely in the scope of this PR and it's just a clone of the other ones.

There's a working group for the dev meeting on kernel work, we can add this there.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.1-Ic-123
