### PR TITLE
Nef_3: Fix issue with the size of the inf box

### LINKED ISSUE #8644: Assertion Nef_3
_Please use the following template to help us solving your issue._

## Issue Details

The following code raise an assertion.

## Source Code
[surface_mesh_kernel.txt](https://github.com/user-attachments/files/18019748/surface_mesh_kernel.txt)
[data.zip](https://github.com/user-attachments/files/18019760/data.zip)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 24.04
* Compiler: g++ 13.2.0
* Release or debug mode: debug
* CGAL version: master branch

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Fixes Issue #8644

## Release Management

* Affected package(s): Nef_3
* Issue(s) solved (if any): fix #
* License and copyright ownership:  unchanged

### CODE REVIEW

File: Nef_3/test/Nef_3/issue8644.cpp [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+#include <CGAL/Extended_cartesian.h>
+#include <CGAL/Exact_rational.h>
+#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
+#include <CGAL/Surface_mesh.h>
+#include <CGAL/Polygon_mesh_processing/compute_normal.h>
+#include <CGAL/Polygon_mesh_processing/orientation.h>
+#include <CGAL/Nef_polyhedron_3.h>
+
+#define DATA_DIR  std::string("./data/")+
```
Comment (sloriot) [inline Nef_3/test/Nef_3/issue8644.cpp:11]:
```suggestion
```

**Comment by afabri** [comment]
So it fails on some platforms in testsuite [6.1-Ic-38](https://cgal.geometryfactory.com/CGAL/testsuite/summary-6.1-Ic-38.html?package=Nef_3)

**Comment by sloriot** [comment]
Should be backported to 5.6

File: Nef_3/include/CGAL/Nef_3/SNC_external_structure.h [hunk 2]
```diff
@@ -585,10 +585,16 @@ class SNC_external_structure_base : public SNC_decorator<SNC_structure_>
             break;
       } else
 #endif
+        CGAL_assertion_code(bool found = false;)
         CGAL_For_all(cet,cete)
           if ( cet->circle() == ce->circle().opposite() &&
                cet->source()->twin() == ce->source() )
+        {
+            found = true;
```
Comment (afabri) [inline Nef_3/include/CGAL/Nef_3/SNC_external_structure.h:593]:
```suggestion
            CGAL_assertion_code(found = true;)
```

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.1-Ic-78
