### PR TITLE
Fix some warnings

### LINKED ISSUE #5030: New batch of warnings
## Issue Details

Here is a list of recently appeared warnings in the testsuite :

 - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-14/Boolean_set_operations_2_Examples/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz :  /mnt/testsuite/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h:249:54: warning: array subscript 'const CGAL::_Bezier_x_monotone_2<CGAL::Cartesian<CORE::BigRat>, CGAL::Cartesian<CORE::Expr>, CGAL::CORE_algebraic_number_traits, CGAL::Bezier_bounding_rational_traits<CGAL::Cartesian<CORE::BigRat> > >[0]' is partly outside array bounds of 'Polygon_2 [1]' {aka 'CGAL::General_polygon_2<CGAL::Arr_Bezier_curve_traits_2<CGAL::Cartesian<CORE::BigRat>, CGAL::Cartesian<CORE::Expr>, CGAL::CORE_algebraic_number_traits> > [1]'} [-Warray-bounds]
  249 |   bool is_directed_right() const { return (_dir_right); }

 - [x] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-14/Convex_decomposition_3/TestReport_lrineau_Ubuntu-latest-GCC6.gz : /mnt/testsuite/include/CGAL/Nef_2/debug.h:61:28: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
   61 | #define CGAL_NEF_TRACEN(t) if((debugthread%CGAL_NEF_DEBUG)==0) 

 - [x] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-14/Hash_map/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz : /mnt/testsuite/include/CGAL/Triangulation_2.h:1354:16: warning: 'li' may be used uninitialized [-Wmaybe-uninitialized]
 1354 |   return insert(p, lt, loc, li);
      |          ~~~~~~^~~~~~~~~~~~~~~~
/mnt/testsuite/include/CGAL/Triangulation_2.h:1352:7: note: 'li' declared here
 1352 |   int li;

 - [x] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-14/Kernel_23/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz : /mnt/testsuite/include/CGAL/Intersections_2/Line_2_Ray_2.h:76:10: warning: 'ispair.CGAL::Intersections::internal::Ray_2_Line_2_pair<CGAL::Simple_cartesian<double> >::_intersection_point.CGAL::Point_2<CGAL::Simple_cartesian<double> >::<anonymous>.CGAL::PointC2<CGAL::Simple_cartesian<double> >::base.CGAL::Vector_2<CGAL::Simple_cartesian<double> >::<anonymous>.CGAL::VectorC2<CGAL::Simple_cartesian<double> >::base.std::array<double, 2>::_M_elems[1]' may be used uninitialized in this function [-Wmaybe-uninitialized]
   76 |     is_t ispair(&ray, &line);

- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-14/Number_types/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz : mnt/testsuite/include/CGAL/Quotient.h:456:22: warning: '<anonymous>' may be used uninitialized [-Wmaybe-uninitialized]
  456 |   return quotient_cmp(x,y) == SMALLER;

- [x] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-Ic-18/Tetrahedral_remeshing/TestReport_lrineau_Ubuntu-latest-GCC6.gz : CGAL/Tetrahedral_remeshing/internal/smooth_vertices.h:546:42: warning: loop variable 'si' creates a copy from type 'const Surface_patch_index' {aka 'const std::pair<int, int>'} 

- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-Ic-18/CGAL_ipelets_Demo/TestReport_lrineau_Debian-stable-Release.gz : /include/CGAL/Arr_segment_traits_2.h:78:9: warning: '*((void*)(&<anonymous>)+8).CGAL::Arr_segment_traits_2<CGAL::Epeck>::_Segment_cached_2::m_is_directed_right' may be used uninitialized in this function 

- [x] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0.4-I-238/Polygon_mesh_processing/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz: loop variable 'hk' creates a copy from type 'const halfedges_pair' {aka 'const std::pair<CGAL::SM_Halfedge_index, CGAL::SM_Halfedge_index>'} [-Wrange-loop-construct]

- [x] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1.1-I-243/Tetrahedral_remeshing/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz : /mnt/testsuite/include/CGAL/Tetrahedral_remeshing/internal/flip_edges.h:1104:25: warning: loop variable 'vp' creates a copy from type 'const std::pair<CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Mesh_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Labeled_mesh_domain_3<CGAL::Epick>, CGAL::Regular_triangulation_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<CGAL::Triangulation_data_structure_3<CGAL::Mesh_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Labeled_mesh_domain_3<CGAL::Epick>, CGAL::Regular_triangulation_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Compact_mesh_cell_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Labeled_mesh_domain_3<CGAL::Epick>, void>, CGAL::Sequential_tag> > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>, CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Mesh_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Labeled_mesh_domain_3<CGAL::Epick>, CGAL::Regular_triangulation_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<CGAL::Triangulation_data_structure_3<CGAL::Mesh_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Labeled_mesh_domain_3<CGAL::Epick>, CGAL::Regular_triangulation_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Compact_mesh_cell_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Epick>, CGAL::Labeled_mesh_domain_3<CGAL::Epick>, void>, CGAL::Sequential_tag> > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false> >' [-Wrange-loop-construct]
 1104 |   for (const VertexPair vp : edges)

- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-19/Arrangement_on_surface_2/TestReport_Friedrich_Ubuntu-gcc-7.gz: include/CGAL/Arr_geometry_traits/Curve_data_aux.h:54:7: warning: ‘*((void*)(&<anonymous>)+8).CGAL::_Curve_data_ex<CGAL::internal::X_monotone_polycurve_2<CGAL::Arr_segment_2<CGAL::Cartesian<CGAL::Gmpq> >, CGAL::Point_2<CGAL::Cartesian<CGAL::Gmpq> > >, unsigned int>::m_data’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 class _Curve_data_ex : public BaseCurveType

- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-19/Arrangement_on_surface_2_Examples/TestReport_lrineau_Debian-stable-Release.gz: More maybe unintialized

- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-19/CGAL_ipelets_Demo/TestReport_lrineau_Debian-stable-Release.gz

- [x] Master : doc problem in Buunding volumes: Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_d.h:66: warning: unable to resolve reference to `Min_sphere_d/min_sphere_homogeneous_d.cpp' for \ref command
/mnt/cgal/Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_d.h:66: warning: included file Min_sphere_d/min_sphere_homogeneous_d.cpp is not found. Check your EXAMPLE_PATH

- [x] Master: In file included from /home/cgal_tester/build/src/cmake/platforms/ArchLinux-CXX14/test/Polyhedron_IO_Examples/off2off.cpp:4:
/mnt/testsuite/include/CGAL/IO/File_writer_OFF.h: In member function ‘void CGAL::File_writer_OFF::write_facet_begin(std::size_t)’:
/mnt/testsuite/include/CGAL/IO/File_writer_OFF.h:80:74: error: ‘int32_t’ in namespace ‘boost’ does not name a type
   80 |           I_Binary_write_big_endian_integer32( out(), static_cast<boost::int32_t>(no));
      |                                                                          ^~~~~~~
/mnt/testsuite/include/CGAL/IO/File_writer_OFF.h: In member function ‘void CGAL::File_writer_OFF::write_facet_vertex_index(std::size_t)’:
/mnt/testsuite/include/CGAL/IO/File_writer_OFF.h:86:74: error: ‘int32_t’ in namespace ‘boost’ does not name a type
   86 |           I_Binary_write_big_endian_integer32( out(), static_cast<boost::int32_t>(index));
**We should use std::int32_t instead, and incllude <cstdint> in that file**

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Fix some uninitialized warning
## Release Management
partially fixes #5030

### CODE REVIEW

File: Intersections_2/include/CGAL/Intersections_2/Line_2_Ray_2.h [hunk 1]
```diff
@@ -35,10 +35,13 @@ namespace internal {
...
 class Ray_2_Line_2_pair {
 public:
-    enum Intersection_results {NO_INTERSECTION, POINT, RAY};
+    enum Intersection_results {NOT_COMPUTED_YET, NO_INTERSECTION, POINT, RAY};
+    typedef typename K::FT FT;
     Ray_2_Line_2_pair(typename K::Ray_2 const *ray,
                       typename K::Line_2 const *line)
-      : _ray(ray), _line(line), _known(false) {}
+      : _ray(ray), _line(line), _result(NOT_COMPUTED_YET),
+        _intersection_point(typename K::Point_2(FT(0), FT(0)))
```
Comment (lrineau) [inline Intersections_2/include/CGAL/Intersections_2/Line_2_Ray_2.h:43]:
```suggestion
        _intersection_point(ORIGIN)
```

**Review by lrineau — APPROVED** [review]

File: Intersections_2/include/CGAL/Intersections_2/Line_2_Ray_2.h [hunk 2]
```diff
@@ -35,10 +35,13 @@ namespace internal {
...
 class Ray_2_Line_2_pair {
 public:
-    enum Intersection_results {NO_INTERSECTION, POINT, RAY};
+    enum Intersection_results {NOT_COMPUTED_YET, NO_INTERSECTION, POINT, RAY};
+    typedef typename K::FT FT;
     Ray_2_Line_2_pair(typename K::Ray_2 const *ray,
                       typename K::Line_2 const *line)
-      : _ray(ray), _line(line), _known(false) {}
+      : _ray(ray), _line(line), _result(NOT_COMPUTED_YET),
+        _intersection_point(typename K::Point_2(ORIGIN))
```
Comment (lrineau) [inline Intersections_2/include/CGAL/Intersections_2/Line_2_Ray_2.h:43]:
```suggestion
        _intersection_point(K().construct_point_2_object()(ORIGIN))
```

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-18.shtml
