### PR TITLE
Fix return type

### LINKED ISSUE #5113: cgal-swig-bindings is broken with CGAL `master`
@sloriot @MaelRL This PR seems to have broken cgal-swig-bindings: https://travis-ci.com/github/CGAL/cgal-swig-bindings/jobs/403883997#L5983

_Originally posted by @lrineau in https://github.com/CGAL/cgal/pull/4729#issuecomment-715368518_

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #5113 

Bug introduced by https://github.com/CGAL/cgal/pull/4729, in `master`, for CGAL-5.2-beta.

### CODE REVIEW

File: Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h [hunk 1]
```diff
@@ -658,10 +658,12 @@ void run_stitch_borders(PolygonMesh& pmesh,
 
 template <typename PolygonMesh, typename HalfedgePairsRange,
           typename Uf_vertices, typename Uf_handles>
-HalfedgePairsRange filter_stitchable_pairs(PolygonMesh& pmesh,
-                                           const HalfedgePairsRange& to_stitch,
-                                           Uf_vertices& uf_vertices,
-                                           Uf_handles& uf_handles)
+std::vector< std::pair<typename boost::graph_traits<PolygonMesh>::halfedge_descriptor,
+                                typename boost::graph_traits<PolygonMesh>::halfedge_descriptor> >
```
Comment (lrineau) [inline Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h:662]:
```suggestion
std::vector< std::pair<typename boost::graph_traits<PolygonMesh>::halfedge_descriptor,
                       typename boost::graph_traits<PolygonMesh>::halfedge_descriptor> >
```

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-36.shtml
