### PR TITLE
Polyhedron demo: Fix edge selection -> face selection conversion

### LINKED ISSUE #2778: Polyhedron demo: Edges to Facet Selection Bug When Boundary Edge
## Issue Details

In the demo, open a polyhedron with boundaries, select a boundary edge and do _Convert Edge Selection to Facet Selection_, the demo crashed (most probably, the boundaries are not handled).

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
- Only call the opposite of the selected halfedge if it is not a border halfedge.
- Add a button to select the whole boundary if in edge selection mode.

* Issue(s) solved (if any): fix #2778

### CODE REVIEW

**Comment by lrineau** [comment]
Does not compile: https://travis-ci.org/CGAL/cgal/jobs/336456297#L7307

File: Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp [hunk 1]
```diff
@@ -573,7 +573,8 @@ public Q_SLOTS:
       BOOST_FOREACH(Scene_polyhedron_selection_item::fg_edge_descriptor ed, selection_item->selected_edges)
       {
         selection_item->selected_facets.insert(face(halfedge(ed, poly), poly));
-        selection_item->selected_facets.insert(face(opposite(halfedge(ed, poly), poly), poly));
+        if(!is_border_edge(halfedge(ed,poly), poly))
+          selection_item->selected_facets.insert(face(opposite(halfedge(ed, poly), poly), poly));
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp]: @sloriot @sgiraudot Could you review this patch? Both the title of the commit and the patch look wrong.

Comment (maxGimeno) [reply Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp]: it seems to work correctly, but I'll still PR a cleaner version.

Comment (lrineau) [reply Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp]: I do not know if it "works". I trust you it worked in your test.

But the description of the commit, and the patch just look wrong. In both of them the notion of "edge" and "halfedge" are completely mixed, and I wonder if the code is actually right.

Comment (lrineau) [reply Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp]: Actually I found out that commit of yours because I was searching for https://github.com/CGAL/cgal/pull/2336/commits/cba3b1c20c4f2e86f8a13ff97ba078e0d397ddd0, that was already a bug due to the confusion between edges and halfedges.

Comment (maxGimeno) [reply Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp]: see #2929

Comment (lrineau) [reply Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp]: ... and 9708c41ad1c3b27e486f3a33c01fa4554a1899ed.

Comment (lrineau) [reply Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp]: Thanks.
