### PR TITLE
Apollonius_graph: Fix return type in the documentation

### LINKED ISSUE #7582: documentation problem about the dual face for Apollonius graph.
According to [the documentation](https://doc.cgal.org/latest/Apollonius_graph_2/classCGAL_1_1Apollonius__graph__2.html#a304f5fe797914ddda090095ece7fdd7d), there's a method `dual` which returns an `Object_2` for `Face_handle`, `Finite_faces_iterator`, and `All_faces_iterator`. This is not in agreement with the code: for `Finite_faces_iterator`, the `dual` method always returns a `Site_2`, and for `All_faces_iterator`, there's no method `dual` defined.

https://github.com/CGAL/cgal/blob/6098856af6ad64f8c851d5e98416ccf4ea7b02a6/Apollonius_graph_2/include/CGAL/Apollonius_graph_2.h#L527

https://github.com/CGAL/cgal/blob/6098856af6ad64f8c851d5e98416ccf4ea7b02a6/Apollonius_graph_2/include/CGAL/Apollonius_graph_2.h#L529

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Fix the return type.  Document the third template parameter of  `Apollonius_graph_vertex_base_2`.

## Release Management

* Affected package(s): `Apollonius_graph_2`
* Issue(s) solved (if any): fix #7582 and #7579
* Link to compiled documentation: [link](https://cgal.github.io/7619/v0/Apollonius_graph_2/classCGAL_1_1Apollonius__graph__2.html#a6e6e1b20ab5018c96e4b0ed2c0f0ee00) and [here ](https://cgal.github.io/7619/v0/Apollonius_graph_2/classCGAL_1_1Apollonius__graph__vertex__base__2.html#acbabb6d26d4d8938bde5bbd6c6e467eb)for the vertex base.
* License and copyright ownership:  unchanged

### CODE REVIEW

File: Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_graph_vertex_base_2.h [hunk 1]
```diff
@@ -7,23 +7,30 @@ namespace CGAL {
 The class `Apollonius_graph_vertex_base_2` provides a model for the
 `ApolloniusGraphVertexBase_2` concept which is the vertex base
 required by the `ApolloniusGraphDataStructure_2` concept. The
-class `Apollonius_graph_vertex_base_2` has two template arguments, the first being the
-geometric traits of the Apollonius graph and should be a model of the
-concept `ApolloniusGraphTraits_2`. The second is a Boolean which
+class `Apollonius_graph_vertex_base_2` has two template arguments.
```
Comment (MaelRL) [inline Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_graph_vertex_base_2.h:10]:
```suggestion
class `Apollonius_graph_vertex_base_2` has three template arguments.
```

File: Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_graph_vertex_base_2.h [hunk 2]
```diff
@@ -7,23 +7,30 @@ namespace CGAL {
...
+
 \cgalModels `ApolloniusGraphVertexBase_2`
 
 \sa `CGAL::Triangulation_data_structure_2<Vb,Fb>`
 \sa `CGAL::Apollonius_graph_hierarchy_vertex_base_2<Gt>`
 */
-template< typename Gt, typename StoreHidden >
-class Apollonius_graph_vertex_base_2 {
+  template< typename Gt, typename StoreHidden, typename Vb >
+  class Apollonius_graph_vertex_base_2 : public Vb {
```
Comment (MaelRL) [inline Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_graph_vertex_base_2.h:33]:
```suggestion
class Apollonius_graph_vertex_base_2 : public Vb {
```

File: Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_graph_vertex_base_2.h [hunk 3]
```diff
@@ -7,23 +7,30 @@ namespace CGAL {
...
+instantiated by `Triangulation_ds_vertex_base_2<>`.
+
 \cgalModels `ApolloniusGraphVertexBase_2`
 
 \sa `CGAL::Triangulation_data_structure_2<Vb,Fb>`
 \sa `CGAL::Apollonius_graph_hierarchy_vertex_base_2<Gt>`
 */
-template< typename Gt, typename StoreHidden >
-class Apollonius_graph_vertex_base_2 {
+  template< typename Gt, typename StoreHidden, typename Vb >
```
Comment (MaelRL) [inline Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_graph_vertex_base_2.h:32]:
```suggestion
template< typename Gt, typename StoreHidden, typename Vb >
```

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-39
