### PR TITLE
Polyhedron_demo: Fix the image item

### LINKED ISSUE #950: Polyhedron demo: buggy draw of `Scene_segmented_image_item.cpp`
From the file [`2×2×2.inr`](https://cgal.geometryfactory.com/~lrineau/2%c3%972%c3%972.inr), the loaded `Scene_segmented_image_item` is cleary wrong.
222-wrong
The real object encoded by the 3D image is more like that 3D mesh, produced by Mesh_3:
222-object

If both the mesh and the 3D  image are drawn at the same time, with the image in wireframe, that gives:
222-both
222-both-from-z

### PR DESCRIPTION
**Pull request by maxGimeno**
This partly fixes #950 
This PR fixes the geometry of the Scene_image_items by shrinking all the border voxels. (All voxels with a coordinate equals to 0 or dimension has its corresponding dimension divided by 2). 
With this fix, a scene_image_item and its mesh are overlapsed. (Before the fix, the Scene_image_item was twice the size of the mesh).

 The color bug is still there though.

### CODE REVIEW

File: Polyhedron/demo/Polyhedron/Scene_image_item.cpp [hunk 1]
```diff
@@ -323,18 +323,32 @@ Vertex_buffer_helper::push_vertex(std::size_t i, std::size_t j, std::size_t k)
...
+  vertices_.push_back( (dk - 0.5) * data_.vz());
 }
 
 void
 Vertex_buffer_helper::push_quads(std::size_t i, std::size_t j, std::size_t k)
 {
   int pos1 = vertex_index(i-dx(), j     , k);
   int pos2 = vertex_index(i-dx(), j-dy(), k);
-  int pos3 = vertex_index(i     , j-dy(), k);
+  int pos3 = vertex_index(i     , j-dy(), k) ;
```
Comment (lrineau) [inline Polyhedron/demo/Polyhedron/Scene_image_item.cpp]: Remove the added space.
